
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AccidentInfo` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model AccidentInfo
 * 
 */
export type AccidentInfoModel = runtime.Types.Result.DefaultSelection<Prisma.$AccidentInfoPayload>

export type AggregateAccidentInfo = {
  _count: AccidentInfoCountAggregateOutputType | null
  _min: AccidentInfoMinAggregateOutputType | null
  _max: AccidentInfoMaxAggregateOutputType | null
}

export type AccidentInfoMinAggregateOutputType = {
  id: string | null
  date: Date | null
  nameOfReporter: string | null
  info: string | null
  isWorkAccident: boolean | null
  isVictimFault: string | null
  isDrunk: string | null
}

export type AccidentInfoMaxAggregateOutputType = {
  id: string | null
  date: Date | null
  nameOfReporter: string | null
  info: string | null
  isWorkAccident: boolean | null
  isVictimFault: string | null
  isDrunk: string | null
}

export type AccidentInfoCountAggregateOutputType = {
  id: number
  date: number
  nameOfReporter: number
  info: number
  isWorkAccident: number
  isVictimFault: number
  isDrunk: number
  _all: number
}


export type AccidentInfoMinAggregateInputType = {
  id?: true
  date?: true
  nameOfReporter?: true
  info?: true
  isWorkAccident?: true
  isVictimFault?: true
  isDrunk?: true
}

export type AccidentInfoMaxAggregateInputType = {
  id?: true
  date?: true
  nameOfReporter?: true
  info?: true
  isWorkAccident?: true
  isVictimFault?: true
  isDrunk?: true
}

export type AccidentInfoCountAggregateInputType = {
  id?: true
  date?: true
  nameOfReporter?: true
  info?: true
  isWorkAccident?: true
  isVictimFault?: true
  isDrunk?: true
  _all?: true
}

export type AccidentInfoAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AccidentInfo to aggregate.
   */
  where?: Prisma.AccidentInfoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AccidentInfos to fetch.
   */
  orderBy?: Prisma.AccidentInfoOrderByWithRelationInput | Prisma.AccidentInfoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AccidentInfoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AccidentInfos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AccidentInfos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AccidentInfos
  **/
  _count?: true | AccidentInfoCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AccidentInfoMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AccidentInfoMaxAggregateInputType
}

export type GetAccidentInfoAggregateType<T extends AccidentInfoAggregateArgs> = {
      [P in keyof T & keyof AggregateAccidentInfo]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAccidentInfo[P]>
    : Prisma.GetScalarType<T[P], AggregateAccidentInfo[P]>
}




export type AccidentInfoGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AccidentInfoWhereInput
  orderBy?: Prisma.AccidentInfoOrderByWithAggregationInput | Prisma.AccidentInfoOrderByWithAggregationInput[]
  by: Prisma.AccidentInfoScalarFieldEnum[] | Prisma.AccidentInfoScalarFieldEnum
  having?: Prisma.AccidentInfoScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AccidentInfoCountAggregateInputType | true
  _min?: AccidentInfoMinAggregateInputType
  _max?: AccidentInfoMaxAggregateInputType
}

export type AccidentInfoGroupByOutputType = {
  id: string
  date: Date
  nameOfReporter: string
  info: string
  isWorkAccident: boolean
  isVictimFault: string
  isDrunk: string
  _count: AccidentInfoCountAggregateOutputType | null
  _min: AccidentInfoMinAggregateOutputType | null
  _max: AccidentInfoMaxAggregateOutputType | null
}

type GetAccidentInfoGroupByPayload<T extends AccidentInfoGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AccidentInfoGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AccidentInfoGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AccidentInfoGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AccidentInfoGroupByOutputType[P]>
      }
    >
  >



export type AccidentInfoWhereInput = {
  AND?: Prisma.AccidentInfoWhereInput | Prisma.AccidentInfoWhereInput[]
  OR?: Prisma.AccidentInfoWhereInput[]
  NOT?: Prisma.AccidentInfoWhereInput | Prisma.AccidentInfoWhereInput[]
  id?: Prisma.StringFilter<"AccidentInfo"> | string
  date?: Prisma.DateTimeFilter<"AccidentInfo"> | Date | string
  nameOfReporter?: Prisma.StringFilter<"AccidentInfo"> | string
  info?: Prisma.StringFilter<"AccidentInfo"> | string
  isWorkAccident?: Prisma.BoolFilter<"AccidentInfo"> | boolean
  isVictimFault?: Prisma.StringFilter<"AccidentInfo"> | string
  isDrunk?: Prisma.StringFilter<"AccidentInfo"> | string
  witnesses?: Prisma.WitnessListRelationFilter
  cases?: Prisma.CaseListRelationFilter
}

export type AccidentInfoOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  nameOfReporter?: Prisma.SortOrder
  info?: Prisma.SortOrder
  isWorkAccident?: Prisma.SortOrder
  isVictimFault?: Prisma.SortOrder
  isDrunk?: Prisma.SortOrder
  witnesses?: Prisma.WitnessOrderByRelationAggregateInput
  cases?: Prisma.CaseOrderByRelationAggregateInput
}

export type AccidentInfoWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.AccidentInfoWhereInput | Prisma.AccidentInfoWhereInput[]
  OR?: Prisma.AccidentInfoWhereInput[]
  NOT?: Prisma.AccidentInfoWhereInput | Prisma.AccidentInfoWhereInput[]
  date?: Prisma.DateTimeFilter<"AccidentInfo"> | Date | string
  nameOfReporter?: Prisma.StringFilter<"AccidentInfo"> | string
  info?: Prisma.StringFilter<"AccidentInfo"> | string
  isWorkAccident?: Prisma.BoolFilter<"AccidentInfo"> | boolean
  isVictimFault?: Prisma.StringFilter<"AccidentInfo"> | string
  isDrunk?: Prisma.StringFilter<"AccidentInfo"> | string
  witnesses?: Prisma.WitnessListRelationFilter
  cases?: Prisma.CaseListRelationFilter
}, "id">

export type AccidentInfoOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  nameOfReporter?: Prisma.SortOrder
  info?: Prisma.SortOrder
  isWorkAccident?: Prisma.SortOrder
  isVictimFault?: Prisma.SortOrder
  isDrunk?: Prisma.SortOrder
  _count?: Prisma.AccidentInfoCountOrderByAggregateInput
  _max?: Prisma.AccidentInfoMaxOrderByAggregateInput
  _min?: Prisma.AccidentInfoMinOrderByAggregateInput
}

export type AccidentInfoScalarWhereWithAggregatesInput = {
  AND?: Prisma.AccidentInfoScalarWhereWithAggregatesInput | Prisma.AccidentInfoScalarWhereWithAggregatesInput[]
  OR?: Prisma.AccidentInfoScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AccidentInfoScalarWhereWithAggregatesInput | Prisma.AccidentInfoScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"AccidentInfo"> | string
  date?: Prisma.DateTimeWithAggregatesFilter<"AccidentInfo"> | Date | string
  nameOfReporter?: Prisma.StringWithAggregatesFilter<"AccidentInfo"> | string
  info?: Prisma.StringWithAggregatesFilter<"AccidentInfo"> | string
  isWorkAccident?: Prisma.BoolWithAggregatesFilter<"AccidentInfo"> | boolean
  isVictimFault?: Prisma.StringWithAggregatesFilter<"AccidentInfo"> | string
  isDrunk?: Prisma.StringWithAggregatesFilter<"AccidentInfo"> | string
}

export type AccidentInfoCreateInput = {
  id?: string
  date: Date | string
  nameOfReporter: string
  info: string
  isWorkAccident: boolean
  isVictimFault: string
  isDrunk: string
  witnesses?: Prisma.WitnessCreateNestedManyWithoutAccidentInfoInput
  cases?: Prisma.CaseCreateNestedManyWithoutAccidentInfoInput
}

export type AccidentInfoUncheckedCreateInput = {
  id?: string
  date: Date | string
  nameOfReporter: string
  info: string
  isWorkAccident: boolean
  isVictimFault: string
  isDrunk: string
  witnesses?: Prisma.WitnessUncheckedCreateNestedManyWithoutAccidentInfoInput
  cases?: Prisma.CaseUncheckedCreateNestedManyWithoutAccidentInfoInput
}

export type AccidentInfoUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  nameOfReporter?: Prisma.StringFieldUpdateOperationsInput | string
  info?: Prisma.StringFieldUpdateOperationsInput | string
  isWorkAccident?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isVictimFault?: Prisma.StringFieldUpdateOperationsInput | string
  isDrunk?: Prisma.StringFieldUpdateOperationsInput | string
  witnesses?: Prisma.WitnessUpdateManyWithoutAccidentInfoNestedInput
  cases?: Prisma.CaseUpdateManyWithoutAccidentInfoNestedInput
}

export type AccidentInfoUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  nameOfReporter?: Prisma.StringFieldUpdateOperationsInput | string
  info?: Prisma.StringFieldUpdateOperationsInput | string
  isWorkAccident?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isVictimFault?: Prisma.StringFieldUpdateOperationsInput | string
  isDrunk?: Prisma.StringFieldUpdateOperationsInput | string
  witnesses?: Prisma.WitnessUncheckedUpdateManyWithoutAccidentInfoNestedInput
  cases?: Prisma.CaseUncheckedUpdateManyWithoutAccidentInfoNestedInput
}

export type AccidentInfoCreateManyInput = {
  id?: string
  date: Date | string
  nameOfReporter: string
  info: string
  isWorkAccident: boolean
  isVictimFault: string
  isDrunk: string
}

export type AccidentInfoUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  nameOfReporter?: Prisma.StringFieldUpdateOperationsInput | string
  info?: Prisma.StringFieldUpdateOperationsInput | string
  isWorkAccident?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isVictimFault?: Prisma.StringFieldUpdateOperationsInput | string
  isDrunk?: Prisma.StringFieldUpdateOperationsInput | string
}

export type AccidentInfoUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  nameOfReporter?: Prisma.StringFieldUpdateOperationsInput | string
  info?: Prisma.StringFieldUpdateOperationsInput | string
  isWorkAccident?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isVictimFault?: Prisma.StringFieldUpdateOperationsInput | string
  isDrunk?: Prisma.StringFieldUpdateOperationsInput | string
}

export type AccidentInfoScalarRelationFilter = {
  is?: Prisma.AccidentInfoWhereInput
  isNot?: Prisma.AccidentInfoWhereInput
}

export type AccidentInfoCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  nameOfReporter?: Prisma.SortOrder
  info?: Prisma.SortOrder
  isWorkAccident?: Prisma.SortOrder
  isVictimFault?: Prisma.SortOrder
  isDrunk?: Prisma.SortOrder
}

export type AccidentInfoMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  nameOfReporter?: Prisma.SortOrder
  info?: Prisma.SortOrder
  isWorkAccident?: Prisma.SortOrder
  isVictimFault?: Prisma.SortOrder
  isDrunk?: Prisma.SortOrder
}

export type AccidentInfoMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  nameOfReporter?: Prisma.SortOrder
  info?: Prisma.SortOrder
  isWorkAccident?: Prisma.SortOrder
  isVictimFault?: Prisma.SortOrder
  isDrunk?: Prisma.SortOrder
}

export type AccidentInfoCreateNestedOneWithoutCasesInput = {
  create?: Prisma.XOR<Prisma.AccidentInfoCreateWithoutCasesInput, Prisma.AccidentInfoUncheckedCreateWithoutCasesInput>
  connectOrCreate?: Prisma.AccidentInfoCreateOrConnectWithoutCasesInput
  connect?: Prisma.AccidentInfoWhereUniqueInput
}

export type AccidentInfoUpdateOneRequiredWithoutCasesNestedInput = {
  create?: Prisma.XOR<Prisma.AccidentInfoCreateWithoutCasesInput, Prisma.AccidentInfoUncheckedCreateWithoutCasesInput>
  connectOrCreate?: Prisma.AccidentInfoCreateOrConnectWithoutCasesInput
  upsert?: Prisma.AccidentInfoUpsertWithoutCasesInput
  connect?: Prisma.AccidentInfoWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AccidentInfoUpdateToOneWithWhereWithoutCasesInput, Prisma.AccidentInfoUpdateWithoutCasesInput>, Prisma.AccidentInfoUncheckedUpdateWithoutCasesInput>
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type AccidentInfoCreateNestedOneWithoutWitnessesInput = {
  create?: Prisma.XOR<Prisma.AccidentInfoCreateWithoutWitnessesInput, Prisma.AccidentInfoUncheckedCreateWithoutWitnessesInput>
  connectOrCreate?: Prisma.AccidentInfoCreateOrConnectWithoutWitnessesInput
  connect?: Prisma.AccidentInfoWhereUniqueInput
}

export type AccidentInfoUpdateOneRequiredWithoutWitnessesNestedInput = {
  create?: Prisma.XOR<Prisma.AccidentInfoCreateWithoutWitnessesInput, Prisma.AccidentInfoUncheckedCreateWithoutWitnessesInput>
  connectOrCreate?: Prisma.AccidentInfoCreateOrConnectWithoutWitnessesInput
  upsert?: Prisma.AccidentInfoUpsertWithoutWitnessesInput
  connect?: Prisma.AccidentInfoWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AccidentInfoUpdateToOneWithWhereWithoutWitnessesInput, Prisma.AccidentInfoUpdateWithoutWitnessesInput>, Prisma.AccidentInfoUncheckedUpdateWithoutWitnessesInput>
}

export type AccidentInfoCreateWithoutCasesInput = {
  id?: string
  date: Date | string
  nameOfReporter: string
  info: string
  isWorkAccident: boolean
  isVictimFault: string
  isDrunk: string
  witnesses?: Prisma.WitnessCreateNestedManyWithoutAccidentInfoInput
}

export type AccidentInfoUncheckedCreateWithoutCasesInput = {
  id?: string
  date: Date | string
  nameOfReporter: string
  info: string
  isWorkAccident: boolean
  isVictimFault: string
  isDrunk: string
  witnesses?: Prisma.WitnessUncheckedCreateNestedManyWithoutAccidentInfoInput
}

export type AccidentInfoCreateOrConnectWithoutCasesInput = {
  where: Prisma.AccidentInfoWhereUniqueInput
  create: Prisma.XOR<Prisma.AccidentInfoCreateWithoutCasesInput, Prisma.AccidentInfoUncheckedCreateWithoutCasesInput>
}

export type AccidentInfoUpsertWithoutCasesInput = {
  update: Prisma.XOR<Prisma.AccidentInfoUpdateWithoutCasesInput, Prisma.AccidentInfoUncheckedUpdateWithoutCasesInput>
  create: Prisma.XOR<Prisma.AccidentInfoCreateWithoutCasesInput, Prisma.AccidentInfoUncheckedCreateWithoutCasesInput>
  where?: Prisma.AccidentInfoWhereInput
}

export type AccidentInfoUpdateToOneWithWhereWithoutCasesInput = {
  where?: Prisma.AccidentInfoWhereInput
  data: Prisma.XOR<Prisma.AccidentInfoUpdateWithoutCasesInput, Prisma.AccidentInfoUncheckedUpdateWithoutCasesInput>
}

export type AccidentInfoUpdateWithoutCasesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  nameOfReporter?: Prisma.StringFieldUpdateOperationsInput | string
  info?: Prisma.StringFieldUpdateOperationsInput | string
  isWorkAccident?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isVictimFault?: Prisma.StringFieldUpdateOperationsInput | string
  isDrunk?: Prisma.StringFieldUpdateOperationsInput | string
  witnesses?: Prisma.WitnessUpdateManyWithoutAccidentInfoNestedInput
}

export type AccidentInfoUncheckedUpdateWithoutCasesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  nameOfReporter?: Prisma.StringFieldUpdateOperationsInput | string
  info?: Prisma.StringFieldUpdateOperationsInput | string
  isWorkAccident?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isVictimFault?: Prisma.StringFieldUpdateOperationsInput | string
  isDrunk?: Prisma.StringFieldUpdateOperationsInput | string
  witnesses?: Prisma.WitnessUncheckedUpdateManyWithoutAccidentInfoNestedInput
}

export type AccidentInfoCreateWithoutWitnessesInput = {
  id?: string
  date: Date | string
  nameOfReporter: string
  info: string
  isWorkAccident: boolean
  isVictimFault: string
  isDrunk: string
  cases?: Prisma.CaseCreateNestedManyWithoutAccidentInfoInput
}

export type AccidentInfoUncheckedCreateWithoutWitnessesInput = {
  id?: string
  date: Date | string
  nameOfReporter: string
  info: string
  isWorkAccident: boolean
  isVictimFault: string
  isDrunk: string
  cases?: Prisma.CaseUncheckedCreateNestedManyWithoutAccidentInfoInput
}

export type AccidentInfoCreateOrConnectWithoutWitnessesInput = {
  where: Prisma.AccidentInfoWhereUniqueInput
  create: Prisma.XOR<Prisma.AccidentInfoCreateWithoutWitnessesInput, Prisma.AccidentInfoUncheckedCreateWithoutWitnessesInput>
}

export type AccidentInfoUpsertWithoutWitnessesInput = {
  update: Prisma.XOR<Prisma.AccidentInfoUpdateWithoutWitnessesInput, Prisma.AccidentInfoUncheckedUpdateWithoutWitnessesInput>
  create: Prisma.XOR<Prisma.AccidentInfoCreateWithoutWitnessesInput, Prisma.AccidentInfoUncheckedCreateWithoutWitnessesInput>
  where?: Prisma.AccidentInfoWhereInput
}

export type AccidentInfoUpdateToOneWithWhereWithoutWitnessesInput = {
  where?: Prisma.AccidentInfoWhereInput
  data: Prisma.XOR<Prisma.AccidentInfoUpdateWithoutWitnessesInput, Prisma.AccidentInfoUncheckedUpdateWithoutWitnessesInput>
}

export type AccidentInfoUpdateWithoutWitnessesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  nameOfReporter?: Prisma.StringFieldUpdateOperationsInput | string
  info?: Prisma.StringFieldUpdateOperationsInput | string
  isWorkAccident?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isVictimFault?: Prisma.StringFieldUpdateOperationsInput | string
  isDrunk?: Prisma.StringFieldUpdateOperationsInput | string
  cases?: Prisma.CaseUpdateManyWithoutAccidentInfoNestedInput
}

export type AccidentInfoUncheckedUpdateWithoutWitnessesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  nameOfReporter?: Prisma.StringFieldUpdateOperationsInput | string
  info?: Prisma.StringFieldUpdateOperationsInput | string
  isWorkAccident?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isVictimFault?: Prisma.StringFieldUpdateOperationsInput | string
  isDrunk?: Prisma.StringFieldUpdateOperationsInput | string
  cases?: Prisma.CaseUncheckedUpdateManyWithoutAccidentInfoNestedInput
}


/**
 * Count Type AccidentInfoCountOutputType
 */

export type AccidentInfoCountOutputType = {
  witnesses: number
  cases: number
}

export type AccidentInfoCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  witnesses?: boolean | AccidentInfoCountOutputTypeCountWitnessesArgs
  cases?: boolean | AccidentInfoCountOutputTypeCountCasesArgs
}

/**
 * AccidentInfoCountOutputType without action
 */
export type AccidentInfoCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccidentInfoCountOutputType
   */
  select?: Prisma.AccidentInfoCountOutputTypeSelect<ExtArgs> | null
}

/**
 * AccidentInfoCountOutputType without action
 */
export type AccidentInfoCountOutputTypeCountWitnessesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.WitnessWhereInput
}

/**
 * AccidentInfoCountOutputType without action
 */
export type AccidentInfoCountOutputTypeCountCasesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CaseWhereInput
}


export type AccidentInfoSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  date?: boolean
  nameOfReporter?: boolean
  info?: boolean
  isWorkAccident?: boolean
  isVictimFault?: boolean
  isDrunk?: boolean
  witnesses?: boolean | Prisma.AccidentInfo$witnessesArgs<ExtArgs>
  cases?: boolean | Prisma.AccidentInfo$casesArgs<ExtArgs>
  _count?: boolean | Prisma.AccidentInfoCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["accidentInfo"]>

export type AccidentInfoSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  date?: boolean
  nameOfReporter?: boolean
  info?: boolean
  isWorkAccident?: boolean
  isVictimFault?: boolean
  isDrunk?: boolean
}, ExtArgs["result"]["accidentInfo"]>

export type AccidentInfoSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  date?: boolean
  nameOfReporter?: boolean
  info?: boolean
  isWorkAccident?: boolean
  isVictimFault?: boolean
  isDrunk?: boolean
}, ExtArgs["result"]["accidentInfo"]>

export type AccidentInfoSelectScalar = {
  id?: boolean
  date?: boolean
  nameOfReporter?: boolean
  info?: boolean
  isWorkAccident?: boolean
  isVictimFault?: boolean
  isDrunk?: boolean
}

export type AccidentInfoOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "date" | "nameOfReporter" | "info" | "isWorkAccident" | "isVictimFault" | "isDrunk", ExtArgs["result"]["accidentInfo"]>
export type AccidentInfoInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  witnesses?: boolean | Prisma.AccidentInfo$witnessesArgs<ExtArgs>
  cases?: boolean | Prisma.AccidentInfo$casesArgs<ExtArgs>
  _count?: boolean | Prisma.AccidentInfoCountOutputTypeDefaultArgs<ExtArgs>
}
export type AccidentInfoIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type AccidentInfoIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $AccidentInfoPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AccidentInfo"
  objects: {
    witnesses: Prisma.$WitnessPayload<ExtArgs>[]
    cases: Prisma.$CasePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    date: Date
    nameOfReporter: string
    info: string
    isWorkAccident: boolean
    isVictimFault: string
    isDrunk: string
  }, ExtArgs["result"]["accidentInfo"]>
  composites: {}
}

export type AccidentInfoGetPayload<S extends boolean | null | undefined | AccidentInfoDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AccidentInfoPayload, S>

export type AccidentInfoCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AccidentInfoFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AccidentInfoCountAggregateInputType | true
  }

export interface AccidentInfoDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AccidentInfo'], meta: { name: 'AccidentInfo' } }
  /**
   * Find zero or one AccidentInfo that matches the filter.
   * @param {AccidentInfoFindUniqueArgs} args - Arguments to find a AccidentInfo
   * @example
   * // Get one AccidentInfo
   * const accidentInfo = await prisma.accidentInfo.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AccidentInfoFindUniqueArgs>(args: Prisma.SelectSubset<T, AccidentInfoFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AccidentInfoClient<runtime.Types.Result.GetResult<Prisma.$AccidentInfoPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AccidentInfo that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AccidentInfoFindUniqueOrThrowArgs} args - Arguments to find a AccidentInfo
   * @example
   * // Get one AccidentInfo
   * const accidentInfo = await prisma.accidentInfo.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AccidentInfoFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AccidentInfoFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AccidentInfoClient<runtime.Types.Result.GetResult<Prisma.$AccidentInfoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AccidentInfo that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccidentInfoFindFirstArgs} args - Arguments to find a AccidentInfo
   * @example
   * // Get one AccidentInfo
   * const accidentInfo = await prisma.accidentInfo.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AccidentInfoFindFirstArgs>(args?: Prisma.SelectSubset<T, AccidentInfoFindFirstArgs<ExtArgs>>): Prisma.Prisma__AccidentInfoClient<runtime.Types.Result.GetResult<Prisma.$AccidentInfoPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AccidentInfo that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccidentInfoFindFirstOrThrowArgs} args - Arguments to find a AccidentInfo
   * @example
   * // Get one AccidentInfo
   * const accidentInfo = await prisma.accidentInfo.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AccidentInfoFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AccidentInfoFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AccidentInfoClient<runtime.Types.Result.GetResult<Prisma.$AccidentInfoPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AccidentInfos that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccidentInfoFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AccidentInfos
   * const accidentInfos = await prisma.accidentInfo.findMany()
   * 
   * // Get first 10 AccidentInfos
   * const accidentInfos = await prisma.accidentInfo.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const accidentInfoWithIdOnly = await prisma.accidentInfo.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AccidentInfoFindManyArgs>(args?: Prisma.SelectSubset<T, AccidentInfoFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AccidentInfoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AccidentInfo.
   * @param {AccidentInfoCreateArgs} args - Arguments to create a AccidentInfo.
   * @example
   * // Create one AccidentInfo
   * const AccidentInfo = await prisma.accidentInfo.create({
   *   data: {
   *     // ... data to create a AccidentInfo
   *   }
   * })
   * 
   */
  create<T extends AccidentInfoCreateArgs>(args: Prisma.SelectSubset<T, AccidentInfoCreateArgs<ExtArgs>>): Prisma.Prisma__AccidentInfoClient<runtime.Types.Result.GetResult<Prisma.$AccidentInfoPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AccidentInfos.
   * @param {AccidentInfoCreateManyArgs} args - Arguments to create many AccidentInfos.
   * @example
   * // Create many AccidentInfos
   * const accidentInfo = await prisma.accidentInfo.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AccidentInfoCreateManyArgs>(args?: Prisma.SelectSubset<T, AccidentInfoCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AccidentInfos and returns the data saved in the database.
   * @param {AccidentInfoCreateManyAndReturnArgs} args - Arguments to create many AccidentInfos.
   * @example
   * // Create many AccidentInfos
   * const accidentInfo = await prisma.accidentInfo.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AccidentInfos and only return the `id`
   * const accidentInfoWithIdOnly = await prisma.accidentInfo.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AccidentInfoCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AccidentInfoCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AccidentInfoPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AccidentInfo.
   * @param {AccidentInfoDeleteArgs} args - Arguments to delete one AccidentInfo.
   * @example
   * // Delete one AccidentInfo
   * const AccidentInfo = await prisma.accidentInfo.delete({
   *   where: {
   *     // ... filter to delete one AccidentInfo
   *   }
   * })
   * 
   */
  delete<T extends AccidentInfoDeleteArgs>(args: Prisma.SelectSubset<T, AccidentInfoDeleteArgs<ExtArgs>>): Prisma.Prisma__AccidentInfoClient<runtime.Types.Result.GetResult<Prisma.$AccidentInfoPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AccidentInfo.
   * @param {AccidentInfoUpdateArgs} args - Arguments to update one AccidentInfo.
   * @example
   * // Update one AccidentInfo
   * const accidentInfo = await prisma.accidentInfo.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AccidentInfoUpdateArgs>(args: Prisma.SelectSubset<T, AccidentInfoUpdateArgs<ExtArgs>>): Prisma.Prisma__AccidentInfoClient<runtime.Types.Result.GetResult<Prisma.$AccidentInfoPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AccidentInfos.
   * @param {AccidentInfoDeleteManyArgs} args - Arguments to filter AccidentInfos to delete.
   * @example
   * // Delete a few AccidentInfos
   * const { count } = await prisma.accidentInfo.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AccidentInfoDeleteManyArgs>(args?: Prisma.SelectSubset<T, AccidentInfoDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AccidentInfos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccidentInfoUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AccidentInfos
   * const accidentInfo = await prisma.accidentInfo.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AccidentInfoUpdateManyArgs>(args: Prisma.SelectSubset<T, AccidentInfoUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AccidentInfos and returns the data updated in the database.
   * @param {AccidentInfoUpdateManyAndReturnArgs} args - Arguments to update many AccidentInfos.
   * @example
   * // Update many AccidentInfos
   * const accidentInfo = await prisma.accidentInfo.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AccidentInfos and only return the `id`
   * const accidentInfoWithIdOnly = await prisma.accidentInfo.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AccidentInfoUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AccidentInfoUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AccidentInfoPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AccidentInfo.
   * @param {AccidentInfoUpsertArgs} args - Arguments to update or create a AccidentInfo.
   * @example
   * // Update or create a AccidentInfo
   * const accidentInfo = await prisma.accidentInfo.upsert({
   *   create: {
   *     // ... data to create a AccidentInfo
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AccidentInfo we want to update
   *   }
   * })
   */
  upsert<T extends AccidentInfoUpsertArgs>(args: Prisma.SelectSubset<T, AccidentInfoUpsertArgs<ExtArgs>>): Prisma.Prisma__AccidentInfoClient<runtime.Types.Result.GetResult<Prisma.$AccidentInfoPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AccidentInfos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccidentInfoCountArgs} args - Arguments to filter AccidentInfos to count.
   * @example
   * // Count the number of AccidentInfos
   * const count = await prisma.accidentInfo.count({
   *   where: {
   *     // ... the filter for the AccidentInfos we want to count
   *   }
   * })
  **/
  count<T extends AccidentInfoCountArgs>(
    args?: Prisma.Subset<T, AccidentInfoCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AccidentInfoCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AccidentInfo.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccidentInfoAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AccidentInfoAggregateArgs>(args: Prisma.Subset<T, AccidentInfoAggregateArgs>): Prisma.PrismaPromise<GetAccidentInfoAggregateType<T>>

  /**
   * Group by AccidentInfo.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccidentInfoGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AccidentInfoGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AccidentInfoGroupByArgs['orderBy'] }
      : { orderBy?: AccidentInfoGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AccidentInfoGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAccidentInfoGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AccidentInfo model
 */
readonly fields: AccidentInfoFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AccidentInfo.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AccidentInfoClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  witnesses<T extends Prisma.AccidentInfo$witnessesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AccidentInfo$witnessesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WitnessPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  cases<T extends Prisma.AccidentInfo$casesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AccidentInfo$casesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CasePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AccidentInfo model
 */
export interface AccidentInfoFieldRefs {
  readonly id: Prisma.FieldRef<"AccidentInfo", 'String'>
  readonly date: Prisma.FieldRef<"AccidentInfo", 'DateTime'>
  readonly nameOfReporter: Prisma.FieldRef<"AccidentInfo", 'String'>
  readonly info: Prisma.FieldRef<"AccidentInfo", 'String'>
  readonly isWorkAccident: Prisma.FieldRef<"AccidentInfo", 'Boolean'>
  readonly isVictimFault: Prisma.FieldRef<"AccidentInfo", 'String'>
  readonly isDrunk: Prisma.FieldRef<"AccidentInfo", 'String'>
}
    

// Custom InputTypes
/**
 * AccidentInfo findUnique
 */
export type AccidentInfoFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccidentInfo
   */
  select?: Prisma.AccidentInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccidentInfo
   */
  omit?: Prisma.AccidentInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccidentInfoInclude<ExtArgs> | null
  /**
   * Filter, which AccidentInfo to fetch.
   */
  where: Prisma.AccidentInfoWhereUniqueInput
}

/**
 * AccidentInfo findUniqueOrThrow
 */
export type AccidentInfoFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccidentInfo
   */
  select?: Prisma.AccidentInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccidentInfo
   */
  omit?: Prisma.AccidentInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccidentInfoInclude<ExtArgs> | null
  /**
   * Filter, which AccidentInfo to fetch.
   */
  where: Prisma.AccidentInfoWhereUniqueInput
}

/**
 * AccidentInfo findFirst
 */
export type AccidentInfoFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccidentInfo
   */
  select?: Prisma.AccidentInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccidentInfo
   */
  omit?: Prisma.AccidentInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccidentInfoInclude<ExtArgs> | null
  /**
   * Filter, which AccidentInfo to fetch.
   */
  where?: Prisma.AccidentInfoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AccidentInfos to fetch.
   */
  orderBy?: Prisma.AccidentInfoOrderByWithRelationInput | Prisma.AccidentInfoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AccidentInfos.
   */
  cursor?: Prisma.AccidentInfoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AccidentInfos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AccidentInfos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AccidentInfos.
   */
  distinct?: Prisma.AccidentInfoScalarFieldEnum | Prisma.AccidentInfoScalarFieldEnum[]
}

/**
 * AccidentInfo findFirstOrThrow
 */
export type AccidentInfoFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccidentInfo
   */
  select?: Prisma.AccidentInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccidentInfo
   */
  omit?: Prisma.AccidentInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccidentInfoInclude<ExtArgs> | null
  /**
   * Filter, which AccidentInfo to fetch.
   */
  where?: Prisma.AccidentInfoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AccidentInfos to fetch.
   */
  orderBy?: Prisma.AccidentInfoOrderByWithRelationInput | Prisma.AccidentInfoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AccidentInfos.
   */
  cursor?: Prisma.AccidentInfoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AccidentInfos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AccidentInfos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AccidentInfos.
   */
  distinct?: Prisma.AccidentInfoScalarFieldEnum | Prisma.AccidentInfoScalarFieldEnum[]
}

/**
 * AccidentInfo findMany
 */
export type AccidentInfoFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccidentInfo
   */
  select?: Prisma.AccidentInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccidentInfo
   */
  omit?: Prisma.AccidentInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccidentInfoInclude<ExtArgs> | null
  /**
   * Filter, which AccidentInfos to fetch.
   */
  where?: Prisma.AccidentInfoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AccidentInfos to fetch.
   */
  orderBy?: Prisma.AccidentInfoOrderByWithRelationInput | Prisma.AccidentInfoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AccidentInfos.
   */
  cursor?: Prisma.AccidentInfoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AccidentInfos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AccidentInfos.
   */
  skip?: number
  distinct?: Prisma.AccidentInfoScalarFieldEnum | Prisma.AccidentInfoScalarFieldEnum[]
}

/**
 * AccidentInfo create
 */
export type AccidentInfoCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccidentInfo
   */
  select?: Prisma.AccidentInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccidentInfo
   */
  omit?: Prisma.AccidentInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccidentInfoInclude<ExtArgs> | null
  /**
   * The data needed to create a AccidentInfo.
   */
  data: Prisma.XOR<Prisma.AccidentInfoCreateInput, Prisma.AccidentInfoUncheckedCreateInput>
}

/**
 * AccidentInfo createMany
 */
export type AccidentInfoCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AccidentInfos.
   */
  data: Prisma.AccidentInfoCreateManyInput | Prisma.AccidentInfoCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AccidentInfo createManyAndReturn
 */
export type AccidentInfoCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccidentInfo
   */
  select?: Prisma.AccidentInfoSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AccidentInfo
   */
  omit?: Prisma.AccidentInfoOmit<ExtArgs> | null
  /**
   * The data used to create many AccidentInfos.
   */
  data: Prisma.AccidentInfoCreateManyInput | Prisma.AccidentInfoCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AccidentInfo update
 */
export type AccidentInfoUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccidentInfo
   */
  select?: Prisma.AccidentInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccidentInfo
   */
  omit?: Prisma.AccidentInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccidentInfoInclude<ExtArgs> | null
  /**
   * The data needed to update a AccidentInfo.
   */
  data: Prisma.XOR<Prisma.AccidentInfoUpdateInput, Prisma.AccidentInfoUncheckedUpdateInput>
  /**
   * Choose, which AccidentInfo to update.
   */
  where: Prisma.AccidentInfoWhereUniqueInput
}

/**
 * AccidentInfo updateMany
 */
export type AccidentInfoUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AccidentInfos.
   */
  data: Prisma.XOR<Prisma.AccidentInfoUpdateManyMutationInput, Prisma.AccidentInfoUncheckedUpdateManyInput>
  /**
   * Filter which AccidentInfos to update
   */
  where?: Prisma.AccidentInfoWhereInput
  /**
   * Limit how many AccidentInfos to update.
   */
  limit?: number
}

/**
 * AccidentInfo updateManyAndReturn
 */
export type AccidentInfoUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccidentInfo
   */
  select?: Prisma.AccidentInfoSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AccidentInfo
   */
  omit?: Prisma.AccidentInfoOmit<ExtArgs> | null
  /**
   * The data used to update AccidentInfos.
   */
  data: Prisma.XOR<Prisma.AccidentInfoUpdateManyMutationInput, Prisma.AccidentInfoUncheckedUpdateManyInput>
  /**
   * Filter which AccidentInfos to update
   */
  where?: Prisma.AccidentInfoWhereInput
  /**
   * Limit how many AccidentInfos to update.
   */
  limit?: number
}

/**
 * AccidentInfo upsert
 */
export type AccidentInfoUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccidentInfo
   */
  select?: Prisma.AccidentInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccidentInfo
   */
  omit?: Prisma.AccidentInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccidentInfoInclude<ExtArgs> | null
  /**
   * The filter to search for the AccidentInfo to update in case it exists.
   */
  where: Prisma.AccidentInfoWhereUniqueInput
  /**
   * In case the AccidentInfo found by the `where` argument doesn't exist, create a new AccidentInfo with this data.
   */
  create: Prisma.XOR<Prisma.AccidentInfoCreateInput, Prisma.AccidentInfoUncheckedCreateInput>
  /**
   * In case the AccidentInfo was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AccidentInfoUpdateInput, Prisma.AccidentInfoUncheckedUpdateInput>
}

/**
 * AccidentInfo delete
 */
export type AccidentInfoDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccidentInfo
   */
  select?: Prisma.AccidentInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccidentInfo
   */
  omit?: Prisma.AccidentInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccidentInfoInclude<ExtArgs> | null
  /**
   * Filter which AccidentInfo to delete.
   */
  where: Prisma.AccidentInfoWhereUniqueInput
}

/**
 * AccidentInfo deleteMany
 */
export type AccidentInfoDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AccidentInfos to delete
   */
  where?: Prisma.AccidentInfoWhereInput
  /**
   * Limit how many AccidentInfos to delete.
   */
  limit?: number
}

/**
 * AccidentInfo.witnesses
 */
export type AccidentInfo$witnessesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Witness
   */
  select?: Prisma.WitnessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Witness
   */
  omit?: Prisma.WitnessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WitnessInclude<ExtArgs> | null
  where?: Prisma.WitnessWhereInput
  orderBy?: Prisma.WitnessOrderByWithRelationInput | Prisma.WitnessOrderByWithRelationInput[]
  cursor?: Prisma.WitnessWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.WitnessScalarFieldEnum | Prisma.WitnessScalarFieldEnum[]
}

/**
 * AccidentInfo.cases
 */
export type AccidentInfo$casesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Case
   */
  select?: Prisma.CaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Case
   */
  omit?: Prisma.CaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaseInclude<ExtArgs> | null
  where?: Prisma.CaseWhereInput
  orderBy?: Prisma.CaseOrderByWithRelationInput | Prisma.CaseOrderByWithRelationInput[]
  cursor?: Prisma.CaseWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.CaseScalarFieldEnum | Prisma.CaseScalarFieldEnum[]
}

/**
 * AccidentInfo without action
 */
export type AccidentInfoDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccidentInfo
   */
  select?: Prisma.AccidentInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccidentInfo
   */
  omit?: Prisma.AccidentInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccidentInfoInclude<ExtArgs> | null
}
