/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `Case` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Case
 *
 */
export type CaseModel = runtime.Types.Result.DefaultSelection<Prisma.$CasePayload>

export type AggregateCase = {
  _count: CaseCountAggregateOutputType | null
  _min: CaseMinAggregateOutputType | null
  _max: CaseMaxAggregateOutputType | null
}

export type CaseMinAggregateOutputType = {
  id: string | null
  caseNumber: string | null
  comments: string | null
  payerInfoId: string | null
  victimInfoId: string | null
  cardOfAccidentId: string | null
  createdAt: Date | null
  updatedAt: Date | null
  accidentInfoId: string | null
}

export type CaseMaxAggregateOutputType = {
  id: string | null
  caseNumber: string | null
  comments: string | null
  payerInfoId: string | null
  victimInfoId: string | null
  cardOfAccidentId: string | null
  createdAt: Date | null
  updatedAt: Date | null
  accidentInfoId: string | null
}

export type CaseCountAggregateOutputType = {
  id: number
  caseNumber: number
  comments: number
  payerInfoId: number
  victimInfoId: number
  cardOfAccidentId: number
  createdAt: number
  updatedAt: number
  accidentInfoId: number
  _all: number
}

export type CaseMinAggregateInputType = {
  id?: true
  caseNumber?: true
  comments?: true
  payerInfoId?: true
  victimInfoId?: true
  cardOfAccidentId?: true
  createdAt?: true
  updatedAt?: true
  accidentInfoId?: true
}

export type CaseMaxAggregateInputType = {
  id?: true
  caseNumber?: true
  comments?: true
  payerInfoId?: true
  victimInfoId?: true
  cardOfAccidentId?: true
  createdAt?: true
  updatedAt?: true
  accidentInfoId?: true
}

export type CaseCountAggregateInputType = {
  id?: true
  caseNumber?: true
  comments?: true
  payerInfoId?: true
  victimInfoId?: true
  cardOfAccidentId?: true
  createdAt?: true
  updatedAt?: true
  accidentInfoId?: true
  _all?: true
}

export type CaseAggregateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which Case to aggregate.
   */
  where?: Prisma.CaseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of Cases to fetch.
   */
  orderBy?: Prisma.CaseOrderByWithRelationInput | Prisma.CaseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.CaseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` Cases from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` Cases.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned Cases
   **/
  _count?: true | CaseCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
   **/
  _min?: CaseMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
   **/
  _max?: CaseMaxAggregateInputType
}

export type GetCaseAggregateType<T extends CaseAggregateArgs> = {
  [P in keyof T & keyof AggregateCase]: P extends "_count" | "count"
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCase[P]>
    : Prisma.GetScalarType<T[P], AggregateCase[P]>
}

export type CaseGroupByArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.CaseWhereInput
  orderBy?: Prisma.CaseOrderByWithAggregationInput | Prisma.CaseOrderByWithAggregationInput[]
  by: Prisma.CaseScalarFieldEnum[] | Prisma.CaseScalarFieldEnum
  having?: Prisma.CaseScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CaseCountAggregateInputType | true
  _min?: CaseMinAggregateInputType
  _max?: CaseMaxAggregateInputType
}

export type CaseGroupByOutputType = {
  id: string
  caseNumber: string
  comments: string | null
  payerInfoId: string
  victimInfoId: string
  cardOfAccidentId: string | null
  createdAt: Date
  updatedAt: Date
  accidentInfoId: string
  _count: CaseCountAggregateOutputType | null
  _min: CaseMinAggregateOutputType | null
  _max: CaseMaxAggregateOutputType | null
}

type GetCaseGroupByPayload<T extends CaseGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CaseGroupByOutputType, T["by"]> & {
      [P in keyof T & keyof CaseGroupByOutputType]: P extends "_count"
        ? T[P] extends boolean
          ? number
          : Prisma.GetScalarType<T[P], CaseGroupByOutputType[P]>
        : Prisma.GetScalarType<T[P], CaseGroupByOutputType[P]>
    }
  >
>

export type CaseWhereInput = {
  AND?: Prisma.CaseWhereInput | Prisma.CaseWhereInput[]
  OR?: Prisma.CaseWhereInput[]
  NOT?: Prisma.CaseWhereInput | Prisma.CaseWhereInput[]
  id?: Prisma.StringFilter<"Case"> | string
  caseNumber?: Prisma.StringFilter<"Case"> | string
  comments?: Prisma.StringNullableFilter<"Case"> | string | null
  payerInfoId?: Prisma.StringFilter<"Case"> | string
  victimInfoId?: Prisma.StringFilter<"Case"> | string
  cardOfAccidentId?: Prisma.StringNullableFilter<"Case"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Case"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Case"> | Date | string
  accidentInfoId?: Prisma.StringFilter<"Case"> | string
  payerInfo?: Prisma.XOR<Prisma.PayerInfoScalarRelationFilter, Prisma.PayerInfoWhereInput>
  victimInfo?: Prisma.XOR<Prisma.VictimInfoScalarRelationFilter, Prisma.VictimInfoWhereInput>
  accidentInfo?: Prisma.XOR<Prisma.AccidentInfoScalarRelationFilter, Prisma.AccidentInfoWhereInput>
  cardOfAccident?: Prisma.XOR<Prisma.FileNullableScalarRelationFilter, Prisma.FileWhereInput> | null
}

export type CaseOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  caseNumber?: Prisma.SortOrder
  comments?: Prisma.SortOrderInput | Prisma.SortOrder
  payerInfoId?: Prisma.SortOrder
  victimInfoId?: Prisma.SortOrder
  cardOfAccidentId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  accidentInfoId?: Prisma.SortOrder
  payerInfo?: Prisma.PayerInfoOrderByWithRelationInput
  victimInfo?: Prisma.VictimInfoOrderByWithRelationInput
  accidentInfo?: Prisma.AccidentInfoOrderByWithRelationInput
  cardOfAccident?: Prisma.FileOrderByWithRelationInput
}

export type CaseWhereUniqueInput = Prisma.AtLeast<
  {
    id?: string
    AND?: Prisma.CaseWhereInput | Prisma.CaseWhereInput[]
    OR?: Prisma.CaseWhereInput[]
    NOT?: Prisma.CaseWhereInput | Prisma.CaseWhereInput[]
    caseNumber?: Prisma.StringFilter<"Case"> | string
    comments?: Prisma.StringNullableFilter<"Case"> | string | null
    payerInfoId?: Prisma.StringFilter<"Case"> | string
    victimInfoId?: Prisma.StringFilter<"Case"> | string
    cardOfAccidentId?: Prisma.StringNullableFilter<"Case"> | string | null
    createdAt?: Prisma.DateTimeFilter<"Case"> | Date | string
    updatedAt?: Prisma.DateTimeFilter<"Case"> | Date | string
    accidentInfoId?: Prisma.StringFilter<"Case"> | string
    payerInfo?: Prisma.XOR<Prisma.PayerInfoScalarRelationFilter, Prisma.PayerInfoWhereInput>
    victimInfo?: Prisma.XOR<Prisma.VictimInfoScalarRelationFilter, Prisma.VictimInfoWhereInput>
    accidentInfo?: Prisma.XOR<
      Prisma.AccidentInfoScalarRelationFilter,
      Prisma.AccidentInfoWhereInput
    >
    cardOfAccident?: Prisma.XOR<
      Prisma.FileNullableScalarRelationFilter,
      Prisma.FileWhereInput
    > | null
  },
  "id"
>

export type CaseOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  caseNumber?: Prisma.SortOrder
  comments?: Prisma.SortOrderInput | Prisma.SortOrder
  payerInfoId?: Prisma.SortOrder
  victimInfoId?: Prisma.SortOrder
  cardOfAccidentId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  accidentInfoId?: Prisma.SortOrder
  _count?: Prisma.CaseCountOrderByAggregateInput
  _max?: Prisma.CaseMaxOrderByAggregateInput
  _min?: Prisma.CaseMinOrderByAggregateInput
}

export type CaseScalarWhereWithAggregatesInput = {
  AND?: Prisma.CaseScalarWhereWithAggregatesInput | Prisma.CaseScalarWhereWithAggregatesInput[]
  OR?: Prisma.CaseScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CaseScalarWhereWithAggregatesInput | Prisma.CaseScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Case"> | string
  caseNumber?: Prisma.StringWithAggregatesFilter<"Case"> | string
  comments?: Prisma.StringNullableWithAggregatesFilter<"Case"> | string | null
  payerInfoId?: Prisma.StringWithAggregatesFilter<"Case"> | string
  victimInfoId?: Prisma.StringWithAggregatesFilter<"Case"> | string
  cardOfAccidentId?: Prisma.StringNullableWithAggregatesFilter<"Case"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Case"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Case"> | Date | string
  accidentInfoId?: Prisma.StringWithAggregatesFilter<"Case"> | string
}

export type CaseCreateInput = {
  id?: string
  caseNumber: string
  comments?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  payerInfo: Prisma.PayerInfoCreateNestedOneWithoutCasesInput
  victimInfo: Prisma.VictimInfoCreateNestedOneWithoutCasesInput
  accidentInfo: Prisma.AccidentInfoCreateNestedOneWithoutCasesInput
  cardOfAccident?: Prisma.FileCreateNestedOneWithoutCasesInput
}

export type CaseUncheckedCreateInput = {
  id?: string
  caseNumber: string
  comments?: string | null
  payerInfoId: string
  victimInfoId: string
  cardOfAccidentId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  accidentInfoId: string
}

export type CaseUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  caseNumber?: Prisma.StringFieldUpdateOperationsInput | string
  comments?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  payerInfo?: Prisma.PayerInfoUpdateOneRequiredWithoutCasesNestedInput
  victimInfo?: Prisma.VictimInfoUpdateOneRequiredWithoutCasesNestedInput
  accidentInfo?: Prisma.AccidentInfoUpdateOneRequiredWithoutCasesNestedInput
  cardOfAccident?: Prisma.FileUpdateOneWithoutCasesNestedInput
}

export type CaseUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  caseNumber?: Prisma.StringFieldUpdateOperationsInput | string
  comments?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  payerInfoId?: Prisma.StringFieldUpdateOperationsInput | string
  victimInfoId?: Prisma.StringFieldUpdateOperationsInput | string
  cardOfAccidentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  accidentInfoId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CaseCreateManyInput = {
  id?: string
  caseNumber: string
  comments?: string | null
  payerInfoId: string
  victimInfoId: string
  cardOfAccidentId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  accidentInfoId: string
}

export type CaseUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  caseNumber?: Prisma.StringFieldUpdateOperationsInput | string
  comments?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CaseUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  caseNumber?: Prisma.StringFieldUpdateOperationsInput | string
  comments?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  payerInfoId?: Prisma.StringFieldUpdateOperationsInput | string
  victimInfoId?: Prisma.StringFieldUpdateOperationsInput | string
  cardOfAccidentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  accidentInfoId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CaseCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  caseNumber?: Prisma.SortOrder
  comments?: Prisma.SortOrder
  payerInfoId?: Prisma.SortOrder
  victimInfoId?: Prisma.SortOrder
  cardOfAccidentId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  accidentInfoId?: Prisma.SortOrder
}

export type CaseMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  caseNumber?: Prisma.SortOrder
  comments?: Prisma.SortOrder
  payerInfoId?: Prisma.SortOrder
  victimInfoId?: Prisma.SortOrder
  cardOfAccidentId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  accidentInfoId?: Prisma.SortOrder
}

export type CaseMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  caseNumber?: Prisma.SortOrder
  comments?: Prisma.SortOrder
  payerInfoId?: Prisma.SortOrder
  victimInfoId?: Prisma.SortOrder
  cardOfAccidentId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  accidentInfoId?: Prisma.SortOrder
}

export type CaseListRelationFilter = {
  every?: Prisma.CaseWhereInput
  some?: Prisma.CaseWhereInput
  none?: Prisma.CaseWhereInput
}

export type CaseOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type CaseCreateNestedManyWithoutPayerInfoInput = {
  create?:
    | Prisma.XOR<
        Prisma.CaseCreateWithoutPayerInfoInput,
        Prisma.CaseUncheckedCreateWithoutPayerInfoInput
      >
    | Prisma.CaseCreateWithoutPayerInfoInput[]
    | Prisma.CaseUncheckedCreateWithoutPayerInfoInput[]
  connectOrCreate?:
    | Prisma.CaseCreateOrConnectWithoutPayerInfoInput
    | Prisma.CaseCreateOrConnectWithoutPayerInfoInput[]
  createMany?: Prisma.CaseCreateManyPayerInfoInputEnvelope
  connect?: Prisma.CaseWhereUniqueInput | Prisma.CaseWhereUniqueInput[]
}

export type CaseUncheckedCreateNestedManyWithoutPayerInfoInput = {
  create?:
    | Prisma.XOR<
        Prisma.CaseCreateWithoutPayerInfoInput,
        Prisma.CaseUncheckedCreateWithoutPayerInfoInput
      >
    | Prisma.CaseCreateWithoutPayerInfoInput[]
    | Prisma.CaseUncheckedCreateWithoutPayerInfoInput[]
  connectOrCreate?:
    | Prisma.CaseCreateOrConnectWithoutPayerInfoInput
    | Prisma.CaseCreateOrConnectWithoutPayerInfoInput[]
  createMany?: Prisma.CaseCreateManyPayerInfoInputEnvelope
  connect?: Prisma.CaseWhereUniqueInput | Prisma.CaseWhereUniqueInput[]
}

export type CaseUpdateManyWithoutPayerInfoNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.CaseCreateWithoutPayerInfoInput,
        Prisma.CaseUncheckedCreateWithoutPayerInfoInput
      >
    | Prisma.CaseCreateWithoutPayerInfoInput[]
    | Prisma.CaseUncheckedCreateWithoutPayerInfoInput[]
  connectOrCreate?:
    | Prisma.CaseCreateOrConnectWithoutPayerInfoInput
    | Prisma.CaseCreateOrConnectWithoutPayerInfoInput[]
  upsert?:
    | Prisma.CaseUpsertWithWhereUniqueWithoutPayerInfoInput
    | Prisma.CaseUpsertWithWhereUniqueWithoutPayerInfoInput[]
  createMany?: Prisma.CaseCreateManyPayerInfoInputEnvelope
  set?: Prisma.CaseWhereUniqueInput | Prisma.CaseWhereUniqueInput[]
  disconnect?: Prisma.CaseWhereUniqueInput | Prisma.CaseWhereUniqueInput[]
  delete?: Prisma.CaseWhereUniqueInput | Prisma.CaseWhereUniqueInput[]
  connect?: Prisma.CaseWhereUniqueInput | Prisma.CaseWhereUniqueInput[]
  update?:
    | Prisma.CaseUpdateWithWhereUniqueWithoutPayerInfoInput
    | Prisma.CaseUpdateWithWhereUniqueWithoutPayerInfoInput[]
  updateMany?:
    | Prisma.CaseUpdateManyWithWhereWithoutPayerInfoInput
    | Prisma.CaseUpdateManyWithWhereWithoutPayerInfoInput[]
  deleteMany?: Prisma.CaseScalarWhereInput | Prisma.CaseScalarWhereInput[]
}

export type CaseUncheckedUpdateManyWithoutPayerInfoNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.CaseCreateWithoutPayerInfoInput,
        Prisma.CaseUncheckedCreateWithoutPayerInfoInput
      >
    | Prisma.CaseCreateWithoutPayerInfoInput[]
    | Prisma.CaseUncheckedCreateWithoutPayerInfoInput[]
  connectOrCreate?:
    | Prisma.CaseCreateOrConnectWithoutPayerInfoInput
    | Prisma.CaseCreateOrConnectWithoutPayerInfoInput[]
  upsert?:
    | Prisma.CaseUpsertWithWhereUniqueWithoutPayerInfoInput
    | Prisma.CaseUpsertWithWhereUniqueWithoutPayerInfoInput[]
  createMany?: Prisma.CaseCreateManyPayerInfoInputEnvelope
  set?: Prisma.CaseWhereUniqueInput | Prisma.CaseWhereUniqueInput[]
  disconnect?: Prisma.CaseWhereUniqueInput | Prisma.CaseWhereUniqueInput[]
  delete?: Prisma.CaseWhereUniqueInput | Prisma.CaseWhereUniqueInput[]
  connect?: Prisma.CaseWhereUniqueInput | Prisma.CaseWhereUniqueInput[]
  update?:
    | Prisma.CaseUpdateWithWhereUniqueWithoutPayerInfoInput
    | Prisma.CaseUpdateWithWhereUniqueWithoutPayerInfoInput[]
  updateMany?:
    | Prisma.CaseUpdateManyWithWhereWithoutPayerInfoInput
    | Prisma.CaseUpdateManyWithWhereWithoutPayerInfoInput[]
  deleteMany?: Prisma.CaseScalarWhereInput | Prisma.CaseScalarWhereInput[]
}

export type CaseCreateNestedManyWithoutVictimInfoInput = {
  create?:
    | Prisma.XOR<
        Prisma.CaseCreateWithoutVictimInfoInput,
        Prisma.CaseUncheckedCreateWithoutVictimInfoInput
      >
    | Prisma.CaseCreateWithoutVictimInfoInput[]
    | Prisma.CaseUncheckedCreateWithoutVictimInfoInput[]
  connectOrCreate?:
    | Prisma.CaseCreateOrConnectWithoutVictimInfoInput
    | Prisma.CaseCreateOrConnectWithoutVictimInfoInput[]
  createMany?: Prisma.CaseCreateManyVictimInfoInputEnvelope
  connect?: Prisma.CaseWhereUniqueInput | Prisma.CaseWhereUniqueInput[]
}

export type CaseUncheckedCreateNestedManyWithoutVictimInfoInput = {
  create?:
    | Prisma.XOR<
        Prisma.CaseCreateWithoutVictimInfoInput,
        Prisma.CaseUncheckedCreateWithoutVictimInfoInput
      >
    | Prisma.CaseCreateWithoutVictimInfoInput[]
    | Prisma.CaseUncheckedCreateWithoutVictimInfoInput[]
  connectOrCreate?:
    | Prisma.CaseCreateOrConnectWithoutVictimInfoInput
    | Prisma.CaseCreateOrConnectWithoutVictimInfoInput[]
  createMany?: Prisma.CaseCreateManyVictimInfoInputEnvelope
  connect?: Prisma.CaseWhereUniqueInput | Prisma.CaseWhereUniqueInput[]
}

export type CaseUpdateManyWithoutVictimInfoNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.CaseCreateWithoutVictimInfoInput,
        Prisma.CaseUncheckedCreateWithoutVictimInfoInput
      >
    | Prisma.CaseCreateWithoutVictimInfoInput[]
    | Prisma.CaseUncheckedCreateWithoutVictimInfoInput[]
  connectOrCreate?:
    | Prisma.CaseCreateOrConnectWithoutVictimInfoInput
    | Prisma.CaseCreateOrConnectWithoutVictimInfoInput[]
  upsert?:
    | Prisma.CaseUpsertWithWhereUniqueWithoutVictimInfoInput
    | Prisma.CaseUpsertWithWhereUniqueWithoutVictimInfoInput[]
  createMany?: Prisma.CaseCreateManyVictimInfoInputEnvelope
  set?: Prisma.CaseWhereUniqueInput | Prisma.CaseWhereUniqueInput[]
  disconnect?: Prisma.CaseWhereUniqueInput | Prisma.CaseWhereUniqueInput[]
  delete?: Prisma.CaseWhereUniqueInput | Prisma.CaseWhereUniqueInput[]
  connect?: Prisma.CaseWhereUniqueInput | Prisma.CaseWhereUniqueInput[]
  update?:
    | Prisma.CaseUpdateWithWhereUniqueWithoutVictimInfoInput
    | Prisma.CaseUpdateWithWhereUniqueWithoutVictimInfoInput[]
  updateMany?:
    | Prisma.CaseUpdateManyWithWhereWithoutVictimInfoInput
    | Prisma.CaseUpdateManyWithWhereWithoutVictimInfoInput[]
  deleteMany?: Prisma.CaseScalarWhereInput | Prisma.CaseScalarWhereInput[]
}

export type CaseUncheckedUpdateManyWithoutVictimInfoNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.CaseCreateWithoutVictimInfoInput,
        Prisma.CaseUncheckedCreateWithoutVictimInfoInput
      >
    | Prisma.CaseCreateWithoutVictimInfoInput[]
    | Prisma.CaseUncheckedCreateWithoutVictimInfoInput[]
  connectOrCreate?:
    | Prisma.CaseCreateOrConnectWithoutVictimInfoInput
    | Prisma.CaseCreateOrConnectWithoutVictimInfoInput[]
  upsert?:
    | Prisma.CaseUpsertWithWhereUniqueWithoutVictimInfoInput
    | Prisma.CaseUpsertWithWhereUniqueWithoutVictimInfoInput[]
  createMany?: Prisma.CaseCreateManyVictimInfoInputEnvelope
  set?: Prisma.CaseWhereUniqueInput | Prisma.CaseWhereUniqueInput[]
  disconnect?: Prisma.CaseWhereUniqueInput | Prisma.CaseWhereUniqueInput[]
  delete?: Prisma.CaseWhereUniqueInput | Prisma.CaseWhereUniqueInput[]
  connect?: Prisma.CaseWhereUniqueInput | Prisma.CaseWhereUniqueInput[]
  update?:
    | Prisma.CaseUpdateWithWhereUniqueWithoutVictimInfoInput
    | Prisma.CaseUpdateWithWhereUniqueWithoutVictimInfoInput[]
  updateMany?:
    | Prisma.CaseUpdateManyWithWhereWithoutVictimInfoInput
    | Prisma.CaseUpdateManyWithWhereWithoutVictimInfoInput[]
  deleteMany?: Prisma.CaseScalarWhereInput | Prisma.CaseScalarWhereInput[]
}

export type CaseCreateNestedManyWithoutAccidentInfoInput = {
  create?:
    | Prisma.XOR<
        Prisma.CaseCreateWithoutAccidentInfoInput,
        Prisma.CaseUncheckedCreateWithoutAccidentInfoInput
      >
    | Prisma.CaseCreateWithoutAccidentInfoInput[]
    | Prisma.CaseUncheckedCreateWithoutAccidentInfoInput[]
  connectOrCreate?:
    | Prisma.CaseCreateOrConnectWithoutAccidentInfoInput
    | Prisma.CaseCreateOrConnectWithoutAccidentInfoInput[]
  createMany?: Prisma.CaseCreateManyAccidentInfoInputEnvelope
  connect?: Prisma.CaseWhereUniqueInput | Prisma.CaseWhereUniqueInput[]
}

export type CaseUncheckedCreateNestedManyWithoutAccidentInfoInput = {
  create?:
    | Prisma.XOR<
        Prisma.CaseCreateWithoutAccidentInfoInput,
        Prisma.CaseUncheckedCreateWithoutAccidentInfoInput
      >
    | Prisma.CaseCreateWithoutAccidentInfoInput[]
    | Prisma.CaseUncheckedCreateWithoutAccidentInfoInput[]
  connectOrCreate?:
    | Prisma.CaseCreateOrConnectWithoutAccidentInfoInput
    | Prisma.CaseCreateOrConnectWithoutAccidentInfoInput[]
  createMany?: Prisma.CaseCreateManyAccidentInfoInputEnvelope
  connect?: Prisma.CaseWhereUniqueInput | Prisma.CaseWhereUniqueInput[]
}

export type CaseUpdateManyWithoutAccidentInfoNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.CaseCreateWithoutAccidentInfoInput,
        Prisma.CaseUncheckedCreateWithoutAccidentInfoInput
      >
    | Prisma.CaseCreateWithoutAccidentInfoInput[]
    | Prisma.CaseUncheckedCreateWithoutAccidentInfoInput[]
  connectOrCreate?:
    | Prisma.CaseCreateOrConnectWithoutAccidentInfoInput
    | Prisma.CaseCreateOrConnectWithoutAccidentInfoInput[]
  upsert?:
    | Prisma.CaseUpsertWithWhereUniqueWithoutAccidentInfoInput
    | Prisma.CaseUpsertWithWhereUniqueWithoutAccidentInfoInput[]
  createMany?: Prisma.CaseCreateManyAccidentInfoInputEnvelope
  set?: Prisma.CaseWhereUniqueInput | Prisma.CaseWhereUniqueInput[]
  disconnect?: Prisma.CaseWhereUniqueInput | Prisma.CaseWhereUniqueInput[]
  delete?: Prisma.CaseWhereUniqueInput | Prisma.CaseWhereUniqueInput[]
  connect?: Prisma.CaseWhereUniqueInput | Prisma.CaseWhereUniqueInput[]
  update?:
    | Prisma.CaseUpdateWithWhereUniqueWithoutAccidentInfoInput
    | Prisma.CaseUpdateWithWhereUniqueWithoutAccidentInfoInput[]
  updateMany?:
    | Prisma.CaseUpdateManyWithWhereWithoutAccidentInfoInput
    | Prisma.CaseUpdateManyWithWhereWithoutAccidentInfoInput[]
  deleteMany?: Prisma.CaseScalarWhereInput | Prisma.CaseScalarWhereInput[]
}

export type CaseUncheckedUpdateManyWithoutAccidentInfoNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.CaseCreateWithoutAccidentInfoInput,
        Prisma.CaseUncheckedCreateWithoutAccidentInfoInput
      >
    | Prisma.CaseCreateWithoutAccidentInfoInput[]
    | Prisma.CaseUncheckedCreateWithoutAccidentInfoInput[]
  connectOrCreate?:
    | Prisma.CaseCreateOrConnectWithoutAccidentInfoInput
    | Prisma.CaseCreateOrConnectWithoutAccidentInfoInput[]
  upsert?:
    | Prisma.CaseUpsertWithWhereUniqueWithoutAccidentInfoInput
    | Prisma.CaseUpsertWithWhereUniqueWithoutAccidentInfoInput[]
  createMany?: Prisma.CaseCreateManyAccidentInfoInputEnvelope
  set?: Prisma.CaseWhereUniqueInput | Prisma.CaseWhereUniqueInput[]
  disconnect?: Prisma.CaseWhereUniqueInput | Prisma.CaseWhereUniqueInput[]
  delete?: Prisma.CaseWhereUniqueInput | Prisma.CaseWhereUniqueInput[]
  connect?: Prisma.CaseWhereUniqueInput | Prisma.CaseWhereUniqueInput[]
  update?:
    | Prisma.CaseUpdateWithWhereUniqueWithoutAccidentInfoInput
    | Prisma.CaseUpdateWithWhereUniqueWithoutAccidentInfoInput[]
  updateMany?:
    | Prisma.CaseUpdateManyWithWhereWithoutAccidentInfoInput
    | Prisma.CaseUpdateManyWithWhereWithoutAccidentInfoInput[]
  deleteMany?: Prisma.CaseScalarWhereInput | Prisma.CaseScalarWhereInput[]
}

export type CaseCreateNestedManyWithoutCardOfAccidentInput = {
  create?:
    | Prisma.XOR<
        Prisma.CaseCreateWithoutCardOfAccidentInput,
        Prisma.CaseUncheckedCreateWithoutCardOfAccidentInput
      >
    | Prisma.CaseCreateWithoutCardOfAccidentInput[]
    | Prisma.CaseUncheckedCreateWithoutCardOfAccidentInput[]
  connectOrCreate?:
    | Prisma.CaseCreateOrConnectWithoutCardOfAccidentInput
    | Prisma.CaseCreateOrConnectWithoutCardOfAccidentInput[]
  createMany?: Prisma.CaseCreateManyCardOfAccidentInputEnvelope
  connect?: Prisma.CaseWhereUniqueInput | Prisma.CaseWhereUniqueInput[]
}

export type CaseUncheckedCreateNestedManyWithoutCardOfAccidentInput = {
  create?:
    | Prisma.XOR<
        Prisma.CaseCreateWithoutCardOfAccidentInput,
        Prisma.CaseUncheckedCreateWithoutCardOfAccidentInput
      >
    | Prisma.CaseCreateWithoutCardOfAccidentInput[]
    | Prisma.CaseUncheckedCreateWithoutCardOfAccidentInput[]
  connectOrCreate?:
    | Prisma.CaseCreateOrConnectWithoutCardOfAccidentInput
    | Prisma.CaseCreateOrConnectWithoutCardOfAccidentInput[]
  createMany?: Prisma.CaseCreateManyCardOfAccidentInputEnvelope
  connect?: Prisma.CaseWhereUniqueInput | Prisma.CaseWhereUniqueInput[]
}

export type CaseUpdateManyWithoutCardOfAccidentNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.CaseCreateWithoutCardOfAccidentInput,
        Prisma.CaseUncheckedCreateWithoutCardOfAccidentInput
      >
    | Prisma.CaseCreateWithoutCardOfAccidentInput[]
    | Prisma.CaseUncheckedCreateWithoutCardOfAccidentInput[]
  connectOrCreate?:
    | Prisma.CaseCreateOrConnectWithoutCardOfAccidentInput
    | Prisma.CaseCreateOrConnectWithoutCardOfAccidentInput[]
  upsert?:
    | Prisma.CaseUpsertWithWhereUniqueWithoutCardOfAccidentInput
    | Prisma.CaseUpsertWithWhereUniqueWithoutCardOfAccidentInput[]
  createMany?: Prisma.CaseCreateManyCardOfAccidentInputEnvelope
  set?: Prisma.CaseWhereUniqueInput | Prisma.CaseWhereUniqueInput[]
  disconnect?: Prisma.CaseWhereUniqueInput | Prisma.CaseWhereUniqueInput[]
  delete?: Prisma.CaseWhereUniqueInput | Prisma.CaseWhereUniqueInput[]
  connect?: Prisma.CaseWhereUniqueInput | Prisma.CaseWhereUniqueInput[]
  update?:
    | Prisma.CaseUpdateWithWhereUniqueWithoutCardOfAccidentInput
    | Prisma.CaseUpdateWithWhereUniqueWithoutCardOfAccidentInput[]
  updateMany?:
    | Prisma.CaseUpdateManyWithWhereWithoutCardOfAccidentInput
    | Prisma.CaseUpdateManyWithWhereWithoutCardOfAccidentInput[]
  deleteMany?: Prisma.CaseScalarWhereInput | Prisma.CaseScalarWhereInput[]
}

export type CaseUncheckedUpdateManyWithoutCardOfAccidentNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.CaseCreateWithoutCardOfAccidentInput,
        Prisma.CaseUncheckedCreateWithoutCardOfAccidentInput
      >
    | Prisma.CaseCreateWithoutCardOfAccidentInput[]
    | Prisma.CaseUncheckedCreateWithoutCardOfAccidentInput[]
  connectOrCreate?:
    | Prisma.CaseCreateOrConnectWithoutCardOfAccidentInput
    | Prisma.CaseCreateOrConnectWithoutCardOfAccidentInput[]
  upsert?:
    | Prisma.CaseUpsertWithWhereUniqueWithoutCardOfAccidentInput
    | Prisma.CaseUpsertWithWhereUniqueWithoutCardOfAccidentInput[]
  createMany?: Prisma.CaseCreateManyCardOfAccidentInputEnvelope
  set?: Prisma.CaseWhereUniqueInput | Prisma.CaseWhereUniqueInput[]
  disconnect?: Prisma.CaseWhereUniqueInput | Prisma.CaseWhereUniqueInput[]
  delete?: Prisma.CaseWhereUniqueInput | Prisma.CaseWhereUniqueInput[]
  connect?: Prisma.CaseWhereUniqueInput | Prisma.CaseWhereUniqueInput[]
  update?:
    | Prisma.CaseUpdateWithWhereUniqueWithoutCardOfAccidentInput
    | Prisma.CaseUpdateWithWhereUniqueWithoutCardOfAccidentInput[]
  updateMany?:
    | Prisma.CaseUpdateManyWithWhereWithoutCardOfAccidentInput
    | Prisma.CaseUpdateManyWithWhereWithoutCardOfAccidentInput[]
  deleteMany?: Prisma.CaseScalarWhereInput | Prisma.CaseScalarWhereInput[]
}

export type CaseCreateWithoutPayerInfoInput = {
  id?: string
  caseNumber: string
  comments?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  victimInfo: Prisma.VictimInfoCreateNestedOneWithoutCasesInput
  accidentInfo: Prisma.AccidentInfoCreateNestedOneWithoutCasesInput
  cardOfAccident?: Prisma.FileCreateNestedOneWithoutCasesInput
}

export type CaseUncheckedCreateWithoutPayerInfoInput = {
  id?: string
  caseNumber: string
  comments?: string | null
  victimInfoId: string
  cardOfAccidentId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  accidentInfoId: string
}

export type CaseCreateOrConnectWithoutPayerInfoInput = {
  where: Prisma.CaseWhereUniqueInput
  create: Prisma.XOR<
    Prisma.CaseCreateWithoutPayerInfoInput,
    Prisma.CaseUncheckedCreateWithoutPayerInfoInput
  >
}

export type CaseCreateManyPayerInfoInputEnvelope = {
  data: Prisma.CaseCreateManyPayerInfoInput | Prisma.CaseCreateManyPayerInfoInput[]
  skipDuplicates?: boolean
}

export type CaseUpsertWithWhereUniqueWithoutPayerInfoInput = {
  where: Prisma.CaseWhereUniqueInput
  update: Prisma.XOR<
    Prisma.CaseUpdateWithoutPayerInfoInput,
    Prisma.CaseUncheckedUpdateWithoutPayerInfoInput
  >
  create: Prisma.XOR<
    Prisma.CaseCreateWithoutPayerInfoInput,
    Prisma.CaseUncheckedCreateWithoutPayerInfoInput
  >
}

export type CaseUpdateWithWhereUniqueWithoutPayerInfoInput = {
  where: Prisma.CaseWhereUniqueInput
  data: Prisma.XOR<
    Prisma.CaseUpdateWithoutPayerInfoInput,
    Prisma.CaseUncheckedUpdateWithoutPayerInfoInput
  >
}

export type CaseUpdateManyWithWhereWithoutPayerInfoInput = {
  where: Prisma.CaseScalarWhereInput
  data: Prisma.XOR<
    Prisma.CaseUpdateManyMutationInput,
    Prisma.CaseUncheckedUpdateManyWithoutPayerInfoInput
  >
}

export type CaseScalarWhereInput = {
  AND?: Prisma.CaseScalarWhereInput | Prisma.CaseScalarWhereInput[]
  OR?: Prisma.CaseScalarWhereInput[]
  NOT?: Prisma.CaseScalarWhereInput | Prisma.CaseScalarWhereInput[]
  id?: Prisma.StringFilter<"Case"> | string
  caseNumber?: Prisma.StringFilter<"Case"> | string
  comments?: Prisma.StringNullableFilter<"Case"> | string | null
  payerInfoId?: Prisma.StringFilter<"Case"> | string
  victimInfoId?: Prisma.StringFilter<"Case"> | string
  cardOfAccidentId?: Prisma.StringNullableFilter<"Case"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Case"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Case"> | Date | string
  accidentInfoId?: Prisma.StringFilter<"Case"> | string
}

export type CaseCreateWithoutVictimInfoInput = {
  id?: string
  caseNumber: string
  comments?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  payerInfo: Prisma.PayerInfoCreateNestedOneWithoutCasesInput
  accidentInfo: Prisma.AccidentInfoCreateNestedOneWithoutCasesInput
  cardOfAccident?: Prisma.FileCreateNestedOneWithoutCasesInput
}

export type CaseUncheckedCreateWithoutVictimInfoInput = {
  id?: string
  caseNumber: string
  comments?: string | null
  payerInfoId: string
  cardOfAccidentId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  accidentInfoId: string
}

export type CaseCreateOrConnectWithoutVictimInfoInput = {
  where: Prisma.CaseWhereUniqueInput
  create: Prisma.XOR<
    Prisma.CaseCreateWithoutVictimInfoInput,
    Prisma.CaseUncheckedCreateWithoutVictimInfoInput
  >
}

export type CaseCreateManyVictimInfoInputEnvelope = {
  data: Prisma.CaseCreateManyVictimInfoInput | Prisma.CaseCreateManyVictimInfoInput[]
  skipDuplicates?: boolean
}

export type CaseUpsertWithWhereUniqueWithoutVictimInfoInput = {
  where: Prisma.CaseWhereUniqueInput
  update: Prisma.XOR<
    Prisma.CaseUpdateWithoutVictimInfoInput,
    Prisma.CaseUncheckedUpdateWithoutVictimInfoInput
  >
  create: Prisma.XOR<
    Prisma.CaseCreateWithoutVictimInfoInput,
    Prisma.CaseUncheckedCreateWithoutVictimInfoInput
  >
}

export type CaseUpdateWithWhereUniqueWithoutVictimInfoInput = {
  where: Prisma.CaseWhereUniqueInput
  data: Prisma.XOR<
    Prisma.CaseUpdateWithoutVictimInfoInput,
    Prisma.CaseUncheckedUpdateWithoutVictimInfoInput
  >
}

export type CaseUpdateManyWithWhereWithoutVictimInfoInput = {
  where: Prisma.CaseScalarWhereInput
  data: Prisma.XOR<
    Prisma.CaseUpdateManyMutationInput,
    Prisma.CaseUncheckedUpdateManyWithoutVictimInfoInput
  >
}

export type CaseCreateWithoutAccidentInfoInput = {
  id?: string
  caseNumber: string
  comments?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  payerInfo: Prisma.PayerInfoCreateNestedOneWithoutCasesInput
  victimInfo: Prisma.VictimInfoCreateNestedOneWithoutCasesInput
  cardOfAccident?: Prisma.FileCreateNestedOneWithoutCasesInput
}

export type CaseUncheckedCreateWithoutAccidentInfoInput = {
  id?: string
  caseNumber: string
  comments?: string | null
  payerInfoId: string
  victimInfoId: string
  cardOfAccidentId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CaseCreateOrConnectWithoutAccidentInfoInput = {
  where: Prisma.CaseWhereUniqueInput
  create: Prisma.XOR<
    Prisma.CaseCreateWithoutAccidentInfoInput,
    Prisma.CaseUncheckedCreateWithoutAccidentInfoInput
  >
}

export type CaseCreateManyAccidentInfoInputEnvelope = {
  data: Prisma.CaseCreateManyAccidentInfoInput | Prisma.CaseCreateManyAccidentInfoInput[]
  skipDuplicates?: boolean
}

export type CaseUpsertWithWhereUniqueWithoutAccidentInfoInput = {
  where: Prisma.CaseWhereUniqueInput
  update: Prisma.XOR<
    Prisma.CaseUpdateWithoutAccidentInfoInput,
    Prisma.CaseUncheckedUpdateWithoutAccidentInfoInput
  >
  create: Prisma.XOR<
    Prisma.CaseCreateWithoutAccidentInfoInput,
    Prisma.CaseUncheckedCreateWithoutAccidentInfoInput
  >
}

export type CaseUpdateWithWhereUniqueWithoutAccidentInfoInput = {
  where: Prisma.CaseWhereUniqueInput
  data: Prisma.XOR<
    Prisma.CaseUpdateWithoutAccidentInfoInput,
    Prisma.CaseUncheckedUpdateWithoutAccidentInfoInput
  >
}

export type CaseUpdateManyWithWhereWithoutAccidentInfoInput = {
  where: Prisma.CaseScalarWhereInput
  data: Prisma.XOR<
    Prisma.CaseUpdateManyMutationInput,
    Prisma.CaseUncheckedUpdateManyWithoutAccidentInfoInput
  >
}

export type CaseCreateWithoutCardOfAccidentInput = {
  id?: string
  caseNumber: string
  comments?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  payerInfo: Prisma.PayerInfoCreateNestedOneWithoutCasesInput
  victimInfo: Prisma.VictimInfoCreateNestedOneWithoutCasesInput
  accidentInfo: Prisma.AccidentInfoCreateNestedOneWithoutCasesInput
}

export type CaseUncheckedCreateWithoutCardOfAccidentInput = {
  id?: string
  caseNumber: string
  comments?: string | null
  payerInfoId: string
  victimInfoId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  accidentInfoId: string
}

export type CaseCreateOrConnectWithoutCardOfAccidentInput = {
  where: Prisma.CaseWhereUniqueInput
  create: Prisma.XOR<
    Prisma.CaseCreateWithoutCardOfAccidentInput,
    Prisma.CaseUncheckedCreateWithoutCardOfAccidentInput
  >
}

export type CaseCreateManyCardOfAccidentInputEnvelope = {
  data: Prisma.CaseCreateManyCardOfAccidentInput | Prisma.CaseCreateManyCardOfAccidentInput[]
  skipDuplicates?: boolean
}

export type CaseUpsertWithWhereUniqueWithoutCardOfAccidentInput = {
  where: Prisma.CaseWhereUniqueInput
  update: Prisma.XOR<
    Prisma.CaseUpdateWithoutCardOfAccidentInput,
    Prisma.CaseUncheckedUpdateWithoutCardOfAccidentInput
  >
  create: Prisma.XOR<
    Prisma.CaseCreateWithoutCardOfAccidentInput,
    Prisma.CaseUncheckedCreateWithoutCardOfAccidentInput
  >
}

export type CaseUpdateWithWhereUniqueWithoutCardOfAccidentInput = {
  where: Prisma.CaseWhereUniqueInput
  data: Prisma.XOR<
    Prisma.CaseUpdateWithoutCardOfAccidentInput,
    Prisma.CaseUncheckedUpdateWithoutCardOfAccidentInput
  >
}

export type CaseUpdateManyWithWhereWithoutCardOfAccidentInput = {
  where: Prisma.CaseScalarWhereInput
  data: Prisma.XOR<
    Prisma.CaseUpdateManyMutationInput,
    Prisma.CaseUncheckedUpdateManyWithoutCardOfAccidentInput
  >
}

export type CaseCreateManyPayerInfoInput = {
  id?: string
  caseNumber: string
  comments?: string | null
  victimInfoId: string
  cardOfAccidentId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  accidentInfoId: string
}

export type CaseUpdateWithoutPayerInfoInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  caseNumber?: Prisma.StringFieldUpdateOperationsInput | string
  comments?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  victimInfo?: Prisma.VictimInfoUpdateOneRequiredWithoutCasesNestedInput
  accidentInfo?: Prisma.AccidentInfoUpdateOneRequiredWithoutCasesNestedInput
  cardOfAccident?: Prisma.FileUpdateOneWithoutCasesNestedInput
}

export type CaseUncheckedUpdateWithoutPayerInfoInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  caseNumber?: Prisma.StringFieldUpdateOperationsInput | string
  comments?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  victimInfoId?: Prisma.StringFieldUpdateOperationsInput | string
  cardOfAccidentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  accidentInfoId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CaseUncheckedUpdateManyWithoutPayerInfoInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  caseNumber?: Prisma.StringFieldUpdateOperationsInput | string
  comments?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  victimInfoId?: Prisma.StringFieldUpdateOperationsInput | string
  cardOfAccidentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  accidentInfoId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CaseCreateManyVictimInfoInput = {
  id?: string
  caseNumber: string
  comments?: string | null
  payerInfoId: string
  cardOfAccidentId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  accidentInfoId: string
}

export type CaseUpdateWithoutVictimInfoInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  caseNumber?: Prisma.StringFieldUpdateOperationsInput | string
  comments?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  payerInfo?: Prisma.PayerInfoUpdateOneRequiredWithoutCasesNestedInput
  accidentInfo?: Prisma.AccidentInfoUpdateOneRequiredWithoutCasesNestedInput
  cardOfAccident?: Prisma.FileUpdateOneWithoutCasesNestedInput
}

export type CaseUncheckedUpdateWithoutVictimInfoInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  caseNumber?: Prisma.StringFieldUpdateOperationsInput | string
  comments?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  payerInfoId?: Prisma.StringFieldUpdateOperationsInput | string
  cardOfAccidentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  accidentInfoId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CaseUncheckedUpdateManyWithoutVictimInfoInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  caseNumber?: Prisma.StringFieldUpdateOperationsInput | string
  comments?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  payerInfoId?: Prisma.StringFieldUpdateOperationsInput | string
  cardOfAccidentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  accidentInfoId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CaseCreateManyAccidentInfoInput = {
  id?: string
  caseNumber: string
  comments?: string | null
  payerInfoId: string
  victimInfoId: string
  cardOfAccidentId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CaseUpdateWithoutAccidentInfoInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  caseNumber?: Prisma.StringFieldUpdateOperationsInput | string
  comments?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  payerInfo?: Prisma.PayerInfoUpdateOneRequiredWithoutCasesNestedInput
  victimInfo?: Prisma.VictimInfoUpdateOneRequiredWithoutCasesNestedInput
  cardOfAccident?: Prisma.FileUpdateOneWithoutCasesNestedInput
}

export type CaseUncheckedUpdateWithoutAccidentInfoInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  caseNumber?: Prisma.StringFieldUpdateOperationsInput | string
  comments?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  payerInfoId?: Prisma.StringFieldUpdateOperationsInput | string
  victimInfoId?: Prisma.StringFieldUpdateOperationsInput | string
  cardOfAccidentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CaseUncheckedUpdateManyWithoutAccidentInfoInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  caseNumber?: Prisma.StringFieldUpdateOperationsInput | string
  comments?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  payerInfoId?: Prisma.StringFieldUpdateOperationsInput | string
  victimInfoId?: Prisma.StringFieldUpdateOperationsInput | string
  cardOfAccidentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CaseCreateManyCardOfAccidentInput = {
  id?: string
  caseNumber: string
  comments?: string | null
  payerInfoId: string
  victimInfoId: string
  createdAt?: Date | string
  updatedAt?: Date | string
  accidentInfoId: string
}

export type CaseUpdateWithoutCardOfAccidentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  caseNumber?: Prisma.StringFieldUpdateOperationsInput | string
  comments?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  payerInfo?: Prisma.PayerInfoUpdateOneRequiredWithoutCasesNestedInput
  victimInfo?: Prisma.VictimInfoUpdateOneRequiredWithoutCasesNestedInput
  accidentInfo?: Prisma.AccidentInfoUpdateOneRequiredWithoutCasesNestedInput
}

export type CaseUncheckedUpdateWithoutCardOfAccidentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  caseNumber?: Prisma.StringFieldUpdateOperationsInput | string
  comments?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  payerInfoId?: Prisma.StringFieldUpdateOperationsInput | string
  victimInfoId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  accidentInfoId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CaseUncheckedUpdateManyWithoutCardOfAccidentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  caseNumber?: Prisma.StringFieldUpdateOperationsInput | string
  comments?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  payerInfoId?: Prisma.StringFieldUpdateOperationsInput | string
  victimInfoId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  accidentInfoId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type CaseSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean
    caseNumber?: boolean
    comments?: boolean
    payerInfoId?: boolean
    victimInfoId?: boolean
    cardOfAccidentId?: boolean
    createdAt?: boolean
    updatedAt?: boolean
    accidentInfoId?: boolean
    payerInfo?: boolean | Prisma.PayerInfoDefaultArgs<ExtArgs>
    victimInfo?: boolean | Prisma.VictimInfoDefaultArgs<ExtArgs>
    accidentInfo?: boolean | Prisma.AccidentInfoDefaultArgs<ExtArgs>
    cardOfAccident?: boolean | Prisma.Case$cardOfAccidentArgs<ExtArgs>
  },
  ExtArgs["result"]["case"]
>

export type CaseSelectCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean
    caseNumber?: boolean
    comments?: boolean
    payerInfoId?: boolean
    victimInfoId?: boolean
    cardOfAccidentId?: boolean
    createdAt?: boolean
    updatedAt?: boolean
    accidentInfoId?: boolean
    payerInfo?: boolean | Prisma.PayerInfoDefaultArgs<ExtArgs>
    victimInfo?: boolean | Prisma.VictimInfoDefaultArgs<ExtArgs>
    accidentInfo?: boolean | Prisma.AccidentInfoDefaultArgs<ExtArgs>
    cardOfAccident?: boolean | Prisma.Case$cardOfAccidentArgs<ExtArgs>
  },
  ExtArgs["result"]["case"]
>

export type CaseSelectUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean
    caseNumber?: boolean
    comments?: boolean
    payerInfoId?: boolean
    victimInfoId?: boolean
    cardOfAccidentId?: boolean
    createdAt?: boolean
    updatedAt?: boolean
    accidentInfoId?: boolean
    payerInfo?: boolean | Prisma.PayerInfoDefaultArgs<ExtArgs>
    victimInfo?: boolean | Prisma.VictimInfoDefaultArgs<ExtArgs>
    accidentInfo?: boolean | Prisma.AccidentInfoDefaultArgs<ExtArgs>
    cardOfAccident?: boolean | Prisma.Case$cardOfAccidentArgs<ExtArgs>
  },
  ExtArgs["result"]["case"]
>

export type CaseSelectScalar = {
  id?: boolean
  caseNumber?: boolean
  comments?: boolean
  payerInfoId?: boolean
  victimInfoId?: boolean
  cardOfAccidentId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  accidentInfoId?: boolean
}

export type CaseOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  | "id"
  | "caseNumber"
  | "comments"
  | "payerInfoId"
  | "victimInfoId"
  | "cardOfAccidentId"
  | "createdAt"
  | "updatedAt"
  | "accidentInfoId",
  ExtArgs["result"]["case"]
>
export type CaseInclude<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  payerInfo?: boolean | Prisma.PayerInfoDefaultArgs<ExtArgs>
  victimInfo?: boolean | Prisma.VictimInfoDefaultArgs<ExtArgs>
  accidentInfo?: boolean | Prisma.AccidentInfoDefaultArgs<ExtArgs>
  cardOfAccident?: boolean | Prisma.Case$cardOfAccidentArgs<ExtArgs>
}
export type CaseIncludeCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  payerInfo?: boolean | Prisma.PayerInfoDefaultArgs<ExtArgs>
  victimInfo?: boolean | Prisma.VictimInfoDefaultArgs<ExtArgs>
  accidentInfo?: boolean | Prisma.AccidentInfoDefaultArgs<ExtArgs>
  cardOfAccident?: boolean | Prisma.Case$cardOfAccidentArgs<ExtArgs>
}
export type CaseIncludeUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  payerInfo?: boolean | Prisma.PayerInfoDefaultArgs<ExtArgs>
  victimInfo?: boolean | Prisma.VictimInfoDefaultArgs<ExtArgs>
  accidentInfo?: boolean | Prisma.AccidentInfoDefaultArgs<ExtArgs>
  cardOfAccident?: boolean | Prisma.Case$cardOfAccidentArgs<ExtArgs>
}

export type $CasePayload<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  name: "Case"
  objects: {
    payerInfo: Prisma.$PayerInfoPayload<ExtArgs>
    victimInfo: Prisma.$VictimInfoPayload<ExtArgs>
    accidentInfo: Prisma.$AccidentInfoPayload<ExtArgs>
    cardOfAccident: Prisma.$FilePayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<
    {
      id: string
      caseNumber: string
      comments: string | null
      payerInfoId: string
      victimInfoId: string
      cardOfAccidentId: string | null
      createdAt: Date
      updatedAt: Date
      accidentInfoId: string
    },
    ExtArgs["result"]["case"]
  >
  composites: {}
}

export type CaseGetPayload<S extends boolean | null | undefined | CaseDefaultArgs> =
  runtime.Types.Result.GetResult<Prisma.$CasePayload, S>

export type CaseCountArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = Omit<CaseFindManyArgs, "select" | "include" | "distinct" | "omit"> & {
  select?: CaseCountAggregateInputType | true
}

export interface CaseDelegate<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>["model"]["Case"]; meta: { name: "Case" } }
  /**
   * Find zero or one Case that matches the filter.
   * @param {CaseFindUniqueArgs} args - Arguments to find a Case
   * @example
   * // Get one Case
   * const case = await prisma.case.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CaseFindUniqueArgs>(
    args: Prisma.SelectSubset<T, CaseFindUniqueArgs<ExtArgs>>,
  ): Prisma.Prisma__CaseClient<
    runtime.Types.Result.GetResult<
      Prisma.$CasePayload<ExtArgs>,
      T,
      "findUnique",
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find one Case that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CaseFindUniqueOrThrowArgs} args - Arguments to find a Case
   * @example
   * // Get one Case
   * const case = await prisma.case.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CaseFindUniqueOrThrowArgs>(
    args: Prisma.SelectSubset<T, CaseFindUniqueOrThrowArgs<ExtArgs>>,
  ): Prisma.Prisma__CaseClient<
    runtime.Types.Result.GetResult<
      Prisma.$CasePayload<ExtArgs>,
      T,
      "findUniqueOrThrow",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find the first Case that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CaseFindFirstArgs} args - Arguments to find a Case
   * @example
   * // Get one Case
   * const case = await prisma.case.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CaseFindFirstArgs>(
    args?: Prisma.SelectSubset<T, CaseFindFirstArgs<ExtArgs>>,
  ): Prisma.Prisma__CaseClient<
    runtime.Types.Result.GetResult<
      Prisma.$CasePayload<ExtArgs>,
      T,
      "findFirst",
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find the first Case that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CaseFindFirstOrThrowArgs} args - Arguments to find a Case
   * @example
   * // Get one Case
   * const case = await prisma.case.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CaseFindFirstOrThrowArgs>(
    args?: Prisma.SelectSubset<T, CaseFindFirstOrThrowArgs<ExtArgs>>,
  ): Prisma.Prisma__CaseClient<
    runtime.Types.Result.GetResult<
      Prisma.$CasePayload<ExtArgs>,
      T,
      "findFirstOrThrow",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find zero or more Cases that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CaseFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Cases
   * const cases = await prisma.case.findMany()
   *
   * // Get first 10 Cases
   * const cases = await prisma.case.findMany({ take: 10 })
   *
   * // Only select the `id`
   * const caseWithIdOnly = await prisma.case.findMany({ select: { id: true } })
   *
   */
  findMany<T extends CaseFindManyArgs>(
    args?: Prisma.SelectSubset<T, CaseFindManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<Prisma.$CasePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>
  >

  /**
   * Create a Case.
   * @param {CaseCreateArgs} args - Arguments to create a Case.
   * @example
   * // Create one Case
   * const Case = await prisma.case.create({
   *   data: {
   *     // ... data to create a Case
   *   }
   * })
   *
   */
  create<T extends CaseCreateArgs>(
    args: Prisma.SelectSubset<T, CaseCreateArgs<ExtArgs>>,
  ): Prisma.Prisma__CaseClient<
    runtime.Types.Result.GetResult<Prisma.$CasePayload<ExtArgs>, T, "create", GlobalOmitOptions>,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Create many Cases.
   * @param {CaseCreateManyArgs} args - Arguments to create many Cases.
   * @example
   * // Create many Cases
   * const case = await prisma.case.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends CaseCreateManyArgs>(
    args?: Prisma.SelectSubset<T, CaseCreateManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Cases and returns the data saved in the database.
   * @param {CaseCreateManyAndReturnArgs} args - Arguments to create many Cases.
   * @example
   * // Create many Cases
   * const case = await prisma.case.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Create many Cases and only return the `id`
   * const caseWithIdOnly = await prisma.case.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  createManyAndReturn<T extends CaseCreateManyAndReturnArgs>(
    args?: Prisma.SelectSubset<T, CaseCreateManyAndReturnArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$CasePayload<ExtArgs>,
      T,
      "createManyAndReturn",
      GlobalOmitOptions
    >
  >

  /**
   * Delete a Case.
   * @param {CaseDeleteArgs} args - Arguments to delete one Case.
   * @example
   * // Delete one Case
   * const Case = await prisma.case.delete({
   *   where: {
   *     // ... filter to delete one Case
   *   }
   * })
   *
   */
  delete<T extends CaseDeleteArgs>(
    args: Prisma.SelectSubset<T, CaseDeleteArgs<ExtArgs>>,
  ): Prisma.Prisma__CaseClient<
    runtime.Types.Result.GetResult<Prisma.$CasePayload<ExtArgs>, T, "delete", GlobalOmitOptions>,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Update one Case.
   * @param {CaseUpdateArgs} args - Arguments to update one Case.
   * @example
   * // Update one Case
   * const case = await prisma.case.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends CaseUpdateArgs>(
    args: Prisma.SelectSubset<T, CaseUpdateArgs<ExtArgs>>,
  ): Prisma.Prisma__CaseClient<
    runtime.Types.Result.GetResult<Prisma.$CasePayload<ExtArgs>, T, "update", GlobalOmitOptions>,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Delete zero or more Cases.
   * @param {CaseDeleteManyArgs} args - Arguments to filter Cases to delete.
   * @example
   * // Delete a few Cases
   * const { count } = await prisma.case.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends CaseDeleteManyArgs>(
    args?: Prisma.SelectSubset<T, CaseDeleteManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Cases.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CaseUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Cases
   * const case = await prisma.case.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends CaseUpdateManyArgs>(
    args: Prisma.SelectSubset<T, CaseUpdateManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Cases and returns the data updated in the database.
   * @param {CaseUpdateManyAndReturnArgs} args - Arguments to update many Cases.
   * @example
   * // Update many Cases
   * const case = await prisma.case.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Update zero or more Cases and only return the `id`
   * const caseWithIdOnly = await prisma.case.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  updateManyAndReturn<T extends CaseUpdateManyAndReturnArgs>(
    args: Prisma.SelectSubset<T, CaseUpdateManyAndReturnArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$CasePayload<ExtArgs>,
      T,
      "updateManyAndReturn",
      GlobalOmitOptions
    >
  >

  /**
   * Create or update one Case.
   * @param {CaseUpsertArgs} args - Arguments to update or create a Case.
   * @example
   * // Update or create a Case
   * const case = await prisma.case.upsert({
   *   create: {
   *     // ... data to create a Case
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Case we want to update
   *   }
   * })
   */
  upsert<T extends CaseUpsertArgs>(
    args: Prisma.SelectSubset<T, CaseUpsertArgs<ExtArgs>>,
  ): Prisma.Prisma__CaseClient<
    runtime.Types.Result.GetResult<Prisma.$CasePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Count the number of Cases.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CaseCountArgs} args - Arguments to filter Cases to count.
   * @example
   * // Count the number of Cases
   * const count = await prisma.case.count({
   *   where: {
   *     // ... the filter for the Cases we want to count
   *   }
   * })
   **/
  count<T extends CaseCountArgs>(
    args?: Prisma.Subset<T, CaseCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<"select", any>
      ? T["select"] extends true
        ? number
        : Prisma.GetScalarType<T["select"], CaseCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Case.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CaseAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
   **/
  aggregate<T extends CaseAggregateArgs>(
    args: Prisma.Subset<T, CaseAggregateArgs>,
  ): Prisma.PrismaPromise<GetCaseAggregateType<T>>

  /**
   * Group by Case.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CaseGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
   **/
  groupBy<
    T extends CaseGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<"skip", Prisma.Keys<T>>,
      Prisma.Extends<"take", Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CaseGroupByArgs["orderBy"] }
      : { orderBy?: CaseGroupByArgs["orderBy"] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<
      Prisma.Keys<Prisma.MaybeTupleToUnion<T["orderBy"]>>
    >,
    ByFields extends Prisma.MaybeTupleToUnion<T["by"]>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T["having"]>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T["by"] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
      ? `Error: "by" must not be empty.`
      : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
                ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                : [Error, "Field ", P, ` in "having" needs to be provided in "by"`]
          }[HavingFields]
        : "take" extends Prisma.Keys<T>
          ? "orderBy" extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                }[OrderFields]
            : 'Error: If you provide "take", you also need to provide "orderBy"'
          : "skip" extends Prisma.Keys<T>
            ? "orderBy" extends Prisma.Keys<T>
              ? ByValid extends Prisma.True
                ? {}
                : {
                    [P in OrderFields]: P extends ByFields
                      ? never
                      : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                  }[OrderFields]
              : 'Error: If you provide "skip", you also need to provide "orderBy"'
            : ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                }[OrderFields],
  >(
    args: Prisma.SubsetIntersection<T, CaseGroupByArgs, OrderByArg> & InputErrors,
  ): {} extends InputErrors ? GetCaseGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
  /**
   * Fields of the Case model
   */
  readonly fields: CaseFieldRefs
}

/**
 * The delegate class that acts as a "Promise-like" for Case.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CaseClient<
  T,
  Null = never,
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  payerInfo<T extends Prisma.PayerInfoDefaultArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.PayerInfoDefaultArgs<ExtArgs>>,
  ): Prisma.Prisma__PayerInfoClient<
    | runtime.Types.Result.GetResult<
        Prisma.$PayerInfoPayload<ExtArgs>,
        T,
        "findUniqueOrThrow",
        GlobalOmitOptions
      >
    | Null,
    Null,
    ExtArgs,
    GlobalOmitOptions
  >
  victimInfo<T extends Prisma.VictimInfoDefaultArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.VictimInfoDefaultArgs<ExtArgs>>,
  ): Prisma.Prisma__VictimInfoClient<
    | runtime.Types.Result.GetResult<
        Prisma.$VictimInfoPayload<ExtArgs>,
        T,
        "findUniqueOrThrow",
        GlobalOmitOptions
      >
    | Null,
    Null,
    ExtArgs,
    GlobalOmitOptions
  >
  accidentInfo<T extends Prisma.AccidentInfoDefaultArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.AccidentInfoDefaultArgs<ExtArgs>>,
  ): Prisma.Prisma__AccidentInfoClient<
    | runtime.Types.Result.GetResult<
        Prisma.$AccidentInfoPayload<ExtArgs>,
        T,
        "findUniqueOrThrow",
        GlobalOmitOptions
      >
    | Null,
    Null,
    ExtArgs,
    GlobalOmitOptions
  >
  cardOfAccident<T extends Prisma.Case$cardOfAccidentArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.Case$cardOfAccidentArgs<ExtArgs>>,
  ): Prisma.Prisma__FileClient<
    runtime.Types.Result.GetResult<
      Prisma.$FilePayload<ExtArgs>,
      T,
      "findUniqueOrThrow",
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(
    onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null,
    onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null,
  ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(
    onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null,
  ): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}

/**
 * Fields of the Case model
 */
export interface CaseFieldRefs {
  readonly id: Prisma.FieldRef<"Case", "String">
  readonly caseNumber: Prisma.FieldRef<"Case", "String">
  readonly comments: Prisma.FieldRef<"Case", "String">
  readonly payerInfoId: Prisma.FieldRef<"Case", "String">
  readonly victimInfoId: Prisma.FieldRef<"Case", "String">
  readonly cardOfAccidentId: Prisma.FieldRef<"Case", "String">
  readonly createdAt: Prisma.FieldRef<"Case", "DateTime">
  readonly updatedAt: Prisma.FieldRef<"Case", "DateTime">
  readonly accidentInfoId: Prisma.FieldRef<"Case", "String">
}

// Custom InputTypes
/**
 * Case findUnique
 */
export type CaseFindUniqueArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Case
   */
  select?: Prisma.CaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Case
   */
  omit?: Prisma.CaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaseInclude<ExtArgs> | null
  /**
   * Filter, which Case to fetch.
   */
  where: Prisma.CaseWhereUniqueInput
}

/**
 * Case findUniqueOrThrow
 */
export type CaseFindUniqueOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Case
   */
  select?: Prisma.CaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Case
   */
  omit?: Prisma.CaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaseInclude<ExtArgs> | null
  /**
   * Filter, which Case to fetch.
   */
  where: Prisma.CaseWhereUniqueInput
}

/**
 * Case findFirst
 */
export type CaseFindFirstArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Case
   */
  select?: Prisma.CaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Case
   */
  omit?: Prisma.CaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaseInclude<ExtArgs> | null
  /**
   * Filter, which Case to fetch.
   */
  where?: Prisma.CaseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of Cases to fetch.
   */
  orderBy?: Prisma.CaseOrderByWithRelationInput | Prisma.CaseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for Cases.
   */
  cursor?: Prisma.CaseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` Cases from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` Cases.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of Cases.
   */
  distinct?: Prisma.CaseScalarFieldEnum | Prisma.CaseScalarFieldEnum[]
}

/**
 * Case findFirstOrThrow
 */
export type CaseFindFirstOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Case
   */
  select?: Prisma.CaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Case
   */
  omit?: Prisma.CaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaseInclude<ExtArgs> | null
  /**
   * Filter, which Case to fetch.
   */
  where?: Prisma.CaseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of Cases to fetch.
   */
  orderBy?: Prisma.CaseOrderByWithRelationInput | Prisma.CaseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for Cases.
   */
  cursor?: Prisma.CaseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` Cases from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` Cases.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of Cases.
   */
  distinct?: Prisma.CaseScalarFieldEnum | Prisma.CaseScalarFieldEnum[]
}

/**
 * Case findMany
 */
export type CaseFindManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Case
   */
  select?: Prisma.CaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Case
   */
  omit?: Prisma.CaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaseInclude<ExtArgs> | null
  /**
   * Filter, which Cases to fetch.
   */
  where?: Prisma.CaseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of Cases to fetch.
   */
  orderBy?: Prisma.CaseOrderByWithRelationInput | Prisma.CaseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing Cases.
   */
  cursor?: Prisma.CaseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` Cases from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` Cases.
   */
  skip?: number
  distinct?: Prisma.CaseScalarFieldEnum | Prisma.CaseScalarFieldEnum[]
}

/**
 * Case create
 */
export type CaseCreateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Case
   */
  select?: Prisma.CaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Case
   */
  omit?: Prisma.CaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaseInclude<ExtArgs> | null
  /**
   * The data needed to create a Case.
   */
  data: Prisma.XOR<Prisma.CaseCreateInput, Prisma.CaseUncheckedCreateInput>
}

/**
 * Case createMany
 */
export type CaseCreateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to create many Cases.
   */
  data: Prisma.CaseCreateManyInput | Prisma.CaseCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Case createManyAndReturn
 */
export type CaseCreateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Case
   */
  select?: Prisma.CaseSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Case
   */
  omit?: Prisma.CaseOmit<ExtArgs> | null
  /**
   * The data used to create many Cases.
   */
  data: Prisma.CaseCreateManyInput | Prisma.CaseCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaseIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Case update
 */
export type CaseUpdateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Case
   */
  select?: Prisma.CaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Case
   */
  omit?: Prisma.CaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaseInclude<ExtArgs> | null
  /**
   * The data needed to update a Case.
   */
  data: Prisma.XOR<Prisma.CaseUpdateInput, Prisma.CaseUncheckedUpdateInput>
  /**
   * Choose, which Case to update.
   */
  where: Prisma.CaseWhereUniqueInput
}

/**
 * Case updateMany
 */
export type CaseUpdateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to update Cases.
   */
  data: Prisma.XOR<Prisma.CaseUpdateManyMutationInput, Prisma.CaseUncheckedUpdateManyInput>
  /**
   * Filter which Cases to update
   */
  where?: Prisma.CaseWhereInput
  /**
   * Limit how many Cases to update.
   */
  limit?: number
}

/**
 * Case updateManyAndReturn
 */
export type CaseUpdateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Case
   */
  select?: Prisma.CaseSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Case
   */
  omit?: Prisma.CaseOmit<ExtArgs> | null
  /**
   * The data used to update Cases.
   */
  data: Prisma.XOR<Prisma.CaseUpdateManyMutationInput, Prisma.CaseUncheckedUpdateManyInput>
  /**
   * Filter which Cases to update
   */
  where?: Prisma.CaseWhereInput
  /**
   * Limit how many Cases to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaseIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Case upsert
 */
export type CaseUpsertArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Case
   */
  select?: Prisma.CaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Case
   */
  omit?: Prisma.CaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaseInclude<ExtArgs> | null
  /**
   * The filter to search for the Case to update in case it exists.
   */
  where: Prisma.CaseWhereUniqueInput
  /**
   * In case the Case found by the `where` argument doesn't exist, create a new Case with this data.
   */
  create: Prisma.XOR<Prisma.CaseCreateInput, Prisma.CaseUncheckedCreateInput>
  /**
   * In case the Case was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CaseUpdateInput, Prisma.CaseUncheckedUpdateInput>
}

/**
 * Case delete
 */
export type CaseDeleteArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Case
   */
  select?: Prisma.CaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Case
   */
  omit?: Prisma.CaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaseInclude<ExtArgs> | null
  /**
   * Filter which Case to delete.
   */
  where: Prisma.CaseWhereUniqueInput
}

/**
 * Case deleteMany
 */
export type CaseDeleteManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which Cases to delete
   */
  where?: Prisma.CaseWhereInput
  /**
   * Limit how many Cases to delete.
   */
  limit?: number
}

/**
 * Case.cardOfAccident
 */
export type Case$cardOfAccidentArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the File
   */
  select?: Prisma.FileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the File
   */
  omit?: Prisma.FileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FileInclude<ExtArgs> | null
  where?: Prisma.FileWhereInput
}

/**
 * Case without action
 */
export type CaseDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Case
   */
  select?: Prisma.CaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Case
   */
  omit?: Prisma.CaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaseInclude<ExtArgs> | null
}
