
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PayerInfo` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model PayerInfo
 * 
 */
export type PayerInfoModel = runtime.Types.Result.DefaultSelection<Prisma.$PayerInfoPayload>

export type AggregatePayerInfo = {
  _count: PayerInfoCountAggregateOutputType | null
  _min: PayerInfoMinAggregateOutputType | null
  _max: PayerInfoMaxAggregateOutputType | null
}

export type PayerInfoMinAggregateOutputType = {
  id: string | null
  payerName: string | null
  documentType: $Enums.DocumentType | null
  documentNumber: string | null
  nip: string | null
  regon: string | null
  pesel: string | null
  addressId: string | null
}

export type PayerInfoMaxAggregateOutputType = {
  id: string | null
  payerName: string | null
  documentType: $Enums.DocumentType | null
  documentNumber: string | null
  nip: string | null
  regon: string | null
  pesel: string | null
  addressId: string | null
}

export type PayerInfoCountAggregateOutputType = {
  id: number
  payerName: number
  documentType: number
  documentNumber: number
  nip: number
  regon: number
  pesel: number
  addressId: number
  _all: number
}


export type PayerInfoMinAggregateInputType = {
  id?: true
  payerName?: true
  documentType?: true
  documentNumber?: true
  nip?: true
  regon?: true
  pesel?: true
  addressId?: true
}

export type PayerInfoMaxAggregateInputType = {
  id?: true
  payerName?: true
  documentType?: true
  documentNumber?: true
  nip?: true
  regon?: true
  pesel?: true
  addressId?: true
}

export type PayerInfoCountAggregateInputType = {
  id?: true
  payerName?: true
  documentType?: true
  documentNumber?: true
  nip?: true
  regon?: true
  pesel?: true
  addressId?: true
  _all?: true
}

export type PayerInfoAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PayerInfo to aggregate.
   */
  where?: Prisma.PayerInfoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PayerInfos to fetch.
   */
  orderBy?: Prisma.PayerInfoOrderByWithRelationInput | Prisma.PayerInfoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PayerInfoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PayerInfos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PayerInfos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PayerInfos
  **/
  _count?: true | PayerInfoCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PayerInfoMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PayerInfoMaxAggregateInputType
}

export type GetPayerInfoAggregateType<T extends PayerInfoAggregateArgs> = {
      [P in keyof T & keyof AggregatePayerInfo]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePayerInfo[P]>
    : Prisma.GetScalarType<T[P], AggregatePayerInfo[P]>
}




export type PayerInfoGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PayerInfoWhereInput
  orderBy?: Prisma.PayerInfoOrderByWithAggregationInput | Prisma.PayerInfoOrderByWithAggregationInput[]
  by: Prisma.PayerInfoScalarFieldEnum[] | Prisma.PayerInfoScalarFieldEnum
  having?: Prisma.PayerInfoScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PayerInfoCountAggregateInputType | true
  _min?: PayerInfoMinAggregateInputType
  _max?: PayerInfoMaxAggregateInputType
}

export type PayerInfoGroupByOutputType = {
  id: string
  payerName: string
  documentType: $Enums.DocumentType
  documentNumber: string
  nip: string
  regon: string | null
  pesel: string | null
  addressId: string
  _count: PayerInfoCountAggregateOutputType | null
  _min: PayerInfoMinAggregateOutputType | null
  _max: PayerInfoMaxAggregateOutputType | null
}

type GetPayerInfoGroupByPayload<T extends PayerInfoGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PayerInfoGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PayerInfoGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PayerInfoGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PayerInfoGroupByOutputType[P]>
      }
    >
  >



export type PayerInfoWhereInput = {
  AND?: Prisma.PayerInfoWhereInput | Prisma.PayerInfoWhereInput[]
  OR?: Prisma.PayerInfoWhereInput[]
  NOT?: Prisma.PayerInfoWhereInput | Prisma.PayerInfoWhereInput[]
  id?: Prisma.StringFilter<"PayerInfo"> | string
  payerName?: Prisma.StringFilter<"PayerInfo"> | string
  documentType?: Prisma.EnumDocumentTypeFilter<"PayerInfo"> | $Enums.DocumentType
  documentNumber?: Prisma.StringFilter<"PayerInfo"> | string
  nip?: Prisma.StringFilter<"PayerInfo"> | string
  regon?: Prisma.StringNullableFilter<"PayerInfo"> | string | null
  pesel?: Prisma.StringNullableFilter<"PayerInfo"> | string | null
  addressId?: Prisma.StringFilter<"PayerInfo"> | string
  address?: Prisma.XOR<Prisma.AddressScalarRelationFilter, Prisma.AddressWhereInput>
  cases?: Prisma.CaseListRelationFilter
}

export type PayerInfoOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  payerName?: Prisma.SortOrder
  documentType?: Prisma.SortOrder
  documentNumber?: Prisma.SortOrder
  nip?: Prisma.SortOrder
  regon?: Prisma.SortOrderInput | Prisma.SortOrder
  pesel?: Prisma.SortOrderInput | Prisma.SortOrder
  addressId?: Prisma.SortOrder
  address?: Prisma.AddressOrderByWithRelationInput
  cases?: Prisma.CaseOrderByRelationAggregateInput
}

export type PayerInfoWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.PayerInfoWhereInput | Prisma.PayerInfoWhereInput[]
  OR?: Prisma.PayerInfoWhereInput[]
  NOT?: Prisma.PayerInfoWhereInput | Prisma.PayerInfoWhereInput[]
  payerName?: Prisma.StringFilter<"PayerInfo"> | string
  documentType?: Prisma.EnumDocumentTypeFilter<"PayerInfo"> | $Enums.DocumentType
  documentNumber?: Prisma.StringFilter<"PayerInfo"> | string
  nip?: Prisma.StringFilter<"PayerInfo"> | string
  regon?: Prisma.StringNullableFilter<"PayerInfo"> | string | null
  pesel?: Prisma.StringNullableFilter<"PayerInfo"> | string | null
  addressId?: Prisma.StringFilter<"PayerInfo"> | string
  address?: Prisma.XOR<Prisma.AddressScalarRelationFilter, Prisma.AddressWhereInput>
  cases?: Prisma.CaseListRelationFilter
}, "id">

export type PayerInfoOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  payerName?: Prisma.SortOrder
  documentType?: Prisma.SortOrder
  documentNumber?: Prisma.SortOrder
  nip?: Prisma.SortOrder
  regon?: Prisma.SortOrderInput | Prisma.SortOrder
  pesel?: Prisma.SortOrderInput | Prisma.SortOrder
  addressId?: Prisma.SortOrder
  _count?: Prisma.PayerInfoCountOrderByAggregateInput
  _max?: Prisma.PayerInfoMaxOrderByAggregateInput
  _min?: Prisma.PayerInfoMinOrderByAggregateInput
}

export type PayerInfoScalarWhereWithAggregatesInput = {
  AND?: Prisma.PayerInfoScalarWhereWithAggregatesInput | Prisma.PayerInfoScalarWhereWithAggregatesInput[]
  OR?: Prisma.PayerInfoScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PayerInfoScalarWhereWithAggregatesInput | Prisma.PayerInfoScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"PayerInfo"> | string
  payerName?: Prisma.StringWithAggregatesFilter<"PayerInfo"> | string
  documentType?: Prisma.EnumDocumentTypeWithAggregatesFilter<"PayerInfo"> | $Enums.DocumentType
  documentNumber?: Prisma.StringWithAggregatesFilter<"PayerInfo"> | string
  nip?: Prisma.StringWithAggregatesFilter<"PayerInfo"> | string
  regon?: Prisma.StringNullableWithAggregatesFilter<"PayerInfo"> | string | null
  pesel?: Prisma.StringNullableWithAggregatesFilter<"PayerInfo"> | string | null
  addressId?: Prisma.StringWithAggregatesFilter<"PayerInfo"> | string
}

export type PayerInfoCreateInput = {
  id?: string
  payerName: string
  documentType: $Enums.DocumentType
  documentNumber: string
  nip: string
  regon?: string | null
  pesel?: string | null
  address: Prisma.AddressCreateNestedOneWithoutReporterInfosInput
  cases?: Prisma.CaseCreateNestedManyWithoutPayerInfoInput
}

export type PayerInfoUncheckedCreateInput = {
  id?: string
  payerName: string
  documentType: $Enums.DocumentType
  documentNumber: string
  nip: string
  regon?: string | null
  pesel?: string | null
  addressId: string
  cases?: Prisma.CaseUncheckedCreateNestedManyWithoutPayerInfoInput
}

export type PayerInfoUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  payerName?: Prisma.StringFieldUpdateOperationsInput | string
  documentType?: Prisma.EnumDocumentTypeFieldUpdateOperationsInput | $Enums.DocumentType
  documentNumber?: Prisma.StringFieldUpdateOperationsInput | string
  nip?: Prisma.StringFieldUpdateOperationsInput | string
  regon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pesel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.AddressUpdateOneRequiredWithoutReporterInfosNestedInput
  cases?: Prisma.CaseUpdateManyWithoutPayerInfoNestedInput
}

export type PayerInfoUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  payerName?: Prisma.StringFieldUpdateOperationsInput | string
  documentType?: Prisma.EnumDocumentTypeFieldUpdateOperationsInput | $Enums.DocumentType
  documentNumber?: Prisma.StringFieldUpdateOperationsInput | string
  nip?: Prisma.StringFieldUpdateOperationsInput | string
  regon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pesel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  addressId?: Prisma.StringFieldUpdateOperationsInput | string
  cases?: Prisma.CaseUncheckedUpdateManyWithoutPayerInfoNestedInput
}

export type PayerInfoCreateManyInput = {
  id?: string
  payerName: string
  documentType: $Enums.DocumentType
  documentNumber: string
  nip: string
  regon?: string | null
  pesel?: string | null
  addressId: string
}

export type PayerInfoUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  payerName?: Prisma.StringFieldUpdateOperationsInput | string
  documentType?: Prisma.EnumDocumentTypeFieldUpdateOperationsInput | $Enums.DocumentType
  documentNumber?: Prisma.StringFieldUpdateOperationsInput | string
  nip?: Prisma.StringFieldUpdateOperationsInput | string
  regon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pesel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type PayerInfoUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  payerName?: Prisma.StringFieldUpdateOperationsInput | string
  documentType?: Prisma.EnumDocumentTypeFieldUpdateOperationsInput | $Enums.DocumentType
  documentNumber?: Prisma.StringFieldUpdateOperationsInput | string
  nip?: Prisma.StringFieldUpdateOperationsInput | string
  regon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pesel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  addressId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PayerInfoScalarRelationFilter = {
  is?: Prisma.PayerInfoWhereInput
  isNot?: Prisma.PayerInfoWhereInput
}

export type PayerInfoCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  payerName?: Prisma.SortOrder
  documentType?: Prisma.SortOrder
  documentNumber?: Prisma.SortOrder
  nip?: Prisma.SortOrder
  regon?: Prisma.SortOrder
  pesel?: Prisma.SortOrder
  addressId?: Prisma.SortOrder
}

export type PayerInfoMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  payerName?: Prisma.SortOrder
  documentType?: Prisma.SortOrder
  documentNumber?: Prisma.SortOrder
  nip?: Prisma.SortOrder
  regon?: Prisma.SortOrder
  pesel?: Prisma.SortOrder
  addressId?: Prisma.SortOrder
}

export type PayerInfoMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  payerName?: Prisma.SortOrder
  documentType?: Prisma.SortOrder
  documentNumber?: Prisma.SortOrder
  nip?: Prisma.SortOrder
  regon?: Prisma.SortOrder
  pesel?: Prisma.SortOrder
  addressId?: Prisma.SortOrder
}

export type PayerInfoListRelationFilter = {
  every?: Prisma.PayerInfoWhereInput
  some?: Prisma.PayerInfoWhereInput
  none?: Prisma.PayerInfoWhereInput
}

export type PayerInfoOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PayerInfoCreateNestedOneWithoutCasesInput = {
  create?: Prisma.XOR<Prisma.PayerInfoCreateWithoutCasesInput, Prisma.PayerInfoUncheckedCreateWithoutCasesInput>
  connectOrCreate?: Prisma.PayerInfoCreateOrConnectWithoutCasesInput
  connect?: Prisma.PayerInfoWhereUniqueInput
}

export type PayerInfoUpdateOneRequiredWithoutCasesNestedInput = {
  create?: Prisma.XOR<Prisma.PayerInfoCreateWithoutCasesInput, Prisma.PayerInfoUncheckedCreateWithoutCasesInput>
  connectOrCreate?: Prisma.PayerInfoCreateOrConnectWithoutCasesInput
  upsert?: Prisma.PayerInfoUpsertWithoutCasesInput
  connect?: Prisma.PayerInfoWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PayerInfoUpdateToOneWithWhereWithoutCasesInput, Prisma.PayerInfoUpdateWithoutCasesInput>, Prisma.PayerInfoUncheckedUpdateWithoutCasesInput>
}

export type EnumDocumentTypeFieldUpdateOperationsInput = {
  set?: $Enums.DocumentType
}

export type PayerInfoCreateNestedManyWithoutAddressInput = {
  create?: Prisma.XOR<Prisma.PayerInfoCreateWithoutAddressInput, Prisma.PayerInfoUncheckedCreateWithoutAddressInput> | Prisma.PayerInfoCreateWithoutAddressInput[] | Prisma.PayerInfoUncheckedCreateWithoutAddressInput[]
  connectOrCreate?: Prisma.PayerInfoCreateOrConnectWithoutAddressInput | Prisma.PayerInfoCreateOrConnectWithoutAddressInput[]
  createMany?: Prisma.PayerInfoCreateManyAddressInputEnvelope
  connect?: Prisma.PayerInfoWhereUniqueInput | Prisma.PayerInfoWhereUniqueInput[]
}

export type PayerInfoUncheckedCreateNestedManyWithoutAddressInput = {
  create?: Prisma.XOR<Prisma.PayerInfoCreateWithoutAddressInput, Prisma.PayerInfoUncheckedCreateWithoutAddressInput> | Prisma.PayerInfoCreateWithoutAddressInput[] | Prisma.PayerInfoUncheckedCreateWithoutAddressInput[]
  connectOrCreate?: Prisma.PayerInfoCreateOrConnectWithoutAddressInput | Prisma.PayerInfoCreateOrConnectWithoutAddressInput[]
  createMany?: Prisma.PayerInfoCreateManyAddressInputEnvelope
  connect?: Prisma.PayerInfoWhereUniqueInput | Prisma.PayerInfoWhereUniqueInput[]
}

export type PayerInfoUpdateManyWithoutAddressNestedInput = {
  create?: Prisma.XOR<Prisma.PayerInfoCreateWithoutAddressInput, Prisma.PayerInfoUncheckedCreateWithoutAddressInput> | Prisma.PayerInfoCreateWithoutAddressInput[] | Prisma.PayerInfoUncheckedCreateWithoutAddressInput[]
  connectOrCreate?: Prisma.PayerInfoCreateOrConnectWithoutAddressInput | Prisma.PayerInfoCreateOrConnectWithoutAddressInput[]
  upsert?: Prisma.PayerInfoUpsertWithWhereUniqueWithoutAddressInput | Prisma.PayerInfoUpsertWithWhereUniqueWithoutAddressInput[]
  createMany?: Prisma.PayerInfoCreateManyAddressInputEnvelope
  set?: Prisma.PayerInfoWhereUniqueInput | Prisma.PayerInfoWhereUniqueInput[]
  disconnect?: Prisma.PayerInfoWhereUniqueInput | Prisma.PayerInfoWhereUniqueInput[]
  delete?: Prisma.PayerInfoWhereUniqueInput | Prisma.PayerInfoWhereUniqueInput[]
  connect?: Prisma.PayerInfoWhereUniqueInput | Prisma.PayerInfoWhereUniqueInput[]
  update?: Prisma.PayerInfoUpdateWithWhereUniqueWithoutAddressInput | Prisma.PayerInfoUpdateWithWhereUniqueWithoutAddressInput[]
  updateMany?: Prisma.PayerInfoUpdateManyWithWhereWithoutAddressInput | Prisma.PayerInfoUpdateManyWithWhereWithoutAddressInput[]
  deleteMany?: Prisma.PayerInfoScalarWhereInput | Prisma.PayerInfoScalarWhereInput[]
}

export type PayerInfoUncheckedUpdateManyWithoutAddressNestedInput = {
  create?: Prisma.XOR<Prisma.PayerInfoCreateWithoutAddressInput, Prisma.PayerInfoUncheckedCreateWithoutAddressInput> | Prisma.PayerInfoCreateWithoutAddressInput[] | Prisma.PayerInfoUncheckedCreateWithoutAddressInput[]
  connectOrCreate?: Prisma.PayerInfoCreateOrConnectWithoutAddressInput | Prisma.PayerInfoCreateOrConnectWithoutAddressInput[]
  upsert?: Prisma.PayerInfoUpsertWithWhereUniqueWithoutAddressInput | Prisma.PayerInfoUpsertWithWhereUniqueWithoutAddressInput[]
  createMany?: Prisma.PayerInfoCreateManyAddressInputEnvelope
  set?: Prisma.PayerInfoWhereUniqueInput | Prisma.PayerInfoWhereUniqueInput[]
  disconnect?: Prisma.PayerInfoWhereUniqueInput | Prisma.PayerInfoWhereUniqueInput[]
  delete?: Prisma.PayerInfoWhereUniqueInput | Prisma.PayerInfoWhereUniqueInput[]
  connect?: Prisma.PayerInfoWhereUniqueInput | Prisma.PayerInfoWhereUniqueInput[]
  update?: Prisma.PayerInfoUpdateWithWhereUniqueWithoutAddressInput | Prisma.PayerInfoUpdateWithWhereUniqueWithoutAddressInput[]
  updateMany?: Prisma.PayerInfoUpdateManyWithWhereWithoutAddressInput | Prisma.PayerInfoUpdateManyWithWhereWithoutAddressInput[]
  deleteMany?: Prisma.PayerInfoScalarWhereInput | Prisma.PayerInfoScalarWhereInput[]
}

export type PayerInfoCreateWithoutCasesInput = {
  id?: string
  payerName: string
  documentType: $Enums.DocumentType
  documentNumber: string
  nip: string
  regon?: string | null
  pesel?: string | null
  address: Prisma.AddressCreateNestedOneWithoutReporterInfosInput
}

export type PayerInfoUncheckedCreateWithoutCasesInput = {
  id?: string
  payerName: string
  documentType: $Enums.DocumentType
  documentNumber: string
  nip: string
  regon?: string | null
  pesel?: string | null
  addressId: string
}

export type PayerInfoCreateOrConnectWithoutCasesInput = {
  where: Prisma.PayerInfoWhereUniqueInput
  create: Prisma.XOR<Prisma.PayerInfoCreateWithoutCasesInput, Prisma.PayerInfoUncheckedCreateWithoutCasesInput>
}

export type PayerInfoUpsertWithoutCasesInput = {
  update: Prisma.XOR<Prisma.PayerInfoUpdateWithoutCasesInput, Prisma.PayerInfoUncheckedUpdateWithoutCasesInput>
  create: Prisma.XOR<Prisma.PayerInfoCreateWithoutCasesInput, Prisma.PayerInfoUncheckedCreateWithoutCasesInput>
  where?: Prisma.PayerInfoWhereInput
}

export type PayerInfoUpdateToOneWithWhereWithoutCasesInput = {
  where?: Prisma.PayerInfoWhereInput
  data: Prisma.XOR<Prisma.PayerInfoUpdateWithoutCasesInput, Prisma.PayerInfoUncheckedUpdateWithoutCasesInput>
}

export type PayerInfoUpdateWithoutCasesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  payerName?: Prisma.StringFieldUpdateOperationsInput | string
  documentType?: Prisma.EnumDocumentTypeFieldUpdateOperationsInput | $Enums.DocumentType
  documentNumber?: Prisma.StringFieldUpdateOperationsInput | string
  nip?: Prisma.StringFieldUpdateOperationsInput | string
  regon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pesel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.AddressUpdateOneRequiredWithoutReporterInfosNestedInput
}

export type PayerInfoUncheckedUpdateWithoutCasesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  payerName?: Prisma.StringFieldUpdateOperationsInput | string
  documentType?: Prisma.EnumDocumentTypeFieldUpdateOperationsInput | $Enums.DocumentType
  documentNumber?: Prisma.StringFieldUpdateOperationsInput | string
  nip?: Prisma.StringFieldUpdateOperationsInput | string
  regon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pesel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  addressId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PayerInfoCreateWithoutAddressInput = {
  id?: string
  payerName: string
  documentType: $Enums.DocumentType
  documentNumber: string
  nip: string
  regon?: string | null
  pesel?: string | null
  cases?: Prisma.CaseCreateNestedManyWithoutPayerInfoInput
}

export type PayerInfoUncheckedCreateWithoutAddressInput = {
  id?: string
  payerName: string
  documentType: $Enums.DocumentType
  documentNumber: string
  nip: string
  regon?: string | null
  pesel?: string | null
  cases?: Prisma.CaseUncheckedCreateNestedManyWithoutPayerInfoInput
}

export type PayerInfoCreateOrConnectWithoutAddressInput = {
  where: Prisma.PayerInfoWhereUniqueInput
  create: Prisma.XOR<Prisma.PayerInfoCreateWithoutAddressInput, Prisma.PayerInfoUncheckedCreateWithoutAddressInput>
}

export type PayerInfoCreateManyAddressInputEnvelope = {
  data: Prisma.PayerInfoCreateManyAddressInput | Prisma.PayerInfoCreateManyAddressInput[]
  skipDuplicates?: boolean
}

export type PayerInfoUpsertWithWhereUniqueWithoutAddressInput = {
  where: Prisma.PayerInfoWhereUniqueInput
  update: Prisma.XOR<Prisma.PayerInfoUpdateWithoutAddressInput, Prisma.PayerInfoUncheckedUpdateWithoutAddressInput>
  create: Prisma.XOR<Prisma.PayerInfoCreateWithoutAddressInput, Prisma.PayerInfoUncheckedCreateWithoutAddressInput>
}

export type PayerInfoUpdateWithWhereUniqueWithoutAddressInput = {
  where: Prisma.PayerInfoWhereUniqueInput
  data: Prisma.XOR<Prisma.PayerInfoUpdateWithoutAddressInput, Prisma.PayerInfoUncheckedUpdateWithoutAddressInput>
}

export type PayerInfoUpdateManyWithWhereWithoutAddressInput = {
  where: Prisma.PayerInfoScalarWhereInput
  data: Prisma.XOR<Prisma.PayerInfoUpdateManyMutationInput, Prisma.PayerInfoUncheckedUpdateManyWithoutAddressInput>
}

export type PayerInfoScalarWhereInput = {
  AND?: Prisma.PayerInfoScalarWhereInput | Prisma.PayerInfoScalarWhereInput[]
  OR?: Prisma.PayerInfoScalarWhereInput[]
  NOT?: Prisma.PayerInfoScalarWhereInput | Prisma.PayerInfoScalarWhereInput[]
  id?: Prisma.StringFilter<"PayerInfo"> | string
  payerName?: Prisma.StringFilter<"PayerInfo"> | string
  documentType?: Prisma.EnumDocumentTypeFilter<"PayerInfo"> | $Enums.DocumentType
  documentNumber?: Prisma.StringFilter<"PayerInfo"> | string
  nip?: Prisma.StringFilter<"PayerInfo"> | string
  regon?: Prisma.StringNullableFilter<"PayerInfo"> | string | null
  pesel?: Prisma.StringNullableFilter<"PayerInfo"> | string | null
  addressId?: Prisma.StringFilter<"PayerInfo"> | string
}

export type PayerInfoCreateManyAddressInput = {
  id?: string
  payerName: string
  documentType: $Enums.DocumentType
  documentNumber: string
  nip: string
  regon?: string | null
  pesel?: string | null
}

export type PayerInfoUpdateWithoutAddressInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  payerName?: Prisma.StringFieldUpdateOperationsInput | string
  documentType?: Prisma.EnumDocumentTypeFieldUpdateOperationsInput | $Enums.DocumentType
  documentNumber?: Prisma.StringFieldUpdateOperationsInput | string
  nip?: Prisma.StringFieldUpdateOperationsInput | string
  regon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pesel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cases?: Prisma.CaseUpdateManyWithoutPayerInfoNestedInput
}

export type PayerInfoUncheckedUpdateWithoutAddressInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  payerName?: Prisma.StringFieldUpdateOperationsInput | string
  documentType?: Prisma.EnumDocumentTypeFieldUpdateOperationsInput | $Enums.DocumentType
  documentNumber?: Prisma.StringFieldUpdateOperationsInput | string
  nip?: Prisma.StringFieldUpdateOperationsInput | string
  regon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pesel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cases?: Prisma.CaseUncheckedUpdateManyWithoutPayerInfoNestedInput
}

export type PayerInfoUncheckedUpdateManyWithoutAddressInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  payerName?: Prisma.StringFieldUpdateOperationsInput | string
  documentType?: Prisma.EnumDocumentTypeFieldUpdateOperationsInput | $Enums.DocumentType
  documentNumber?: Prisma.StringFieldUpdateOperationsInput | string
  nip?: Prisma.StringFieldUpdateOperationsInput | string
  regon?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pesel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}


/**
 * Count Type PayerInfoCountOutputType
 */

export type PayerInfoCountOutputType = {
  cases: number
}

export type PayerInfoCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  cases?: boolean | PayerInfoCountOutputTypeCountCasesArgs
}

/**
 * PayerInfoCountOutputType without action
 */
export type PayerInfoCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PayerInfoCountOutputType
   */
  select?: Prisma.PayerInfoCountOutputTypeSelect<ExtArgs> | null
}

/**
 * PayerInfoCountOutputType without action
 */
export type PayerInfoCountOutputTypeCountCasesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CaseWhereInput
}


export type PayerInfoSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  payerName?: boolean
  documentType?: boolean
  documentNumber?: boolean
  nip?: boolean
  regon?: boolean
  pesel?: boolean
  addressId?: boolean
  address?: boolean | Prisma.AddressDefaultArgs<ExtArgs>
  cases?: boolean | Prisma.PayerInfo$casesArgs<ExtArgs>
  _count?: boolean | Prisma.PayerInfoCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["payerInfo"]>

export type PayerInfoSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  payerName?: boolean
  documentType?: boolean
  documentNumber?: boolean
  nip?: boolean
  regon?: boolean
  pesel?: boolean
  addressId?: boolean
  address?: boolean | Prisma.AddressDefaultArgs<ExtArgs>
}, ExtArgs["result"]["payerInfo"]>

export type PayerInfoSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  payerName?: boolean
  documentType?: boolean
  documentNumber?: boolean
  nip?: boolean
  regon?: boolean
  pesel?: boolean
  addressId?: boolean
  address?: boolean | Prisma.AddressDefaultArgs<ExtArgs>
}, ExtArgs["result"]["payerInfo"]>

export type PayerInfoSelectScalar = {
  id?: boolean
  payerName?: boolean
  documentType?: boolean
  documentNumber?: boolean
  nip?: boolean
  regon?: boolean
  pesel?: boolean
  addressId?: boolean
}

export type PayerInfoOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "payerName" | "documentType" | "documentNumber" | "nip" | "regon" | "pesel" | "addressId", ExtArgs["result"]["payerInfo"]>
export type PayerInfoInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  address?: boolean | Prisma.AddressDefaultArgs<ExtArgs>
  cases?: boolean | Prisma.PayerInfo$casesArgs<ExtArgs>
  _count?: boolean | Prisma.PayerInfoCountOutputTypeDefaultArgs<ExtArgs>
}
export type PayerInfoIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  address?: boolean | Prisma.AddressDefaultArgs<ExtArgs>
}
export type PayerInfoIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  address?: boolean | Prisma.AddressDefaultArgs<ExtArgs>
}

export type $PayerInfoPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PayerInfo"
  objects: {
    address: Prisma.$AddressPayload<ExtArgs>
    cases: Prisma.$CasePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    payerName: string
    documentType: $Enums.DocumentType
    documentNumber: string
    nip: string
    regon: string | null
    pesel: string | null
    addressId: string
  }, ExtArgs["result"]["payerInfo"]>
  composites: {}
}

export type PayerInfoGetPayload<S extends boolean | null | undefined | PayerInfoDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PayerInfoPayload, S>

export type PayerInfoCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PayerInfoFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PayerInfoCountAggregateInputType | true
  }

export interface PayerInfoDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PayerInfo'], meta: { name: 'PayerInfo' } }
  /**
   * Find zero or one PayerInfo that matches the filter.
   * @param {PayerInfoFindUniqueArgs} args - Arguments to find a PayerInfo
   * @example
   * // Get one PayerInfo
   * const payerInfo = await prisma.payerInfo.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PayerInfoFindUniqueArgs>(args: Prisma.SelectSubset<T, PayerInfoFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PayerInfoClient<runtime.Types.Result.GetResult<Prisma.$PayerInfoPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PayerInfo that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PayerInfoFindUniqueOrThrowArgs} args - Arguments to find a PayerInfo
   * @example
   * // Get one PayerInfo
   * const payerInfo = await prisma.payerInfo.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PayerInfoFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PayerInfoFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PayerInfoClient<runtime.Types.Result.GetResult<Prisma.$PayerInfoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PayerInfo that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PayerInfoFindFirstArgs} args - Arguments to find a PayerInfo
   * @example
   * // Get one PayerInfo
   * const payerInfo = await prisma.payerInfo.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PayerInfoFindFirstArgs>(args?: Prisma.SelectSubset<T, PayerInfoFindFirstArgs<ExtArgs>>): Prisma.Prisma__PayerInfoClient<runtime.Types.Result.GetResult<Prisma.$PayerInfoPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PayerInfo that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PayerInfoFindFirstOrThrowArgs} args - Arguments to find a PayerInfo
   * @example
   * // Get one PayerInfo
   * const payerInfo = await prisma.payerInfo.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PayerInfoFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PayerInfoFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PayerInfoClient<runtime.Types.Result.GetResult<Prisma.$PayerInfoPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PayerInfos that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PayerInfoFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PayerInfos
   * const payerInfos = await prisma.payerInfo.findMany()
   * 
   * // Get first 10 PayerInfos
   * const payerInfos = await prisma.payerInfo.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const payerInfoWithIdOnly = await prisma.payerInfo.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PayerInfoFindManyArgs>(args?: Prisma.SelectSubset<T, PayerInfoFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PayerInfoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PayerInfo.
   * @param {PayerInfoCreateArgs} args - Arguments to create a PayerInfo.
   * @example
   * // Create one PayerInfo
   * const PayerInfo = await prisma.payerInfo.create({
   *   data: {
   *     // ... data to create a PayerInfo
   *   }
   * })
   * 
   */
  create<T extends PayerInfoCreateArgs>(args: Prisma.SelectSubset<T, PayerInfoCreateArgs<ExtArgs>>): Prisma.Prisma__PayerInfoClient<runtime.Types.Result.GetResult<Prisma.$PayerInfoPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PayerInfos.
   * @param {PayerInfoCreateManyArgs} args - Arguments to create many PayerInfos.
   * @example
   * // Create many PayerInfos
   * const payerInfo = await prisma.payerInfo.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PayerInfoCreateManyArgs>(args?: Prisma.SelectSubset<T, PayerInfoCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PayerInfos and returns the data saved in the database.
   * @param {PayerInfoCreateManyAndReturnArgs} args - Arguments to create many PayerInfos.
   * @example
   * // Create many PayerInfos
   * const payerInfo = await prisma.payerInfo.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PayerInfos and only return the `id`
   * const payerInfoWithIdOnly = await prisma.payerInfo.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PayerInfoCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PayerInfoCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PayerInfoPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PayerInfo.
   * @param {PayerInfoDeleteArgs} args - Arguments to delete one PayerInfo.
   * @example
   * // Delete one PayerInfo
   * const PayerInfo = await prisma.payerInfo.delete({
   *   where: {
   *     // ... filter to delete one PayerInfo
   *   }
   * })
   * 
   */
  delete<T extends PayerInfoDeleteArgs>(args: Prisma.SelectSubset<T, PayerInfoDeleteArgs<ExtArgs>>): Prisma.Prisma__PayerInfoClient<runtime.Types.Result.GetResult<Prisma.$PayerInfoPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PayerInfo.
   * @param {PayerInfoUpdateArgs} args - Arguments to update one PayerInfo.
   * @example
   * // Update one PayerInfo
   * const payerInfo = await prisma.payerInfo.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PayerInfoUpdateArgs>(args: Prisma.SelectSubset<T, PayerInfoUpdateArgs<ExtArgs>>): Prisma.Prisma__PayerInfoClient<runtime.Types.Result.GetResult<Prisma.$PayerInfoPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PayerInfos.
   * @param {PayerInfoDeleteManyArgs} args - Arguments to filter PayerInfos to delete.
   * @example
   * // Delete a few PayerInfos
   * const { count } = await prisma.payerInfo.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PayerInfoDeleteManyArgs>(args?: Prisma.SelectSubset<T, PayerInfoDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PayerInfos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PayerInfoUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PayerInfos
   * const payerInfo = await prisma.payerInfo.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PayerInfoUpdateManyArgs>(args: Prisma.SelectSubset<T, PayerInfoUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PayerInfos and returns the data updated in the database.
   * @param {PayerInfoUpdateManyAndReturnArgs} args - Arguments to update many PayerInfos.
   * @example
   * // Update many PayerInfos
   * const payerInfo = await prisma.payerInfo.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PayerInfos and only return the `id`
   * const payerInfoWithIdOnly = await prisma.payerInfo.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PayerInfoUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PayerInfoUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PayerInfoPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PayerInfo.
   * @param {PayerInfoUpsertArgs} args - Arguments to update or create a PayerInfo.
   * @example
   * // Update or create a PayerInfo
   * const payerInfo = await prisma.payerInfo.upsert({
   *   create: {
   *     // ... data to create a PayerInfo
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PayerInfo we want to update
   *   }
   * })
   */
  upsert<T extends PayerInfoUpsertArgs>(args: Prisma.SelectSubset<T, PayerInfoUpsertArgs<ExtArgs>>): Prisma.Prisma__PayerInfoClient<runtime.Types.Result.GetResult<Prisma.$PayerInfoPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PayerInfos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PayerInfoCountArgs} args - Arguments to filter PayerInfos to count.
   * @example
   * // Count the number of PayerInfos
   * const count = await prisma.payerInfo.count({
   *   where: {
   *     // ... the filter for the PayerInfos we want to count
   *   }
   * })
  **/
  count<T extends PayerInfoCountArgs>(
    args?: Prisma.Subset<T, PayerInfoCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PayerInfoCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PayerInfo.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PayerInfoAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PayerInfoAggregateArgs>(args: Prisma.Subset<T, PayerInfoAggregateArgs>): Prisma.PrismaPromise<GetPayerInfoAggregateType<T>>

  /**
   * Group by PayerInfo.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PayerInfoGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PayerInfoGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PayerInfoGroupByArgs['orderBy'] }
      : { orderBy?: PayerInfoGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PayerInfoGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPayerInfoGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PayerInfo model
 */
readonly fields: PayerInfoFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PayerInfo.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PayerInfoClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  address<T extends Prisma.AddressDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AddressDefaultArgs<ExtArgs>>): Prisma.Prisma__AddressClient<runtime.Types.Result.GetResult<Prisma.$AddressPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  cases<T extends Prisma.PayerInfo$casesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PayerInfo$casesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CasePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PayerInfo model
 */
export interface PayerInfoFieldRefs {
  readonly id: Prisma.FieldRef<"PayerInfo", 'String'>
  readonly payerName: Prisma.FieldRef<"PayerInfo", 'String'>
  readonly documentType: Prisma.FieldRef<"PayerInfo", 'DocumentType'>
  readonly documentNumber: Prisma.FieldRef<"PayerInfo", 'String'>
  readonly nip: Prisma.FieldRef<"PayerInfo", 'String'>
  readonly regon: Prisma.FieldRef<"PayerInfo", 'String'>
  readonly pesel: Prisma.FieldRef<"PayerInfo", 'String'>
  readonly addressId: Prisma.FieldRef<"PayerInfo", 'String'>
}
    

// Custom InputTypes
/**
 * PayerInfo findUnique
 */
export type PayerInfoFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PayerInfo
   */
  select?: Prisma.PayerInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PayerInfo
   */
  omit?: Prisma.PayerInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PayerInfoInclude<ExtArgs> | null
  /**
   * Filter, which PayerInfo to fetch.
   */
  where: Prisma.PayerInfoWhereUniqueInput
}

/**
 * PayerInfo findUniqueOrThrow
 */
export type PayerInfoFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PayerInfo
   */
  select?: Prisma.PayerInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PayerInfo
   */
  omit?: Prisma.PayerInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PayerInfoInclude<ExtArgs> | null
  /**
   * Filter, which PayerInfo to fetch.
   */
  where: Prisma.PayerInfoWhereUniqueInput
}

/**
 * PayerInfo findFirst
 */
export type PayerInfoFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PayerInfo
   */
  select?: Prisma.PayerInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PayerInfo
   */
  omit?: Prisma.PayerInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PayerInfoInclude<ExtArgs> | null
  /**
   * Filter, which PayerInfo to fetch.
   */
  where?: Prisma.PayerInfoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PayerInfos to fetch.
   */
  orderBy?: Prisma.PayerInfoOrderByWithRelationInput | Prisma.PayerInfoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PayerInfos.
   */
  cursor?: Prisma.PayerInfoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PayerInfos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PayerInfos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PayerInfos.
   */
  distinct?: Prisma.PayerInfoScalarFieldEnum | Prisma.PayerInfoScalarFieldEnum[]
}

/**
 * PayerInfo findFirstOrThrow
 */
export type PayerInfoFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PayerInfo
   */
  select?: Prisma.PayerInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PayerInfo
   */
  omit?: Prisma.PayerInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PayerInfoInclude<ExtArgs> | null
  /**
   * Filter, which PayerInfo to fetch.
   */
  where?: Prisma.PayerInfoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PayerInfos to fetch.
   */
  orderBy?: Prisma.PayerInfoOrderByWithRelationInput | Prisma.PayerInfoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PayerInfos.
   */
  cursor?: Prisma.PayerInfoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PayerInfos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PayerInfos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PayerInfos.
   */
  distinct?: Prisma.PayerInfoScalarFieldEnum | Prisma.PayerInfoScalarFieldEnum[]
}

/**
 * PayerInfo findMany
 */
export type PayerInfoFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PayerInfo
   */
  select?: Prisma.PayerInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PayerInfo
   */
  omit?: Prisma.PayerInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PayerInfoInclude<ExtArgs> | null
  /**
   * Filter, which PayerInfos to fetch.
   */
  where?: Prisma.PayerInfoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PayerInfos to fetch.
   */
  orderBy?: Prisma.PayerInfoOrderByWithRelationInput | Prisma.PayerInfoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PayerInfos.
   */
  cursor?: Prisma.PayerInfoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PayerInfos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PayerInfos.
   */
  skip?: number
  distinct?: Prisma.PayerInfoScalarFieldEnum | Prisma.PayerInfoScalarFieldEnum[]
}

/**
 * PayerInfo create
 */
export type PayerInfoCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PayerInfo
   */
  select?: Prisma.PayerInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PayerInfo
   */
  omit?: Prisma.PayerInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PayerInfoInclude<ExtArgs> | null
  /**
   * The data needed to create a PayerInfo.
   */
  data: Prisma.XOR<Prisma.PayerInfoCreateInput, Prisma.PayerInfoUncheckedCreateInput>
}

/**
 * PayerInfo createMany
 */
export type PayerInfoCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PayerInfos.
   */
  data: Prisma.PayerInfoCreateManyInput | Prisma.PayerInfoCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PayerInfo createManyAndReturn
 */
export type PayerInfoCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PayerInfo
   */
  select?: Prisma.PayerInfoSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PayerInfo
   */
  omit?: Prisma.PayerInfoOmit<ExtArgs> | null
  /**
   * The data used to create many PayerInfos.
   */
  data: Prisma.PayerInfoCreateManyInput | Prisma.PayerInfoCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PayerInfoIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * PayerInfo update
 */
export type PayerInfoUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PayerInfo
   */
  select?: Prisma.PayerInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PayerInfo
   */
  omit?: Prisma.PayerInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PayerInfoInclude<ExtArgs> | null
  /**
   * The data needed to update a PayerInfo.
   */
  data: Prisma.XOR<Prisma.PayerInfoUpdateInput, Prisma.PayerInfoUncheckedUpdateInput>
  /**
   * Choose, which PayerInfo to update.
   */
  where: Prisma.PayerInfoWhereUniqueInput
}

/**
 * PayerInfo updateMany
 */
export type PayerInfoUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PayerInfos.
   */
  data: Prisma.XOR<Prisma.PayerInfoUpdateManyMutationInput, Prisma.PayerInfoUncheckedUpdateManyInput>
  /**
   * Filter which PayerInfos to update
   */
  where?: Prisma.PayerInfoWhereInput
  /**
   * Limit how many PayerInfos to update.
   */
  limit?: number
}

/**
 * PayerInfo updateManyAndReturn
 */
export type PayerInfoUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PayerInfo
   */
  select?: Prisma.PayerInfoSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PayerInfo
   */
  omit?: Prisma.PayerInfoOmit<ExtArgs> | null
  /**
   * The data used to update PayerInfos.
   */
  data: Prisma.XOR<Prisma.PayerInfoUpdateManyMutationInput, Prisma.PayerInfoUncheckedUpdateManyInput>
  /**
   * Filter which PayerInfos to update
   */
  where?: Prisma.PayerInfoWhereInput
  /**
   * Limit how many PayerInfos to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PayerInfoIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * PayerInfo upsert
 */
export type PayerInfoUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PayerInfo
   */
  select?: Prisma.PayerInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PayerInfo
   */
  omit?: Prisma.PayerInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PayerInfoInclude<ExtArgs> | null
  /**
   * The filter to search for the PayerInfo to update in case it exists.
   */
  where: Prisma.PayerInfoWhereUniqueInput
  /**
   * In case the PayerInfo found by the `where` argument doesn't exist, create a new PayerInfo with this data.
   */
  create: Prisma.XOR<Prisma.PayerInfoCreateInput, Prisma.PayerInfoUncheckedCreateInput>
  /**
   * In case the PayerInfo was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PayerInfoUpdateInput, Prisma.PayerInfoUncheckedUpdateInput>
}

/**
 * PayerInfo delete
 */
export type PayerInfoDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PayerInfo
   */
  select?: Prisma.PayerInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PayerInfo
   */
  omit?: Prisma.PayerInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PayerInfoInclude<ExtArgs> | null
  /**
   * Filter which PayerInfo to delete.
   */
  where: Prisma.PayerInfoWhereUniqueInput
}

/**
 * PayerInfo deleteMany
 */
export type PayerInfoDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PayerInfos to delete
   */
  where?: Prisma.PayerInfoWhereInput
  /**
   * Limit how many PayerInfos to delete.
   */
  limit?: number
}

/**
 * PayerInfo.cases
 */
export type PayerInfo$casesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Case
   */
  select?: Prisma.CaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Case
   */
  omit?: Prisma.CaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaseInclude<ExtArgs> | null
  where?: Prisma.CaseWhereInput
  orderBy?: Prisma.CaseOrderByWithRelationInput | Prisma.CaseOrderByWithRelationInput[]
  cursor?: Prisma.CaseWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.CaseScalarFieldEnum | Prisma.CaseScalarFieldEnum[]
}

/**
 * PayerInfo without action
 */
export type PayerInfoDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PayerInfo
   */
  select?: Prisma.PayerInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PayerInfo
   */
  omit?: Prisma.PayerInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PayerInfoInclude<ExtArgs> | null
}
