/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `VictimInfo` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model VictimInfo
 *
 */
export type VictimInfoModel = runtime.Types.Result.DefaultSelection<Prisma.$VictimInfoPayload>

export type AggregateVictimInfo = {
  _count: VictimInfoCountAggregateOutputType | null
  _min: VictimInfoMinAggregateOutputType | null
  _max: VictimInfoMaxAggregateOutputType | null
}

export type VictimInfoMinAggregateOutputType = {
  id: string | null
  name: string | null
  pesel: string | null
  dateOfBirth: Date | null
  placeOfBirth: string | null
  documentType: $Enums.DocumentType | null
  documentNumber: string | null
  insuranceTitle: string | null
  addressId: string | null
}

export type VictimInfoMaxAggregateOutputType = {
  id: string | null
  name: string | null
  pesel: string | null
  dateOfBirth: Date | null
  placeOfBirth: string | null
  documentType: $Enums.DocumentType | null
  documentNumber: string | null
  insuranceTitle: string | null
  addressId: string | null
}

export type VictimInfoCountAggregateOutputType = {
  id: number
  name: number
  pesel: number
  dateOfBirth: number
  placeOfBirth: number
  documentType: number
  documentNumber: number
  insuranceTitle: number
  addressId: number
  _all: number
}

export type VictimInfoMinAggregateInputType = {
  id?: true
  name?: true
  pesel?: true
  dateOfBirth?: true
  placeOfBirth?: true
  documentType?: true
  documentNumber?: true
  insuranceTitle?: true
  addressId?: true
}

export type VictimInfoMaxAggregateInputType = {
  id?: true
  name?: true
  pesel?: true
  dateOfBirth?: true
  placeOfBirth?: true
  documentType?: true
  documentNumber?: true
  insuranceTitle?: true
  addressId?: true
}

export type VictimInfoCountAggregateInputType = {
  id?: true
  name?: true
  pesel?: true
  dateOfBirth?: true
  placeOfBirth?: true
  documentType?: true
  documentNumber?: true
  insuranceTitle?: true
  addressId?: true
  _all?: true
}

export type VictimInfoAggregateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which VictimInfo to aggregate.
   */
  where?: Prisma.VictimInfoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of VictimInfos to fetch.
   */
  orderBy?: Prisma.VictimInfoOrderByWithRelationInput | Prisma.VictimInfoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.VictimInfoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` VictimInfos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` VictimInfos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned VictimInfos
   **/
  _count?: true | VictimInfoCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
   **/
  _min?: VictimInfoMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
   **/
  _max?: VictimInfoMaxAggregateInputType
}

export type GetVictimInfoAggregateType<T extends VictimInfoAggregateArgs> = {
  [P in keyof T & keyof AggregateVictimInfo]: P extends "_count" | "count"
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateVictimInfo[P]>
    : Prisma.GetScalarType<T[P], AggregateVictimInfo[P]>
}

export type VictimInfoGroupByArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.VictimInfoWhereInput
  orderBy?:
    | Prisma.VictimInfoOrderByWithAggregationInput
    | Prisma.VictimInfoOrderByWithAggregationInput[]
  by: Prisma.VictimInfoScalarFieldEnum[] | Prisma.VictimInfoScalarFieldEnum
  having?: Prisma.VictimInfoScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: VictimInfoCountAggregateInputType | true
  _min?: VictimInfoMinAggregateInputType
  _max?: VictimInfoMaxAggregateInputType
}

export type VictimInfoGroupByOutputType = {
  id: string
  name: string
  pesel: string
  dateOfBirth: Date
  placeOfBirth: string
  documentType: $Enums.DocumentType
  documentNumber: string
  insuranceTitle: string
  addressId: string
  _count: VictimInfoCountAggregateOutputType | null
  _min: VictimInfoMinAggregateOutputType | null
  _max: VictimInfoMaxAggregateOutputType | null
}

type GetVictimInfoGroupByPayload<T extends VictimInfoGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<VictimInfoGroupByOutputType, T["by"]> & {
      [P in keyof T & keyof VictimInfoGroupByOutputType]: P extends "_count"
        ? T[P] extends boolean
          ? number
          : Prisma.GetScalarType<T[P], VictimInfoGroupByOutputType[P]>
        : Prisma.GetScalarType<T[P], VictimInfoGroupByOutputType[P]>
    }
  >
>

export type VictimInfoWhereInput = {
  AND?: Prisma.VictimInfoWhereInput | Prisma.VictimInfoWhereInput[]
  OR?: Prisma.VictimInfoWhereInput[]
  NOT?: Prisma.VictimInfoWhereInput | Prisma.VictimInfoWhereInput[]
  id?: Prisma.StringFilter<"VictimInfo"> | string
  name?: Prisma.StringFilter<"VictimInfo"> | string
  pesel?: Prisma.StringFilter<"VictimInfo"> | string
  dateOfBirth?: Prisma.DateTimeFilter<"VictimInfo"> | Date | string
  placeOfBirth?: Prisma.StringFilter<"VictimInfo"> | string
  documentType?: Prisma.EnumDocumentTypeFilter<"VictimInfo"> | $Enums.DocumentType
  documentNumber?: Prisma.StringFilter<"VictimInfo"> | string
  insuranceTitle?: Prisma.StringFilter<"VictimInfo"> | string
  addressId?: Prisma.StringFilter<"VictimInfo"> | string
  address?: Prisma.XOR<Prisma.AddressScalarRelationFilter, Prisma.AddressWhereInput>
  cases?: Prisma.CaseListRelationFilter
}

export type VictimInfoOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  pesel?: Prisma.SortOrder
  dateOfBirth?: Prisma.SortOrder
  placeOfBirth?: Prisma.SortOrder
  documentType?: Prisma.SortOrder
  documentNumber?: Prisma.SortOrder
  insuranceTitle?: Prisma.SortOrder
  addressId?: Prisma.SortOrder
  address?: Prisma.AddressOrderByWithRelationInput
  cases?: Prisma.CaseOrderByRelationAggregateInput
}

export type VictimInfoWhereUniqueInput = Prisma.AtLeast<
  {
    id?: string
    AND?: Prisma.VictimInfoWhereInput | Prisma.VictimInfoWhereInput[]
    OR?: Prisma.VictimInfoWhereInput[]
    NOT?: Prisma.VictimInfoWhereInput | Prisma.VictimInfoWhereInput[]
    name?: Prisma.StringFilter<"VictimInfo"> | string
    pesel?: Prisma.StringFilter<"VictimInfo"> | string
    dateOfBirth?: Prisma.DateTimeFilter<"VictimInfo"> | Date | string
    placeOfBirth?: Prisma.StringFilter<"VictimInfo"> | string
    documentType?: Prisma.EnumDocumentTypeFilter<"VictimInfo"> | $Enums.DocumentType
    documentNumber?: Prisma.StringFilter<"VictimInfo"> | string
    insuranceTitle?: Prisma.StringFilter<"VictimInfo"> | string
    addressId?: Prisma.StringFilter<"VictimInfo"> | string
    address?: Prisma.XOR<Prisma.AddressScalarRelationFilter, Prisma.AddressWhereInput>
    cases?: Prisma.CaseListRelationFilter
  },
  "id"
>

export type VictimInfoOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  pesel?: Prisma.SortOrder
  dateOfBirth?: Prisma.SortOrder
  placeOfBirth?: Prisma.SortOrder
  documentType?: Prisma.SortOrder
  documentNumber?: Prisma.SortOrder
  insuranceTitle?: Prisma.SortOrder
  addressId?: Prisma.SortOrder
  _count?: Prisma.VictimInfoCountOrderByAggregateInput
  _max?: Prisma.VictimInfoMaxOrderByAggregateInput
  _min?: Prisma.VictimInfoMinOrderByAggregateInput
}

export type VictimInfoScalarWhereWithAggregatesInput = {
  AND?:
    | Prisma.VictimInfoScalarWhereWithAggregatesInput
    | Prisma.VictimInfoScalarWhereWithAggregatesInput[]
  OR?: Prisma.VictimInfoScalarWhereWithAggregatesInput[]
  NOT?:
    | Prisma.VictimInfoScalarWhereWithAggregatesInput
    | Prisma.VictimInfoScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"VictimInfo"> | string
  name?: Prisma.StringWithAggregatesFilter<"VictimInfo"> | string
  pesel?: Prisma.StringWithAggregatesFilter<"VictimInfo"> | string
  dateOfBirth?: Prisma.DateTimeWithAggregatesFilter<"VictimInfo"> | Date | string
  placeOfBirth?: Prisma.StringWithAggregatesFilter<"VictimInfo"> | string
  documentType?: Prisma.EnumDocumentTypeWithAggregatesFilter<"VictimInfo"> | $Enums.DocumentType
  documentNumber?: Prisma.StringWithAggregatesFilter<"VictimInfo"> | string
  insuranceTitle?: Prisma.StringWithAggregatesFilter<"VictimInfo"> | string
  addressId?: Prisma.StringWithAggregatesFilter<"VictimInfo"> | string
}

export type VictimInfoCreateInput = {
  id?: string
  name: string
  pesel: string
  dateOfBirth: Date | string
  placeOfBirth: string
  documentType: $Enums.DocumentType
  documentNumber: string
  insuranceTitle: string
  address: Prisma.AddressCreateNestedOneWithoutVictimInfosInput
  cases?: Prisma.CaseCreateNestedManyWithoutVictimInfoInput
}

export type VictimInfoUncheckedCreateInput = {
  id?: string
  name: string
  pesel: string
  dateOfBirth: Date | string
  placeOfBirth: string
  documentType: $Enums.DocumentType
  documentNumber: string
  insuranceTitle: string
  addressId: string
  cases?: Prisma.CaseUncheckedCreateNestedManyWithoutVictimInfoInput
}

export type VictimInfoUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  pesel?: Prisma.StringFieldUpdateOperationsInput | string
  dateOfBirth?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  placeOfBirth?: Prisma.StringFieldUpdateOperationsInput | string
  documentType?: Prisma.EnumDocumentTypeFieldUpdateOperationsInput | $Enums.DocumentType
  documentNumber?: Prisma.StringFieldUpdateOperationsInput | string
  insuranceTitle?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.AddressUpdateOneRequiredWithoutVictimInfosNestedInput
  cases?: Prisma.CaseUpdateManyWithoutVictimInfoNestedInput
}

export type VictimInfoUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  pesel?: Prisma.StringFieldUpdateOperationsInput | string
  dateOfBirth?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  placeOfBirth?: Prisma.StringFieldUpdateOperationsInput | string
  documentType?: Prisma.EnumDocumentTypeFieldUpdateOperationsInput | $Enums.DocumentType
  documentNumber?: Prisma.StringFieldUpdateOperationsInput | string
  insuranceTitle?: Prisma.StringFieldUpdateOperationsInput | string
  addressId?: Prisma.StringFieldUpdateOperationsInput | string
  cases?: Prisma.CaseUncheckedUpdateManyWithoutVictimInfoNestedInput
}

export type VictimInfoCreateManyInput = {
  id?: string
  name: string
  pesel: string
  dateOfBirth: Date | string
  placeOfBirth: string
  documentType: $Enums.DocumentType
  documentNumber: string
  insuranceTitle: string
  addressId: string
}

export type VictimInfoUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  pesel?: Prisma.StringFieldUpdateOperationsInput | string
  dateOfBirth?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  placeOfBirth?: Prisma.StringFieldUpdateOperationsInput | string
  documentType?: Prisma.EnumDocumentTypeFieldUpdateOperationsInput | $Enums.DocumentType
  documentNumber?: Prisma.StringFieldUpdateOperationsInput | string
  insuranceTitle?: Prisma.StringFieldUpdateOperationsInput | string
}

export type VictimInfoUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  pesel?: Prisma.StringFieldUpdateOperationsInput | string
  dateOfBirth?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  placeOfBirth?: Prisma.StringFieldUpdateOperationsInput | string
  documentType?: Prisma.EnumDocumentTypeFieldUpdateOperationsInput | $Enums.DocumentType
  documentNumber?: Prisma.StringFieldUpdateOperationsInput | string
  insuranceTitle?: Prisma.StringFieldUpdateOperationsInput | string
  addressId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type VictimInfoScalarRelationFilter = {
  is?: Prisma.VictimInfoWhereInput
  isNot?: Prisma.VictimInfoWhereInput
}

export type VictimInfoCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  pesel?: Prisma.SortOrder
  dateOfBirth?: Prisma.SortOrder
  placeOfBirth?: Prisma.SortOrder
  documentType?: Prisma.SortOrder
  documentNumber?: Prisma.SortOrder
  insuranceTitle?: Prisma.SortOrder
  addressId?: Prisma.SortOrder
}

export type VictimInfoMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  pesel?: Prisma.SortOrder
  dateOfBirth?: Prisma.SortOrder
  placeOfBirth?: Prisma.SortOrder
  documentType?: Prisma.SortOrder
  documentNumber?: Prisma.SortOrder
  insuranceTitle?: Prisma.SortOrder
  addressId?: Prisma.SortOrder
}

export type VictimInfoMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  pesel?: Prisma.SortOrder
  dateOfBirth?: Prisma.SortOrder
  placeOfBirth?: Prisma.SortOrder
  documentType?: Prisma.SortOrder
  documentNumber?: Prisma.SortOrder
  insuranceTitle?: Prisma.SortOrder
  addressId?: Prisma.SortOrder
}

export type VictimInfoListRelationFilter = {
  every?: Prisma.VictimInfoWhereInput
  some?: Prisma.VictimInfoWhereInput
  none?: Prisma.VictimInfoWhereInput
}

export type VictimInfoOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type VictimInfoCreateNestedOneWithoutCasesInput = {
  create?: Prisma.XOR<
    Prisma.VictimInfoCreateWithoutCasesInput,
    Prisma.VictimInfoUncheckedCreateWithoutCasesInput
  >
  connectOrCreate?: Prisma.VictimInfoCreateOrConnectWithoutCasesInput
  connect?: Prisma.VictimInfoWhereUniqueInput
}

export type VictimInfoUpdateOneRequiredWithoutCasesNestedInput = {
  create?: Prisma.XOR<
    Prisma.VictimInfoCreateWithoutCasesInput,
    Prisma.VictimInfoUncheckedCreateWithoutCasesInput
  >
  connectOrCreate?: Prisma.VictimInfoCreateOrConnectWithoutCasesInput
  upsert?: Prisma.VictimInfoUpsertWithoutCasesInput
  connect?: Prisma.VictimInfoWhereUniqueInput
  update?: Prisma.XOR<
    Prisma.XOR<
      Prisma.VictimInfoUpdateToOneWithWhereWithoutCasesInput,
      Prisma.VictimInfoUpdateWithoutCasesInput
    >,
    Prisma.VictimInfoUncheckedUpdateWithoutCasesInput
  >
}

export type VictimInfoCreateNestedManyWithoutAddressInput = {
  create?:
    | Prisma.XOR<
        Prisma.VictimInfoCreateWithoutAddressInput,
        Prisma.VictimInfoUncheckedCreateWithoutAddressInput
      >
    | Prisma.VictimInfoCreateWithoutAddressInput[]
    | Prisma.VictimInfoUncheckedCreateWithoutAddressInput[]
  connectOrCreate?:
    | Prisma.VictimInfoCreateOrConnectWithoutAddressInput
    | Prisma.VictimInfoCreateOrConnectWithoutAddressInput[]
  createMany?: Prisma.VictimInfoCreateManyAddressInputEnvelope
  connect?: Prisma.VictimInfoWhereUniqueInput | Prisma.VictimInfoWhereUniqueInput[]
}

export type VictimInfoUncheckedCreateNestedManyWithoutAddressInput = {
  create?:
    | Prisma.XOR<
        Prisma.VictimInfoCreateWithoutAddressInput,
        Prisma.VictimInfoUncheckedCreateWithoutAddressInput
      >
    | Prisma.VictimInfoCreateWithoutAddressInput[]
    | Prisma.VictimInfoUncheckedCreateWithoutAddressInput[]
  connectOrCreate?:
    | Prisma.VictimInfoCreateOrConnectWithoutAddressInput
    | Prisma.VictimInfoCreateOrConnectWithoutAddressInput[]
  createMany?: Prisma.VictimInfoCreateManyAddressInputEnvelope
  connect?: Prisma.VictimInfoWhereUniqueInput | Prisma.VictimInfoWhereUniqueInput[]
}

export type VictimInfoUpdateManyWithoutAddressNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.VictimInfoCreateWithoutAddressInput,
        Prisma.VictimInfoUncheckedCreateWithoutAddressInput
      >
    | Prisma.VictimInfoCreateWithoutAddressInput[]
    | Prisma.VictimInfoUncheckedCreateWithoutAddressInput[]
  connectOrCreate?:
    | Prisma.VictimInfoCreateOrConnectWithoutAddressInput
    | Prisma.VictimInfoCreateOrConnectWithoutAddressInput[]
  upsert?:
    | Prisma.VictimInfoUpsertWithWhereUniqueWithoutAddressInput
    | Prisma.VictimInfoUpsertWithWhereUniqueWithoutAddressInput[]
  createMany?: Prisma.VictimInfoCreateManyAddressInputEnvelope
  set?: Prisma.VictimInfoWhereUniqueInput | Prisma.VictimInfoWhereUniqueInput[]
  disconnect?: Prisma.VictimInfoWhereUniqueInput | Prisma.VictimInfoWhereUniqueInput[]
  delete?: Prisma.VictimInfoWhereUniqueInput | Prisma.VictimInfoWhereUniqueInput[]
  connect?: Prisma.VictimInfoWhereUniqueInput | Prisma.VictimInfoWhereUniqueInput[]
  update?:
    | Prisma.VictimInfoUpdateWithWhereUniqueWithoutAddressInput
    | Prisma.VictimInfoUpdateWithWhereUniqueWithoutAddressInput[]
  updateMany?:
    | Prisma.VictimInfoUpdateManyWithWhereWithoutAddressInput
    | Prisma.VictimInfoUpdateManyWithWhereWithoutAddressInput[]
  deleteMany?: Prisma.VictimInfoScalarWhereInput | Prisma.VictimInfoScalarWhereInput[]
}

export type VictimInfoUncheckedUpdateManyWithoutAddressNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.VictimInfoCreateWithoutAddressInput,
        Prisma.VictimInfoUncheckedCreateWithoutAddressInput
      >
    | Prisma.VictimInfoCreateWithoutAddressInput[]
    | Prisma.VictimInfoUncheckedCreateWithoutAddressInput[]
  connectOrCreate?:
    | Prisma.VictimInfoCreateOrConnectWithoutAddressInput
    | Prisma.VictimInfoCreateOrConnectWithoutAddressInput[]
  upsert?:
    | Prisma.VictimInfoUpsertWithWhereUniqueWithoutAddressInput
    | Prisma.VictimInfoUpsertWithWhereUniqueWithoutAddressInput[]
  createMany?: Prisma.VictimInfoCreateManyAddressInputEnvelope
  set?: Prisma.VictimInfoWhereUniqueInput | Prisma.VictimInfoWhereUniqueInput[]
  disconnect?: Prisma.VictimInfoWhereUniqueInput | Prisma.VictimInfoWhereUniqueInput[]
  delete?: Prisma.VictimInfoWhereUniqueInput | Prisma.VictimInfoWhereUniqueInput[]
  connect?: Prisma.VictimInfoWhereUniqueInput | Prisma.VictimInfoWhereUniqueInput[]
  update?:
    | Prisma.VictimInfoUpdateWithWhereUniqueWithoutAddressInput
    | Prisma.VictimInfoUpdateWithWhereUniqueWithoutAddressInput[]
  updateMany?:
    | Prisma.VictimInfoUpdateManyWithWhereWithoutAddressInput
    | Prisma.VictimInfoUpdateManyWithWhereWithoutAddressInput[]
  deleteMany?: Prisma.VictimInfoScalarWhereInput | Prisma.VictimInfoScalarWhereInput[]
}

export type VictimInfoCreateWithoutCasesInput = {
  id?: string
  name: string
  pesel: string
  dateOfBirth: Date | string
  placeOfBirth: string
  documentType: $Enums.DocumentType
  documentNumber: string
  insuranceTitle: string
  address: Prisma.AddressCreateNestedOneWithoutVictimInfosInput
}

export type VictimInfoUncheckedCreateWithoutCasesInput = {
  id?: string
  name: string
  pesel: string
  dateOfBirth: Date | string
  placeOfBirth: string
  documentType: $Enums.DocumentType
  documentNumber: string
  insuranceTitle: string
  addressId: string
}

export type VictimInfoCreateOrConnectWithoutCasesInput = {
  where: Prisma.VictimInfoWhereUniqueInput
  create: Prisma.XOR<
    Prisma.VictimInfoCreateWithoutCasesInput,
    Prisma.VictimInfoUncheckedCreateWithoutCasesInput
  >
}

export type VictimInfoUpsertWithoutCasesInput = {
  update: Prisma.XOR<
    Prisma.VictimInfoUpdateWithoutCasesInput,
    Prisma.VictimInfoUncheckedUpdateWithoutCasesInput
  >
  create: Prisma.XOR<
    Prisma.VictimInfoCreateWithoutCasesInput,
    Prisma.VictimInfoUncheckedCreateWithoutCasesInput
  >
  where?: Prisma.VictimInfoWhereInput
}

export type VictimInfoUpdateToOneWithWhereWithoutCasesInput = {
  where?: Prisma.VictimInfoWhereInput
  data: Prisma.XOR<
    Prisma.VictimInfoUpdateWithoutCasesInput,
    Prisma.VictimInfoUncheckedUpdateWithoutCasesInput
  >
}

export type VictimInfoUpdateWithoutCasesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  pesel?: Prisma.StringFieldUpdateOperationsInput | string
  dateOfBirth?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  placeOfBirth?: Prisma.StringFieldUpdateOperationsInput | string
  documentType?: Prisma.EnumDocumentTypeFieldUpdateOperationsInput | $Enums.DocumentType
  documentNumber?: Prisma.StringFieldUpdateOperationsInput | string
  insuranceTitle?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.AddressUpdateOneRequiredWithoutVictimInfosNestedInput
}

export type VictimInfoUncheckedUpdateWithoutCasesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  pesel?: Prisma.StringFieldUpdateOperationsInput | string
  dateOfBirth?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  placeOfBirth?: Prisma.StringFieldUpdateOperationsInput | string
  documentType?: Prisma.EnumDocumentTypeFieldUpdateOperationsInput | $Enums.DocumentType
  documentNumber?: Prisma.StringFieldUpdateOperationsInput | string
  insuranceTitle?: Prisma.StringFieldUpdateOperationsInput | string
  addressId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type VictimInfoCreateWithoutAddressInput = {
  id?: string
  name: string
  pesel: string
  dateOfBirth: Date | string
  placeOfBirth: string
  documentType: $Enums.DocumentType
  documentNumber: string
  insuranceTitle: string
  cases?: Prisma.CaseCreateNestedManyWithoutVictimInfoInput
}

export type VictimInfoUncheckedCreateWithoutAddressInput = {
  id?: string
  name: string
  pesel: string
  dateOfBirth: Date | string
  placeOfBirth: string
  documentType: $Enums.DocumentType
  documentNumber: string
  insuranceTitle: string
  cases?: Prisma.CaseUncheckedCreateNestedManyWithoutVictimInfoInput
}

export type VictimInfoCreateOrConnectWithoutAddressInput = {
  where: Prisma.VictimInfoWhereUniqueInput
  create: Prisma.XOR<
    Prisma.VictimInfoCreateWithoutAddressInput,
    Prisma.VictimInfoUncheckedCreateWithoutAddressInput
  >
}

export type VictimInfoCreateManyAddressInputEnvelope = {
  data: Prisma.VictimInfoCreateManyAddressInput | Prisma.VictimInfoCreateManyAddressInput[]
  skipDuplicates?: boolean
}

export type VictimInfoUpsertWithWhereUniqueWithoutAddressInput = {
  where: Prisma.VictimInfoWhereUniqueInput
  update: Prisma.XOR<
    Prisma.VictimInfoUpdateWithoutAddressInput,
    Prisma.VictimInfoUncheckedUpdateWithoutAddressInput
  >
  create: Prisma.XOR<
    Prisma.VictimInfoCreateWithoutAddressInput,
    Prisma.VictimInfoUncheckedCreateWithoutAddressInput
  >
}

export type VictimInfoUpdateWithWhereUniqueWithoutAddressInput = {
  where: Prisma.VictimInfoWhereUniqueInput
  data: Prisma.XOR<
    Prisma.VictimInfoUpdateWithoutAddressInput,
    Prisma.VictimInfoUncheckedUpdateWithoutAddressInput
  >
}

export type VictimInfoUpdateManyWithWhereWithoutAddressInput = {
  where: Prisma.VictimInfoScalarWhereInput
  data: Prisma.XOR<
    Prisma.VictimInfoUpdateManyMutationInput,
    Prisma.VictimInfoUncheckedUpdateManyWithoutAddressInput
  >
}

export type VictimInfoScalarWhereInput = {
  AND?: Prisma.VictimInfoScalarWhereInput | Prisma.VictimInfoScalarWhereInput[]
  OR?: Prisma.VictimInfoScalarWhereInput[]
  NOT?: Prisma.VictimInfoScalarWhereInput | Prisma.VictimInfoScalarWhereInput[]
  id?: Prisma.StringFilter<"VictimInfo"> | string
  name?: Prisma.StringFilter<"VictimInfo"> | string
  pesel?: Prisma.StringFilter<"VictimInfo"> | string
  dateOfBirth?: Prisma.DateTimeFilter<"VictimInfo"> | Date | string
  placeOfBirth?: Prisma.StringFilter<"VictimInfo"> | string
  documentType?: Prisma.EnumDocumentTypeFilter<"VictimInfo"> | $Enums.DocumentType
  documentNumber?: Prisma.StringFilter<"VictimInfo"> | string
  insuranceTitle?: Prisma.StringFilter<"VictimInfo"> | string
  addressId?: Prisma.StringFilter<"VictimInfo"> | string
}

export type VictimInfoCreateManyAddressInput = {
  id?: string
  name: string
  pesel: string
  dateOfBirth: Date | string
  placeOfBirth: string
  documentType: $Enums.DocumentType
  documentNumber: string
  insuranceTitle: string
}

export type VictimInfoUpdateWithoutAddressInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  pesel?: Prisma.StringFieldUpdateOperationsInput | string
  dateOfBirth?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  placeOfBirth?: Prisma.StringFieldUpdateOperationsInput | string
  documentType?: Prisma.EnumDocumentTypeFieldUpdateOperationsInput | $Enums.DocumentType
  documentNumber?: Prisma.StringFieldUpdateOperationsInput | string
  insuranceTitle?: Prisma.StringFieldUpdateOperationsInput | string
  cases?: Prisma.CaseUpdateManyWithoutVictimInfoNestedInput
}

export type VictimInfoUncheckedUpdateWithoutAddressInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  pesel?: Prisma.StringFieldUpdateOperationsInput | string
  dateOfBirth?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  placeOfBirth?: Prisma.StringFieldUpdateOperationsInput | string
  documentType?: Prisma.EnumDocumentTypeFieldUpdateOperationsInput | $Enums.DocumentType
  documentNumber?: Prisma.StringFieldUpdateOperationsInput | string
  insuranceTitle?: Prisma.StringFieldUpdateOperationsInput | string
  cases?: Prisma.CaseUncheckedUpdateManyWithoutVictimInfoNestedInput
}

export type VictimInfoUncheckedUpdateManyWithoutAddressInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  pesel?: Prisma.StringFieldUpdateOperationsInput | string
  dateOfBirth?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  placeOfBirth?: Prisma.StringFieldUpdateOperationsInput | string
  documentType?: Prisma.EnumDocumentTypeFieldUpdateOperationsInput | $Enums.DocumentType
  documentNumber?: Prisma.StringFieldUpdateOperationsInput | string
  insuranceTitle?: Prisma.StringFieldUpdateOperationsInput | string
}

/**
 * Count Type VictimInfoCountOutputType
 */

export type VictimInfoCountOutputType = {
  cases: number
}

export type VictimInfoCountOutputTypeSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  cases?: boolean | VictimInfoCountOutputTypeCountCasesArgs
}

/**
 * VictimInfoCountOutputType without action
 */
export type VictimInfoCountOutputTypeDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the VictimInfoCountOutputType
   */
  select?: Prisma.VictimInfoCountOutputTypeSelect<ExtArgs> | null
}

/**
 * VictimInfoCountOutputType without action
 */
export type VictimInfoCountOutputTypeCountCasesArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.CaseWhereInput
}

export type VictimInfoSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean
    name?: boolean
    pesel?: boolean
    dateOfBirth?: boolean
    placeOfBirth?: boolean
    documentType?: boolean
    documentNumber?: boolean
    insuranceTitle?: boolean
    addressId?: boolean
    address?: boolean | Prisma.AddressDefaultArgs<ExtArgs>
    cases?: boolean | Prisma.VictimInfo$casesArgs<ExtArgs>
    _count?: boolean | Prisma.VictimInfoCountOutputTypeDefaultArgs<ExtArgs>
  },
  ExtArgs["result"]["victimInfo"]
>

export type VictimInfoSelectCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean
    name?: boolean
    pesel?: boolean
    dateOfBirth?: boolean
    placeOfBirth?: boolean
    documentType?: boolean
    documentNumber?: boolean
    insuranceTitle?: boolean
    addressId?: boolean
    address?: boolean | Prisma.AddressDefaultArgs<ExtArgs>
  },
  ExtArgs["result"]["victimInfo"]
>

export type VictimInfoSelectUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean
    name?: boolean
    pesel?: boolean
    dateOfBirth?: boolean
    placeOfBirth?: boolean
    documentType?: boolean
    documentNumber?: boolean
    insuranceTitle?: boolean
    addressId?: boolean
    address?: boolean | Prisma.AddressDefaultArgs<ExtArgs>
  },
  ExtArgs["result"]["victimInfo"]
>

export type VictimInfoSelectScalar = {
  id?: boolean
  name?: boolean
  pesel?: boolean
  dateOfBirth?: boolean
  placeOfBirth?: boolean
  documentType?: boolean
  documentNumber?: boolean
  insuranceTitle?: boolean
  addressId?: boolean
}

export type VictimInfoOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  | "id"
  | "name"
  | "pesel"
  | "dateOfBirth"
  | "placeOfBirth"
  | "documentType"
  | "documentNumber"
  | "insuranceTitle"
  | "addressId",
  ExtArgs["result"]["victimInfo"]
>
export type VictimInfoInclude<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  address?: boolean | Prisma.AddressDefaultArgs<ExtArgs>
  cases?: boolean | Prisma.VictimInfo$casesArgs<ExtArgs>
  _count?: boolean | Prisma.VictimInfoCountOutputTypeDefaultArgs<ExtArgs>
}
export type VictimInfoIncludeCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  address?: boolean | Prisma.AddressDefaultArgs<ExtArgs>
}
export type VictimInfoIncludeUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  address?: boolean | Prisma.AddressDefaultArgs<ExtArgs>
}

export type $VictimInfoPayload<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  name: "VictimInfo"
  objects: {
    address: Prisma.$AddressPayload<ExtArgs>
    cases: Prisma.$CasePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<
    {
      id: string
      name: string
      pesel: string
      dateOfBirth: Date
      placeOfBirth: string
      documentType: $Enums.DocumentType
      documentNumber: string
      insuranceTitle: string
      addressId: string
    },
    ExtArgs["result"]["victimInfo"]
  >
  composites: {}
}

export type VictimInfoGetPayload<S extends boolean | null | undefined | VictimInfoDefaultArgs> =
  runtime.Types.Result.GetResult<Prisma.$VictimInfoPayload, S>

export type VictimInfoCountArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = Omit<VictimInfoFindManyArgs, "select" | "include" | "distinct" | "omit"> & {
  select?: VictimInfoCountAggregateInputType | true
}

export interface VictimInfoDelegate<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> {
  [K: symbol]: {
    types: Prisma.TypeMap<ExtArgs>["model"]["VictimInfo"]
    meta: { name: "VictimInfo" }
  }
  /**
   * Find zero or one VictimInfo that matches the filter.
   * @param {VictimInfoFindUniqueArgs} args - Arguments to find a VictimInfo
   * @example
   * // Get one VictimInfo
   * const victimInfo = await prisma.victimInfo.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends VictimInfoFindUniqueArgs>(
    args: Prisma.SelectSubset<T, VictimInfoFindUniqueArgs<ExtArgs>>,
  ): Prisma.Prisma__VictimInfoClient<
    runtime.Types.Result.GetResult<
      Prisma.$VictimInfoPayload<ExtArgs>,
      T,
      "findUnique",
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find one VictimInfo that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {VictimInfoFindUniqueOrThrowArgs} args - Arguments to find a VictimInfo
   * @example
   * // Get one VictimInfo
   * const victimInfo = await prisma.victimInfo.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends VictimInfoFindUniqueOrThrowArgs>(
    args: Prisma.SelectSubset<T, VictimInfoFindUniqueOrThrowArgs<ExtArgs>>,
  ): Prisma.Prisma__VictimInfoClient<
    runtime.Types.Result.GetResult<
      Prisma.$VictimInfoPayload<ExtArgs>,
      T,
      "findUniqueOrThrow",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find the first VictimInfo that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VictimInfoFindFirstArgs} args - Arguments to find a VictimInfo
   * @example
   * // Get one VictimInfo
   * const victimInfo = await prisma.victimInfo.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends VictimInfoFindFirstArgs>(
    args?: Prisma.SelectSubset<T, VictimInfoFindFirstArgs<ExtArgs>>,
  ): Prisma.Prisma__VictimInfoClient<
    runtime.Types.Result.GetResult<
      Prisma.$VictimInfoPayload<ExtArgs>,
      T,
      "findFirst",
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find the first VictimInfo that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VictimInfoFindFirstOrThrowArgs} args - Arguments to find a VictimInfo
   * @example
   * // Get one VictimInfo
   * const victimInfo = await prisma.victimInfo.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends VictimInfoFindFirstOrThrowArgs>(
    args?: Prisma.SelectSubset<T, VictimInfoFindFirstOrThrowArgs<ExtArgs>>,
  ): Prisma.Prisma__VictimInfoClient<
    runtime.Types.Result.GetResult<
      Prisma.$VictimInfoPayload<ExtArgs>,
      T,
      "findFirstOrThrow",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find zero or more VictimInfos that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VictimInfoFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all VictimInfos
   * const victimInfos = await prisma.victimInfo.findMany()
   *
   * // Get first 10 VictimInfos
   * const victimInfos = await prisma.victimInfo.findMany({ take: 10 })
   *
   * // Only select the `id`
   * const victimInfoWithIdOnly = await prisma.victimInfo.findMany({ select: { id: true } })
   *
   */
  findMany<T extends VictimInfoFindManyArgs>(
    args?: Prisma.SelectSubset<T, VictimInfoFindManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$VictimInfoPayload<ExtArgs>,
      T,
      "findMany",
      GlobalOmitOptions
    >
  >

  /**
   * Create a VictimInfo.
   * @param {VictimInfoCreateArgs} args - Arguments to create a VictimInfo.
   * @example
   * // Create one VictimInfo
   * const VictimInfo = await prisma.victimInfo.create({
   *   data: {
   *     // ... data to create a VictimInfo
   *   }
   * })
   *
   */
  create<T extends VictimInfoCreateArgs>(
    args: Prisma.SelectSubset<T, VictimInfoCreateArgs<ExtArgs>>,
  ): Prisma.Prisma__VictimInfoClient<
    runtime.Types.Result.GetResult<
      Prisma.$VictimInfoPayload<ExtArgs>,
      T,
      "create",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Create many VictimInfos.
   * @param {VictimInfoCreateManyArgs} args - Arguments to create many VictimInfos.
   * @example
   * // Create many VictimInfos
   * const victimInfo = await prisma.victimInfo.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends VictimInfoCreateManyArgs>(
    args?: Prisma.SelectSubset<T, VictimInfoCreateManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many VictimInfos and returns the data saved in the database.
   * @param {VictimInfoCreateManyAndReturnArgs} args - Arguments to create many VictimInfos.
   * @example
   * // Create many VictimInfos
   * const victimInfo = await prisma.victimInfo.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Create many VictimInfos and only return the `id`
   * const victimInfoWithIdOnly = await prisma.victimInfo.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  createManyAndReturn<T extends VictimInfoCreateManyAndReturnArgs>(
    args?: Prisma.SelectSubset<T, VictimInfoCreateManyAndReturnArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$VictimInfoPayload<ExtArgs>,
      T,
      "createManyAndReturn",
      GlobalOmitOptions
    >
  >

  /**
   * Delete a VictimInfo.
   * @param {VictimInfoDeleteArgs} args - Arguments to delete one VictimInfo.
   * @example
   * // Delete one VictimInfo
   * const VictimInfo = await prisma.victimInfo.delete({
   *   where: {
   *     // ... filter to delete one VictimInfo
   *   }
   * })
   *
   */
  delete<T extends VictimInfoDeleteArgs>(
    args: Prisma.SelectSubset<T, VictimInfoDeleteArgs<ExtArgs>>,
  ): Prisma.Prisma__VictimInfoClient<
    runtime.Types.Result.GetResult<
      Prisma.$VictimInfoPayload<ExtArgs>,
      T,
      "delete",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Update one VictimInfo.
   * @param {VictimInfoUpdateArgs} args - Arguments to update one VictimInfo.
   * @example
   * // Update one VictimInfo
   * const victimInfo = await prisma.victimInfo.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends VictimInfoUpdateArgs>(
    args: Prisma.SelectSubset<T, VictimInfoUpdateArgs<ExtArgs>>,
  ): Prisma.Prisma__VictimInfoClient<
    runtime.Types.Result.GetResult<
      Prisma.$VictimInfoPayload<ExtArgs>,
      T,
      "update",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Delete zero or more VictimInfos.
   * @param {VictimInfoDeleteManyArgs} args - Arguments to filter VictimInfos to delete.
   * @example
   * // Delete a few VictimInfos
   * const { count } = await prisma.victimInfo.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends VictimInfoDeleteManyArgs>(
    args?: Prisma.SelectSubset<T, VictimInfoDeleteManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more VictimInfos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VictimInfoUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many VictimInfos
   * const victimInfo = await prisma.victimInfo.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends VictimInfoUpdateManyArgs>(
    args: Prisma.SelectSubset<T, VictimInfoUpdateManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more VictimInfos and returns the data updated in the database.
   * @param {VictimInfoUpdateManyAndReturnArgs} args - Arguments to update many VictimInfos.
   * @example
   * // Update many VictimInfos
   * const victimInfo = await prisma.victimInfo.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Update zero or more VictimInfos and only return the `id`
   * const victimInfoWithIdOnly = await prisma.victimInfo.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  updateManyAndReturn<T extends VictimInfoUpdateManyAndReturnArgs>(
    args: Prisma.SelectSubset<T, VictimInfoUpdateManyAndReturnArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$VictimInfoPayload<ExtArgs>,
      T,
      "updateManyAndReturn",
      GlobalOmitOptions
    >
  >

  /**
   * Create or update one VictimInfo.
   * @param {VictimInfoUpsertArgs} args - Arguments to update or create a VictimInfo.
   * @example
   * // Update or create a VictimInfo
   * const victimInfo = await prisma.victimInfo.upsert({
   *   create: {
   *     // ... data to create a VictimInfo
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the VictimInfo we want to update
   *   }
   * })
   */
  upsert<T extends VictimInfoUpsertArgs>(
    args: Prisma.SelectSubset<T, VictimInfoUpsertArgs<ExtArgs>>,
  ): Prisma.Prisma__VictimInfoClient<
    runtime.Types.Result.GetResult<
      Prisma.$VictimInfoPayload<ExtArgs>,
      T,
      "upsert",
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Count the number of VictimInfos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VictimInfoCountArgs} args - Arguments to filter VictimInfos to count.
   * @example
   * // Count the number of VictimInfos
   * const count = await prisma.victimInfo.count({
   *   where: {
   *     // ... the filter for the VictimInfos we want to count
   *   }
   * })
   **/
  count<T extends VictimInfoCountArgs>(
    args?: Prisma.Subset<T, VictimInfoCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<"select", any>
      ? T["select"] extends true
        ? number
        : Prisma.GetScalarType<T["select"], VictimInfoCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a VictimInfo.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VictimInfoAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
   **/
  aggregate<T extends VictimInfoAggregateArgs>(
    args: Prisma.Subset<T, VictimInfoAggregateArgs>,
  ): Prisma.PrismaPromise<GetVictimInfoAggregateType<T>>

  /**
   * Group by VictimInfo.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VictimInfoGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
   **/
  groupBy<
    T extends VictimInfoGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<"skip", Prisma.Keys<T>>,
      Prisma.Extends<"take", Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: VictimInfoGroupByArgs["orderBy"] }
      : { orderBy?: VictimInfoGroupByArgs["orderBy"] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<
      Prisma.Keys<Prisma.MaybeTupleToUnion<T["orderBy"]>>
    >,
    ByFields extends Prisma.MaybeTupleToUnion<T["by"]>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T["having"]>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T["by"] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
      ? `Error: "by" must not be empty.`
      : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
                ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                : [Error, "Field ", P, ` in "having" needs to be provided in "by"`]
          }[HavingFields]
        : "take" extends Prisma.Keys<T>
          ? "orderBy" extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                }[OrderFields]
            : 'Error: If you provide "take", you also need to provide "orderBy"'
          : "skip" extends Prisma.Keys<T>
            ? "orderBy" extends Prisma.Keys<T>
              ? ByValid extends Prisma.True
                ? {}
                : {
                    [P in OrderFields]: P extends ByFields
                      ? never
                      : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                  }[OrderFields]
              : 'Error: If you provide "skip", you also need to provide "orderBy"'
            : ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                }[OrderFields],
  >(
    args: Prisma.SubsetIntersection<T, VictimInfoGroupByArgs, OrderByArg> & InputErrors,
  ): {} extends InputErrors ? GetVictimInfoGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
  /**
   * Fields of the VictimInfo model
   */
  readonly fields: VictimInfoFieldRefs
}

/**
 * The delegate class that acts as a "Promise-like" for VictimInfo.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__VictimInfoClient<
  T,
  Null = never,
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  address<T extends Prisma.AddressDefaultArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.AddressDefaultArgs<ExtArgs>>,
  ): Prisma.Prisma__AddressClient<
    | runtime.Types.Result.GetResult<
        Prisma.$AddressPayload<ExtArgs>,
        T,
        "findUniqueOrThrow",
        GlobalOmitOptions
      >
    | Null,
    Null,
    ExtArgs,
    GlobalOmitOptions
  >
  cases<T extends Prisma.VictimInfo$casesArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.VictimInfo$casesArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    | runtime.Types.Result.GetResult<Prisma.$CasePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>
    | Null
  >
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(
    onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null,
    onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null,
  ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(
    onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null,
  ): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}

/**
 * Fields of the VictimInfo model
 */
export interface VictimInfoFieldRefs {
  readonly id: Prisma.FieldRef<"VictimInfo", "String">
  readonly name: Prisma.FieldRef<"VictimInfo", "String">
  readonly pesel: Prisma.FieldRef<"VictimInfo", "String">
  readonly dateOfBirth: Prisma.FieldRef<"VictimInfo", "DateTime">
  readonly placeOfBirth: Prisma.FieldRef<"VictimInfo", "String">
  readonly documentType: Prisma.FieldRef<"VictimInfo", "DocumentType">
  readonly documentNumber: Prisma.FieldRef<"VictimInfo", "String">
  readonly insuranceTitle: Prisma.FieldRef<"VictimInfo", "String">
  readonly addressId: Prisma.FieldRef<"VictimInfo", "String">
}

// Custom InputTypes
/**
 * VictimInfo findUnique
 */
export type VictimInfoFindUniqueArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the VictimInfo
   */
  select?: Prisma.VictimInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VictimInfo
   */
  omit?: Prisma.VictimInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VictimInfoInclude<ExtArgs> | null
  /**
   * Filter, which VictimInfo to fetch.
   */
  where: Prisma.VictimInfoWhereUniqueInput
}

/**
 * VictimInfo findUniqueOrThrow
 */
export type VictimInfoFindUniqueOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the VictimInfo
   */
  select?: Prisma.VictimInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VictimInfo
   */
  omit?: Prisma.VictimInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VictimInfoInclude<ExtArgs> | null
  /**
   * Filter, which VictimInfo to fetch.
   */
  where: Prisma.VictimInfoWhereUniqueInput
}

/**
 * VictimInfo findFirst
 */
export type VictimInfoFindFirstArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the VictimInfo
   */
  select?: Prisma.VictimInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VictimInfo
   */
  omit?: Prisma.VictimInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VictimInfoInclude<ExtArgs> | null
  /**
   * Filter, which VictimInfo to fetch.
   */
  where?: Prisma.VictimInfoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of VictimInfos to fetch.
   */
  orderBy?: Prisma.VictimInfoOrderByWithRelationInput | Prisma.VictimInfoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for VictimInfos.
   */
  cursor?: Prisma.VictimInfoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` VictimInfos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` VictimInfos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of VictimInfos.
   */
  distinct?: Prisma.VictimInfoScalarFieldEnum | Prisma.VictimInfoScalarFieldEnum[]
}

/**
 * VictimInfo findFirstOrThrow
 */
export type VictimInfoFindFirstOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the VictimInfo
   */
  select?: Prisma.VictimInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VictimInfo
   */
  omit?: Prisma.VictimInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VictimInfoInclude<ExtArgs> | null
  /**
   * Filter, which VictimInfo to fetch.
   */
  where?: Prisma.VictimInfoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of VictimInfos to fetch.
   */
  orderBy?: Prisma.VictimInfoOrderByWithRelationInput | Prisma.VictimInfoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for VictimInfos.
   */
  cursor?: Prisma.VictimInfoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` VictimInfos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` VictimInfos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of VictimInfos.
   */
  distinct?: Prisma.VictimInfoScalarFieldEnum | Prisma.VictimInfoScalarFieldEnum[]
}

/**
 * VictimInfo findMany
 */
export type VictimInfoFindManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the VictimInfo
   */
  select?: Prisma.VictimInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VictimInfo
   */
  omit?: Prisma.VictimInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VictimInfoInclude<ExtArgs> | null
  /**
   * Filter, which VictimInfos to fetch.
   */
  where?: Prisma.VictimInfoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of VictimInfos to fetch.
   */
  orderBy?: Prisma.VictimInfoOrderByWithRelationInput | Prisma.VictimInfoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing VictimInfos.
   */
  cursor?: Prisma.VictimInfoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` VictimInfos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` VictimInfos.
   */
  skip?: number
  distinct?: Prisma.VictimInfoScalarFieldEnum | Prisma.VictimInfoScalarFieldEnum[]
}

/**
 * VictimInfo create
 */
export type VictimInfoCreateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the VictimInfo
   */
  select?: Prisma.VictimInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VictimInfo
   */
  omit?: Prisma.VictimInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VictimInfoInclude<ExtArgs> | null
  /**
   * The data needed to create a VictimInfo.
   */
  data: Prisma.XOR<Prisma.VictimInfoCreateInput, Prisma.VictimInfoUncheckedCreateInput>
}

/**
 * VictimInfo createMany
 */
export type VictimInfoCreateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to create many VictimInfos.
   */
  data: Prisma.VictimInfoCreateManyInput | Prisma.VictimInfoCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * VictimInfo createManyAndReturn
 */
export type VictimInfoCreateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the VictimInfo
   */
  select?: Prisma.VictimInfoSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the VictimInfo
   */
  omit?: Prisma.VictimInfoOmit<ExtArgs> | null
  /**
   * The data used to create many VictimInfos.
   */
  data: Prisma.VictimInfoCreateManyInput | Prisma.VictimInfoCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VictimInfoIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * VictimInfo update
 */
export type VictimInfoUpdateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the VictimInfo
   */
  select?: Prisma.VictimInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VictimInfo
   */
  omit?: Prisma.VictimInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VictimInfoInclude<ExtArgs> | null
  /**
   * The data needed to update a VictimInfo.
   */
  data: Prisma.XOR<Prisma.VictimInfoUpdateInput, Prisma.VictimInfoUncheckedUpdateInput>
  /**
   * Choose, which VictimInfo to update.
   */
  where: Prisma.VictimInfoWhereUniqueInput
}

/**
 * VictimInfo updateMany
 */
export type VictimInfoUpdateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to update VictimInfos.
   */
  data: Prisma.XOR<
    Prisma.VictimInfoUpdateManyMutationInput,
    Prisma.VictimInfoUncheckedUpdateManyInput
  >
  /**
   * Filter which VictimInfos to update
   */
  where?: Prisma.VictimInfoWhereInput
  /**
   * Limit how many VictimInfos to update.
   */
  limit?: number
}

/**
 * VictimInfo updateManyAndReturn
 */
export type VictimInfoUpdateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the VictimInfo
   */
  select?: Prisma.VictimInfoSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the VictimInfo
   */
  omit?: Prisma.VictimInfoOmit<ExtArgs> | null
  /**
   * The data used to update VictimInfos.
   */
  data: Prisma.XOR<
    Prisma.VictimInfoUpdateManyMutationInput,
    Prisma.VictimInfoUncheckedUpdateManyInput
  >
  /**
   * Filter which VictimInfos to update
   */
  where?: Prisma.VictimInfoWhereInput
  /**
   * Limit how many VictimInfos to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VictimInfoIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * VictimInfo upsert
 */
export type VictimInfoUpsertArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the VictimInfo
   */
  select?: Prisma.VictimInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VictimInfo
   */
  omit?: Prisma.VictimInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VictimInfoInclude<ExtArgs> | null
  /**
   * The filter to search for the VictimInfo to update in case it exists.
   */
  where: Prisma.VictimInfoWhereUniqueInput
  /**
   * In case the VictimInfo found by the `where` argument doesn't exist, create a new VictimInfo with this data.
   */
  create: Prisma.XOR<Prisma.VictimInfoCreateInput, Prisma.VictimInfoUncheckedCreateInput>
  /**
   * In case the VictimInfo was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.VictimInfoUpdateInput, Prisma.VictimInfoUncheckedUpdateInput>
}

/**
 * VictimInfo delete
 */
export type VictimInfoDeleteArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the VictimInfo
   */
  select?: Prisma.VictimInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VictimInfo
   */
  omit?: Prisma.VictimInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VictimInfoInclude<ExtArgs> | null
  /**
   * Filter which VictimInfo to delete.
   */
  where: Prisma.VictimInfoWhereUniqueInput
}

/**
 * VictimInfo deleteMany
 */
export type VictimInfoDeleteManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which VictimInfos to delete
   */
  where?: Prisma.VictimInfoWhereInput
  /**
   * Limit how many VictimInfos to delete.
   */
  limit?: number
}

/**
 * VictimInfo.cases
 */
export type VictimInfo$casesArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Case
   */
  select?: Prisma.CaseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Case
   */
  omit?: Prisma.CaseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CaseInclude<ExtArgs> | null
  where?: Prisma.CaseWhereInput
  orderBy?: Prisma.CaseOrderByWithRelationInput | Prisma.CaseOrderByWithRelationInput[]
  cursor?: Prisma.CaseWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.CaseScalarFieldEnum | Prisma.CaseScalarFieldEnum[]
}

/**
 * VictimInfo without action
 */
export type VictimInfoDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the VictimInfo
   */
  select?: Prisma.VictimInfoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VictimInfo
   */
  omit?: Prisma.VictimInfoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VictimInfoInclude<ExtArgs> | null
}
