
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Witness` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Witness
 * 
 */
export type WitnessModel = runtime.Types.Result.DefaultSelection<Prisma.$WitnessPayload>

export type AggregateWitness = {
  _count: WitnessCountAggregateOutputType | null
  _min: WitnessMinAggregateOutputType | null
  _max: WitnessMaxAggregateOutputType | null
}

export type WitnessMinAggregateOutputType = {
  id: string | null
  name: string | null
  contact: string | null
  accidentInfoId: string | null
}

export type WitnessMaxAggregateOutputType = {
  id: string | null
  name: string | null
  contact: string | null
  accidentInfoId: string | null
}

export type WitnessCountAggregateOutputType = {
  id: number
  name: number
  contact: number
  accidentInfoId: number
  _all: number
}


export type WitnessMinAggregateInputType = {
  id?: true
  name?: true
  contact?: true
  accidentInfoId?: true
}

export type WitnessMaxAggregateInputType = {
  id?: true
  name?: true
  contact?: true
  accidentInfoId?: true
}

export type WitnessCountAggregateInputType = {
  id?: true
  name?: true
  contact?: true
  accidentInfoId?: true
  _all?: true
}

export type WitnessAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Witness to aggregate.
   */
  where?: Prisma.WitnessWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Witnesses to fetch.
   */
  orderBy?: Prisma.WitnessOrderByWithRelationInput | Prisma.WitnessOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.WitnessWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Witnesses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Witnesses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Witnesses
  **/
  _count?: true | WitnessCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: WitnessMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: WitnessMaxAggregateInputType
}

export type GetWitnessAggregateType<T extends WitnessAggregateArgs> = {
      [P in keyof T & keyof AggregateWitness]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateWitness[P]>
    : Prisma.GetScalarType<T[P], AggregateWitness[P]>
}




export type WitnessGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.WitnessWhereInput
  orderBy?: Prisma.WitnessOrderByWithAggregationInput | Prisma.WitnessOrderByWithAggregationInput[]
  by: Prisma.WitnessScalarFieldEnum[] | Prisma.WitnessScalarFieldEnum
  having?: Prisma.WitnessScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: WitnessCountAggregateInputType | true
  _min?: WitnessMinAggregateInputType
  _max?: WitnessMaxAggregateInputType
}

export type WitnessGroupByOutputType = {
  id: string
  name: string
  contact: string
  accidentInfoId: string
  _count: WitnessCountAggregateOutputType | null
  _min: WitnessMinAggregateOutputType | null
  _max: WitnessMaxAggregateOutputType | null
}

type GetWitnessGroupByPayload<T extends WitnessGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<WitnessGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof WitnessGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], WitnessGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], WitnessGroupByOutputType[P]>
      }
    >
  >



export type WitnessWhereInput = {
  AND?: Prisma.WitnessWhereInput | Prisma.WitnessWhereInput[]
  OR?: Prisma.WitnessWhereInput[]
  NOT?: Prisma.WitnessWhereInput | Prisma.WitnessWhereInput[]
  id?: Prisma.StringFilter<"Witness"> | string
  name?: Prisma.StringFilter<"Witness"> | string
  contact?: Prisma.StringFilter<"Witness"> | string
  accidentInfoId?: Prisma.StringFilter<"Witness"> | string
  accidentInfo?: Prisma.XOR<Prisma.AccidentInfoScalarRelationFilter, Prisma.AccidentInfoWhereInput>
}

export type WitnessOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  contact?: Prisma.SortOrder
  accidentInfoId?: Prisma.SortOrder
  accidentInfo?: Prisma.AccidentInfoOrderByWithRelationInput
}

export type WitnessWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.WitnessWhereInput | Prisma.WitnessWhereInput[]
  OR?: Prisma.WitnessWhereInput[]
  NOT?: Prisma.WitnessWhereInput | Prisma.WitnessWhereInput[]
  name?: Prisma.StringFilter<"Witness"> | string
  contact?: Prisma.StringFilter<"Witness"> | string
  accidentInfoId?: Prisma.StringFilter<"Witness"> | string
  accidentInfo?: Prisma.XOR<Prisma.AccidentInfoScalarRelationFilter, Prisma.AccidentInfoWhereInput>
}, "id">

export type WitnessOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  contact?: Prisma.SortOrder
  accidentInfoId?: Prisma.SortOrder
  _count?: Prisma.WitnessCountOrderByAggregateInput
  _max?: Prisma.WitnessMaxOrderByAggregateInput
  _min?: Prisma.WitnessMinOrderByAggregateInput
}

export type WitnessScalarWhereWithAggregatesInput = {
  AND?: Prisma.WitnessScalarWhereWithAggregatesInput | Prisma.WitnessScalarWhereWithAggregatesInput[]
  OR?: Prisma.WitnessScalarWhereWithAggregatesInput[]
  NOT?: Prisma.WitnessScalarWhereWithAggregatesInput | Prisma.WitnessScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Witness"> | string
  name?: Prisma.StringWithAggregatesFilter<"Witness"> | string
  contact?: Prisma.StringWithAggregatesFilter<"Witness"> | string
  accidentInfoId?: Prisma.StringWithAggregatesFilter<"Witness"> | string
}

export type WitnessCreateInput = {
  id?: string
  name: string
  contact: string
  accidentInfo: Prisma.AccidentInfoCreateNestedOneWithoutWitnessesInput
}

export type WitnessUncheckedCreateInput = {
  id?: string
  name: string
  contact: string
  accidentInfoId: string
}

export type WitnessUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  contact?: Prisma.StringFieldUpdateOperationsInput | string
  accidentInfo?: Prisma.AccidentInfoUpdateOneRequiredWithoutWitnessesNestedInput
}

export type WitnessUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  contact?: Prisma.StringFieldUpdateOperationsInput | string
  accidentInfoId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type WitnessCreateManyInput = {
  id?: string
  name: string
  contact: string
  accidentInfoId: string
}

export type WitnessUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  contact?: Prisma.StringFieldUpdateOperationsInput | string
}

export type WitnessUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  contact?: Prisma.StringFieldUpdateOperationsInput | string
  accidentInfoId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type WitnessListRelationFilter = {
  every?: Prisma.WitnessWhereInput
  some?: Prisma.WitnessWhereInput
  none?: Prisma.WitnessWhereInput
}

export type WitnessOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type WitnessCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  contact?: Prisma.SortOrder
  accidentInfoId?: Prisma.SortOrder
}

export type WitnessMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  contact?: Prisma.SortOrder
  accidentInfoId?: Prisma.SortOrder
}

export type WitnessMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  contact?: Prisma.SortOrder
  accidentInfoId?: Prisma.SortOrder
}

export type WitnessCreateNestedManyWithoutAccidentInfoInput = {
  create?: Prisma.XOR<Prisma.WitnessCreateWithoutAccidentInfoInput, Prisma.WitnessUncheckedCreateWithoutAccidentInfoInput> | Prisma.WitnessCreateWithoutAccidentInfoInput[] | Prisma.WitnessUncheckedCreateWithoutAccidentInfoInput[]
  connectOrCreate?: Prisma.WitnessCreateOrConnectWithoutAccidentInfoInput | Prisma.WitnessCreateOrConnectWithoutAccidentInfoInput[]
  createMany?: Prisma.WitnessCreateManyAccidentInfoInputEnvelope
  connect?: Prisma.WitnessWhereUniqueInput | Prisma.WitnessWhereUniqueInput[]
}

export type WitnessUncheckedCreateNestedManyWithoutAccidentInfoInput = {
  create?: Prisma.XOR<Prisma.WitnessCreateWithoutAccidentInfoInput, Prisma.WitnessUncheckedCreateWithoutAccidentInfoInput> | Prisma.WitnessCreateWithoutAccidentInfoInput[] | Prisma.WitnessUncheckedCreateWithoutAccidentInfoInput[]
  connectOrCreate?: Prisma.WitnessCreateOrConnectWithoutAccidentInfoInput | Prisma.WitnessCreateOrConnectWithoutAccidentInfoInput[]
  createMany?: Prisma.WitnessCreateManyAccidentInfoInputEnvelope
  connect?: Prisma.WitnessWhereUniqueInput | Prisma.WitnessWhereUniqueInput[]
}

export type WitnessUpdateManyWithoutAccidentInfoNestedInput = {
  create?: Prisma.XOR<Prisma.WitnessCreateWithoutAccidentInfoInput, Prisma.WitnessUncheckedCreateWithoutAccidentInfoInput> | Prisma.WitnessCreateWithoutAccidentInfoInput[] | Prisma.WitnessUncheckedCreateWithoutAccidentInfoInput[]
  connectOrCreate?: Prisma.WitnessCreateOrConnectWithoutAccidentInfoInput | Prisma.WitnessCreateOrConnectWithoutAccidentInfoInput[]
  upsert?: Prisma.WitnessUpsertWithWhereUniqueWithoutAccidentInfoInput | Prisma.WitnessUpsertWithWhereUniqueWithoutAccidentInfoInput[]
  createMany?: Prisma.WitnessCreateManyAccidentInfoInputEnvelope
  set?: Prisma.WitnessWhereUniqueInput | Prisma.WitnessWhereUniqueInput[]
  disconnect?: Prisma.WitnessWhereUniqueInput | Prisma.WitnessWhereUniqueInput[]
  delete?: Prisma.WitnessWhereUniqueInput | Prisma.WitnessWhereUniqueInput[]
  connect?: Prisma.WitnessWhereUniqueInput | Prisma.WitnessWhereUniqueInput[]
  update?: Prisma.WitnessUpdateWithWhereUniqueWithoutAccidentInfoInput | Prisma.WitnessUpdateWithWhereUniqueWithoutAccidentInfoInput[]
  updateMany?: Prisma.WitnessUpdateManyWithWhereWithoutAccidentInfoInput | Prisma.WitnessUpdateManyWithWhereWithoutAccidentInfoInput[]
  deleteMany?: Prisma.WitnessScalarWhereInput | Prisma.WitnessScalarWhereInput[]
}

export type WitnessUncheckedUpdateManyWithoutAccidentInfoNestedInput = {
  create?: Prisma.XOR<Prisma.WitnessCreateWithoutAccidentInfoInput, Prisma.WitnessUncheckedCreateWithoutAccidentInfoInput> | Prisma.WitnessCreateWithoutAccidentInfoInput[] | Prisma.WitnessUncheckedCreateWithoutAccidentInfoInput[]
  connectOrCreate?: Prisma.WitnessCreateOrConnectWithoutAccidentInfoInput | Prisma.WitnessCreateOrConnectWithoutAccidentInfoInput[]
  upsert?: Prisma.WitnessUpsertWithWhereUniqueWithoutAccidentInfoInput | Prisma.WitnessUpsertWithWhereUniqueWithoutAccidentInfoInput[]
  createMany?: Prisma.WitnessCreateManyAccidentInfoInputEnvelope
  set?: Prisma.WitnessWhereUniqueInput | Prisma.WitnessWhereUniqueInput[]
  disconnect?: Prisma.WitnessWhereUniqueInput | Prisma.WitnessWhereUniqueInput[]
  delete?: Prisma.WitnessWhereUniqueInput | Prisma.WitnessWhereUniqueInput[]
  connect?: Prisma.WitnessWhereUniqueInput | Prisma.WitnessWhereUniqueInput[]
  update?: Prisma.WitnessUpdateWithWhereUniqueWithoutAccidentInfoInput | Prisma.WitnessUpdateWithWhereUniqueWithoutAccidentInfoInput[]
  updateMany?: Prisma.WitnessUpdateManyWithWhereWithoutAccidentInfoInput | Prisma.WitnessUpdateManyWithWhereWithoutAccidentInfoInput[]
  deleteMany?: Prisma.WitnessScalarWhereInput | Prisma.WitnessScalarWhereInput[]
}

export type WitnessCreateWithoutAccidentInfoInput = {
  id?: string
  name: string
  contact: string
}

export type WitnessUncheckedCreateWithoutAccidentInfoInput = {
  id?: string
  name: string
  contact: string
}

export type WitnessCreateOrConnectWithoutAccidentInfoInput = {
  where: Prisma.WitnessWhereUniqueInput
  create: Prisma.XOR<Prisma.WitnessCreateWithoutAccidentInfoInput, Prisma.WitnessUncheckedCreateWithoutAccidentInfoInput>
}

export type WitnessCreateManyAccidentInfoInputEnvelope = {
  data: Prisma.WitnessCreateManyAccidentInfoInput | Prisma.WitnessCreateManyAccidentInfoInput[]
  skipDuplicates?: boolean
}

export type WitnessUpsertWithWhereUniqueWithoutAccidentInfoInput = {
  where: Prisma.WitnessWhereUniqueInput
  update: Prisma.XOR<Prisma.WitnessUpdateWithoutAccidentInfoInput, Prisma.WitnessUncheckedUpdateWithoutAccidentInfoInput>
  create: Prisma.XOR<Prisma.WitnessCreateWithoutAccidentInfoInput, Prisma.WitnessUncheckedCreateWithoutAccidentInfoInput>
}

export type WitnessUpdateWithWhereUniqueWithoutAccidentInfoInput = {
  where: Prisma.WitnessWhereUniqueInput
  data: Prisma.XOR<Prisma.WitnessUpdateWithoutAccidentInfoInput, Prisma.WitnessUncheckedUpdateWithoutAccidentInfoInput>
}

export type WitnessUpdateManyWithWhereWithoutAccidentInfoInput = {
  where: Prisma.WitnessScalarWhereInput
  data: Prisma.XOR<Prisma.WitnessUpdateManyMutationInput, Prisma.WitnessUncheckedUpdateManyWithoutAccidentInfoInput>
}

export type WitnessScalarWhereInput = {
  AND?: Prisma.WitnessScalarWhereInput | Prisma.WitnessScalarWhereInput[]
  OR?: Prisma.WitnessScalarWhereInput[]
  NOT?: Prisma.WitnessScalarWhereInput | Prisma.WitnessScalarWhereInput[]
  id?: Prisma.StringFilter<"Witness"> | string
  name?: Prisma.StringFilter<"Witness"> | string
  contact?: Prisma.StringFilter<"Witness"> | string
  accidentInfoId?: Prisma.StringFilter<"Witness"> | string
}

export type WitnessCreateManyAccidentInfoInput = {
  id?: string
  name: string
  contact: string
}

export type WitnessUpdateWithoutAccidentInfoInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  contact?: Prisma.StringFieldUpdateOperationsInput | string
}

export type WitnessUncheckedUpdateWithoutAccidentInfoInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  contact?: Prisma.StringFieldUpdateOperationsInput | string
}

export type WitnessUncheckedUpdateManyWithoutAccidentInfoInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  contact?: Prisma.StringFieldUpdateOperationsInput | string
}



export type WitnessSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  contact?: boolean
  accidentInfoId?: boolean
  accidentInfo?: boolean | Prisma.AccidentInfoDefaultArgs<ExtArgs>
}, ExtArgs["result"]["witness"]>

export type WitnessSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  contact?: boolean
  accidentInfoId?: boolean
  accidentInfo?: boolean | Prisma.AccidentInfoDefaultArgs<ExtArgs>
}, ExtArgs["result"]["witness"]>

export type WitnessSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  contact?: boolean
  accidentInfoId?: boolean
  accidentInfo?: boolean | Prisma.AccidentInfoDefaultArgs<ExtArgs>
}, ExtArgs["result"]["witness"]>

export type WitnessSelectScalar = {
  id?: boolean
  name?: boolean
  contact?: boolean
  accidentInfoId?: boolean
}

export type WitnessOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "contact" | "accidentInfoId", ExtArgs["result"]["witness"]>
export type WitnessInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  accidentInfo?: boolean | Prisma.AccidentInfoDefaultArgs<ExtArgs>
}
export type WitnessIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  accidentInfo?: boolean | Prisma.AccidentInfoDefaultArgs<ExtArgs>
}
export type WitnessIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  accidentInfo?: boolean | Prisma.AccidentInfoDefaultArgs<ExtArgs>
}

export type $WitnessPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Witness"
  objects: {
    accidentInfo: Prisma.$AccidentInfoPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    contact: string
    accidentInfoId: string
  }, ExtArgs["result"]["witness"]>
  composites: {}
}

export type WitnessGetPayload<S extends boolean | null | undefined | WitnessDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$WitnessPayload, S>

export type WitnessCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<WitnessFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: WitnessCountAggregateInputType | true
  }

export interface WitnessDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Witness'], meta: { name: 'Witness' } }
  /**
   * Find zero or one Witness that matches the filter.
   * @param {WitnessFindUniqueArgs} args - Arguments to find a Witness
   * @example
   * // Get one Witness
   * const witness = await prisma.witness.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends WitnessFindUniqueArgs>(args: Prisma.SelectSubset<T, WitnessFindUniqueArgs<ExtArgs>>): Prisma.Prisma__WitnessClient<runtime.Types.Result.GetResult<Prisma.$WitnessPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Witness that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {WitnessFindUniqueOrThrowArgs} args - Arguments to find a Witness
   * @example
   * // Get one Witness
   * const witness = await prisma.witness.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends WitnessFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, WitnessFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__WitnessClient<runtime.Types.Result.GetResult<Prisma.$WitnessPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Witness that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WitnessFindFirstArgs} args - Arguments to find a Witness
   * @example
   * // Get one Witness
   * const witness = await prisma.witness.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends WitnessFindFirstArgs>(args?: Prisma.SelectSubset<T, WitnessFindFirstArgs<ExtArgs>>): Prisma.Prisma__WitnessClient<runtime.Types.Result.GetResult<Prisma.$WitnessPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Witness that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WitnessFindFirstOrThrowArgs} args - Arguments to find a Witness
   * @example
   * // Get one Witness
   * const witness = await prisma.witness.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends WitnessFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, WitnessFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__WitnessClient<runtime.Types.Result.GetResult<Prisma.$WitnessPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Witnesses that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WitnessFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Witnesses
   * const witnesses = await prisma.witness.findMany()
   * 
   * // Get first 10 Witnesses
   * const witnesses = await prisma.witness.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const witnessWithIdOnly = await prisma.witness.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends WitnessFindManyArgs>(args?: Prisma.SelectSubset<T, WitnessFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WitnessPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Witness.
   * @param {WitnessCreateArgs} args - Arguments to create a Witness.
   * @example
   * // Create one Witness
   * const Witness = await prisma.witness.create({
   *   data: {
   *     // ... data to create a Witness
   *   }
   * })
   * 
   */
  create<T extends WitnessCreateArgs>(args: Prisma.SelectSubset<T, WitnessCreateArgs<ExtArgs>>): Prisma.Prisma__WitnessClient<runtime.Types.Result.GetResult<Prisma.$WitnessPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Witnesses.
   * @param {WitnessCreateManyArgs} args - Arguments to create many Witnesses.
   * @example
   * // Create many Witnesses
   * const witness = await prisma.witness.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends WitnessCreateManyArgs>(args?: Prisma.SelectSubset<T, WitnessCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Witnesses and returns the data saved in the database.
   * @param {WitnessCreateManyAndReturnArgs} args - Arguments to create many Witnesses.
   * @example
   * // Create many Witnesses
   * const witness = await prisma.witness.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Witnesses and only return the `id`
   * const witnessWithIdOnly = await prisma.witness.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends WitnessCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, WitnessCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WitnessPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Witness.
   * @param {WitnessDeleteArgs} args - Arguments to delete one Witness.
   * @example
   * // Delete one Witness
   * const Witness = await prisma.witness.delete({
   *   where: {
   *     // ... filter to delete one Witness
   *   }
   * })
   * 
   */
  delete<T extends WitnessDeleteArgs>(args: Prisma.SelectSubset<T, WitnessDeleteArgs<ExtArgs>>): Prisma.Prisma__WitnessClient<runtime.Types.Result.GetResult<Prisma.$WitnessPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Witness.
   * @param {WitnessUpdateArgs} args - Arguments to update one Witness.
   * @example
   * // Update one Witness
   * const witness = await prisma.witness.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends WitnessUpdateArgs>(args: Prisma.SelectSubset<T, WitnessUpdateArgs<ExtArgs>>): Prisma.Prisma__WitnessClient<runtime.Types.Result.GetResult<Prisma.$WitnessPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Witnesses.
   * @param {WitnessDeleteManyArgs} args - Arguments to filter Witnesses to delete.
   * @example
   * // Delete a few Witnesses
   * const { count } = await prisma.witness.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends WitnessDeleteManyArgs>(args?: Prisma.SelectSubset<T, WitnessDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Witnesses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WitnessUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Witnesses
   * const witness = await prisma.witness.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends WitnessUpdateManyArgs>(args: Prisma.SelectSubset<T, WitnessUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Witnesses and returns the data updated in the database.
   * @param {WitnessUpdateManyAndReturnArgs} args - Arguments to update many Witnesses.
   * @example
   * // Update many Witnesses
   * const witness = await prisma.witness.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Witnesses and only return the `id`
   * const witnessWithIdOnly = await prisma.witness.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends WitnessUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, WitnessUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WitnessPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Witness.
   * @param {WitnessUpsertArgs} args - Arguments to update or create a Witness.
   * @example
   * // Update or create a Witness
   * const witness = await prisma.witness.upsert({
   *   create: {
   *     // ... data to create a Witness
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Witness we want to update
   *   }
   * })
   */
  upsert<T extends WitnessUpsertArgs>(args: Prisma.SelectSubset<T, WitnessUpsertArgs<ExtArgs>>): Prisma.Prisma__WitnessClient<runtime.Types.Result.GetResult<Prisma.$WitnessPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Witnesses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WitnessCountArgs} args - Arguments to filter Witnesses to count.
   * @example
   * // Count the number of Witnesses
   * const count = await prisma.witness.count({
   *   where: {
   *     // ... the filter for the Witnesses we want to count
   *   }
   * })
  **/
  count<T extends WitnessCountArgs>(
    args?: Prisma.Subset<T, WitnessCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], WitnessCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Witness.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WitnessAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends WitnessAggregateArgs>(args: Prisma.Subset<T, WitnessAggregateArgs>): Prisma.PrismaPromise<GetWitnessAggregateType<T>>

  /**
   * Group by Witness.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WitnessGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends WitnessGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: WitnessGroupByArgs['orderBy'] }
      : { orderBy?: WitnessGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, WitnessGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetWitnessGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Witness model
 */
readonly fields: WitnessFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Witness.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__WitnessClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  accidentInfo<T extends Prisma.AccidentInfoDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AccidentInfoDefaultArgs<ExtArgs>>): Prisma.Prisma__AccidentInfoClient<runtime.Types.Result.GetResult<Prisma.$AccidentInfoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Witness model
 */
export interface WitnessFieldRefs {
  readonly id: Prisma.FieldRef<"Witness", 'String'>
  readonly name: Prisma.FieldRef<"Witness", 'String'>
  readonly contact: Prisma.FieldRef<"Witness", 'String'>
  readonly accidentInfoId: Prisma.FieldRef<"Witness", 'String'>
}
    

// Custom InputTypes
/**
 * Witness findUnique
 */
export type WitnessFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Witness
   */
  select?: Prisma.WitnessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Witness
   */
  omit?: Prisma.WitnessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WitnessInclude<ExtArgs> | null
  /**
   * Filter, which Witness to fetch.
   */
  where: Prisma.WitnessWhereUniqueInput
}

/**
 * Witness findUniqueOrThrow
 */
export type WitnessFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Witness
   */
  select?: Prisma.WitnessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Witness
   */
  omit?: Prisma.WitnessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WitnessInclude<ExtArgs> | null
  /**
   * Filter, which Witness to fetch.
   */
  where: Prisma.WitnessWhereUniqueInput
}

/**
 * Witness findFirst
 */
export type WitnessFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Witness
   */
  select?: Prisma.WitnessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Witness
   */
  omit?: Prisma.WitnessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WitnessInclude<ExtArgs> | null
  /**
   * Filter, which Witness to fetch.
   */
  where?: Prisma.WitnessWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Witnesses to fetch.
   */
  orderBy?: Prisma.WitnessOrderByWithRelationInput | Prisma.WitnessOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Witnesses.
   */
  cursor?: Prisma.WitnessWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Witnesses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Witnesses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Witnesses.
   */
  distinct?: Prisma.WitnessScalarFieldEnum | Prisma.WitnessScalarFieldEnum[]
}

/**
 * Witness findFirstOrThrow
 */
export type WitnessFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Witness
   */
  select?: Prisma.WitnessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Witness
   */
  omit?: Prisma.WitnessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WitnessInclude<ExtArgs> | null
  /**
   * Filter, which Witness to fetch.
   */
  where?: Prisma.WitnessWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Witnesses to fetch.
   */
  orderBy?: Prisma.WitnessOrderByWithRelationInput | Prisma.WitnessOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Witnesses.
   */
  cursor?: Prisma.WitnessWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Witnesses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Witnesses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Witnesses.
   */
  distinct?: Prisma.WitnessScalarFieldEnum | Prisma.WitnessScalarFieldEnum[]
}

/**
 * Witness findMany
 */
export type WitnessFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Witness
   */
  select?: Prisma.WitnessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Witness
   */
  omit?: Prisma.WitnessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WitnessInclude<ExtArgs> | null
  /**
   * Filter, which Witnesses to fetch.
   */
  where?: Prisma.WitnessWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Witnesses to fetch.
   */
  orderBy?: Prisma.WitnessOrderByWithRelationInput | Prisma.WitnessOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Witnesses.
   */
  cursor?: Prisma.WitnessWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Witnesses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Witnesses.
   */
  skip?: number
  distinct?: Prisma.WitnessScalarFieldEnum | Prisma.WitnessScalarFieldEnum[]
}

/**
 * Witness create
 */
export type WitnessCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Witness
   */
  select?: Prisma.WitnessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Witness
   */
  omit?: Prisma.WitnessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WitnessInclude<ExtArgs> | null
  /**
   * The data needed to create a Witness.
   */
  data: Prisma.XOR<Prisma.WitnessCreateInput, Prisma.WitnessUncheckedCreateInput>
}

/**
 * Witness createMany
 */
export type WitnessCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Witnesses.
   */
  data: Prisma.WitnessCreateManyInput | Prisma.WitnessCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Witness createManyAndReturn
 */
export type WitnessCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Witness
   */
  select?: Prisma.WitnessSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Witness
   */
  omit?: Prisma.WitnessOmit<ExtArgs> | null
  /**
   * The data used to create many Witnesses.
   */
  data: Prisma.WitnessCreateManyInput | Prisma.WitnessCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WitnessIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Witness update
 */
export type WitnessUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Witness
   */
  select?: Prisma.WitnessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Witness
   */
  omit?: Prisma.WitnessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WitnessInclude<ExtArgs> | null
  /**
   * The data needed to update a Witness.
   */
  data: Prisma.XOR<Prisma.WitnessUpdateInput, Prisma.WitnessUncheckedUpdateInput>
  /**
   * Choose, which Witness to update.
   */
  where: Prisma.WitnessWhereUniqueInput
}

/**
 * Witness updateMany
 */
export type WitnessUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Witnesses.
   */
  data: Prisma.XOR<Prisma.WitnessUpdateManyMutationInput, Prisma.WitnessUncheckedUpdateManyInput>
  /**
   * Filter which Witnesses to update
   */
  where?: Prisma.WitnessWhereInput
  /**
   * Limit how many Witnesses to update.
   */
  limit?: number
}

/**
 * Witness updateManyAndReturn
 */
export type WitnessUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Witness
   */
  select?: Prisma.WitnessSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Witness
   */
  omit?: Prisma.WitnessOmit<ExtArgs> | null
  /**
   * The data used to update Witnesses.
   */
  data: Prisma.XOR<Prisma.WitnessUpdateManyMutationInput, Prisma.WitnessUncheckedUpdateManyInput>
  /**
   * Filter which Witnesses to update
   */
  where?: Prisma.WitnessWhereInput
  /**
   * Limit how many Witnesses to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WitnessIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Witness upsert
 */
export type WitnessUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Witness
   */
  select?: Prisma.WitnessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Witness
   */
  omit?: Prisma.WitnessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WitnessInclude<ExtArgs> | null
  /**
   * The filter to search for the Witness to update in case it exists.
   */
  where: Prisma.WitnessWhereUniqueInput
  /**
   * In case the Witness found by the `where` argument doesn't exist, create a new Witness with this data.
   */
  create: Prisma.XOR<Prisma.WitnessCreateInput, Prisma.WitnessUncheckedCreateInput>
  /**
   * In case the Witness was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.WitnessUpdateInput, Prisma.WitnessUncheckedUpdateInput>
}

/**
 * Witness delete
 */
export type WitnessDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Witness
   */
  select?: Prisma.WitnessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Witness
   */
  omit?: Prisma.WitnessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WitnessInclude<ExtArgs> | null
  /**
   * Filter which Witness to delete.
   */
  where: Prisma.WitnessWhereUniqueInput
}

/**
 * Witness deleteMany
 */
export type WitnessDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Witnesses to delete
   */
  where?: Prisma.WitnessWhereInput
  /**
   * Limit how many Witnesses to delete.
   */
  limit?: number
}

/**
 * Witness without action
 */
export type WitnessDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Witness
   */
  select?: Prisma.WitnessSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Witness
   */
  omit?: Prisma.WitnessOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WitnessInclude<ExtArgs> | null
}
