/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from "../models"
export type * from "./prismaNamespace"

export const Decimal = runtime.Decimal

export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as new (secret: never) => typeof runtime.DbNull,
  JsonNull: runtime.NullTypes.JsonNull as new (secret: never) => typeof runtime.JsonNull,
  AnyNull: runtime.NullTypes.AnyNull as new (secret: never) => typeof runtime.AnyNull,
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull

export const ModelName = {
  Case: "Case",
  PayerInfo: "PayerInfo",
  VictimInfo: "VictimInfo",
  AccidentInfo: "AccidentInfo",
  Address: "Address",
  File: "File",
  Witness: "Witness",
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = {
  ReadUncommitted: "ReadUncommitted",
  ReadCommitted: "ReadCommitted",
  RepeatableRead: "RepeatableRead",
  Serializable: "Serializable",
} as const

export type TransactionIsolationLevel =
  (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]

export const CaseScalarFieldEnum = {
  id: "id",
  caseNumber: "caseNumber",
  comments: "comments",
  payerInfoId: "payerInfoId",
  victimInfoId: "victimInfoId",
  cardOfAccidentId: "cardOfAccidentId",
  createdAt: "createdAt",
  updatedAt: "updatedAt",
  accidentInfoId: "accidentInfoId",
} as const

export type CaseScalarFieldEnum = (typeof CaseScalarFieldEnum)[keyof typeof CaseScalarFieldEnum]

export const PayerInfoScalarFieldEnum = {
  id: "id",
  payerName: "payerName",
  documentType: "documentType",
  documentNumber: "documentNumber",
  nip: "nip",
  regon: "regon",
  pesel: "pesel",
  addressId: "addressId",
} as const

export type PayerInfoScalarFieldEnum =
  (typeof PayerInfoScalarFieldEnum)[keyof typeof PayerInfoScalarFieldEnum]

export const VictimInfoScalarFieldEnum = {
  id: "id",
  name: "name",
  pesel: "pesel",
  dateOfBirth: "dateOfBirth",
  placeOfBirth: "placeOfBirth",
  documentType: "documentType",
  documentNumber: "documentNumber",
  insuranceTitle: "insuranceTitle",
  addressId: "addressId",
} as const

export type VictimInfoScalarFieldEnum =
  (typeof VictimInfoScalarFieldEnum)[keyof typeof VictimInfoScalarFieldEnum]

export const AccidentInfoScalarFieldEnum = {
  id: "id",
  date: "date",
  nameOfReporter: "nameOfReporter",
  info: "info",
  isWorkAccident: "isWorkAccident",
  isVictimFault: "isVictimFault",
  isDrunk: "isDrunk",
} as const

export type AccidentInfoScalarFieldEnum =
  (typeof AccidentInfoScalarFieldEnum)[keyof typeof AccidentInfoScalarFieldEnum]

export const AddressScalarFieldEnum = {
  id: "id",
  street: "street",
  city: "city",
  postalCode: "postalCode",
  country: "country",
} as const

export type AddressScalarFieldEnum =
  (typeof AddressScalarFieldEnum)[keyof typeof AddressScalarFieldEnum]

export const FileScalarFieldEnum = {
  id: "id",
  file: "file",
  createdAt: "createdAt",
  updatedAt: "updatedAt",
} as const

export type FileScalarFieldEnum = (typeof FileScalarFieldEnum)[keyof typeof FileScalarFieldEnum]

export const WitnessScalarFieldEnum = {
  id: "id",
  name: "name",
  contact: "contact",
  accidentInfoId: "accidentInfoId",
} as const

export type WitnessScalarFieldEnum =
  (typeof WitnessScalarFieldEnum)[keyof typeof WitnessScalarFieldEnum]

export const SortOrder = {
  asc: "asc",
  desc: "desc",
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]

export const QueryMode = {
  default: "default",
  insensitive: "insensitive",
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]

export const NullsOrder = {
  first: "first",
  last: "last",
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]
