/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser.
 * Use it to get access to models, enums, and input types.
 *
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from "./internal/prismaNamespaceBrowser"
export { Prisma }
export * as $Enums from "./enums"
export * from "./enums"
/**
 * Model Case
 *
 */
export type Case = Prisma.CaseModel
/**
 * Model PayerInfo
 *
 */
export type PayerInfo = Prisma.PayerInfoModel
/**
 * Model VictimInfo
 *
 */
export type VictimInfo = Prisma.VictimInfoModel
/**
 * Model AccidentInfo
 *
 */
export type AccidentInfo = Prisma.AccidentInfoModel
/**
 * Model Address
 *
 */
export type Address = Prisma.AddressModel
/**
 * Model File
 *
 */
export type File = Prisma.FileModel
/**
 * Model Witness
 *
 */
export type Witness = Prisma.WitnessModel
