/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from "./models/Case"
export type * from "./models/PayerInfo"
export type * from "./models/VictimInfo"
export type * from "./models/AccidentInfo"
export type * from "./models/Address"
export type * from "./models/File"
export type * from "./models/Witness"
export type * from "./commonInputTypes"
